### ISSUE TITLE
DisplayMagician does not launch

### ISSUE THREAD

**Issue by pl4sma2389** [terrymacdonald/DisplayMagician#114]
**Describe the bug**
The software does not appear to launch, whether running as Admin or regular.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install DisplayMagician
2. Launch it from the shortcut or the executable file

**Expected behaviour**
I would expect it to launch and appear on a screen or in the taskbar.

**Screenshots**
N/A

**Reporting Logs**
[DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/8804744/DisplayMagician.zip)

**Enviroment (please complete the following information):**
 - Windows Version: Win11
 - DisplayMagician Version: v2.3.1.60
 - Video Card: Asus NVIDIA RTX 3080
 - Number and make/model of monitors: 3x Acer KW272U
 - Date of last video driver update: 2022-5-26
 - Date of last windows update: 2022-5-31

**Additional context**
Fresh Windows install, new computer, new monitors.

**Comment by terrymacdonald** [comment]
@pl4sma2389 So DisplayMagician appears to be hanging when it is trying to get the taskbar location. You're the second person to have that problem.

Do you use a different display language in Windows other than English? I wonder if the Taskbar logic is failing because of that?

Or do you have the taskbar in a different place? Or do you run some other taskbar moving software? Or anything that changes the taskbar?

I'm also going to go through and add some exception handling to the DisplayMagician code, so see if I can make it a bit more robust in that section of the codebase.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@pl4sma2389 To make sure that I've fixed the taskbar location in my custom WinLibrary. I'll need you to test NVIDIAInfo, a little app that I wrote specifically to test the NVIDIALibrary and WinLibrary that I wrote. Because I want to only test the video manipulation works with multiple video cards, we don't want to test DisplayMagician. We want to test with NVIDIAInfo so that we only test NVIDIALibrary and WinLibrary.

Once we can confirm that NVIDIALibrary and WinLibrary work then we know they will work in DisplayMagician.

Can you please download and extract the latest NVIDIAInfo zip file to a folder on your computer from here: https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.7.7
 
Open a PowerShell window, and change to the same folder that you extracted NVIDIAInfo into.

**IMPORTANT - These instructions are likely to fail, so I need you to save/rename the NVIDIAInfo.log file as shown below. Each run of NVIDIAInfo overwrites the previous NVIDIAInfo.log, so I need you to rename it each time so it doesn't get overwritten. I need to see the log file entries to know what is broken.**

Please complete the following instructions in this specific order:

Create a surround display layout with some of your screens then:
- Save the first config as `NVIDIAInfo save surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)

Next create a second windows display layout, this time with individual triple screen:
- Save the second windows display as `NVIDIAInfo save triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-save.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Check if the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we want it to NOT be equal)

Next create a third windows display layout, this time with a cloned display in it:
- Save the second windows display as `NVIDIAInfo save cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-save.log"`
- Check if the third windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to NOT be equal)
- Check if the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we want it to NOT be equal)

Next swap back to the surround display layout:
- Load the first windows display as `NVIDIAInfo load surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save surround-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal triple.cfg` (we DO NOT want it to be equal)

Next swap back to the triple screen display layout again:
- Load the second windows display as `NVIDIAInfo load triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save triple-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Next swap back to the cloned screen display layout again:
- Load the second windows display as `NVIDIAInfo load cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save cloned-reload.cfg`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- surround.cfg
- surround-reload.cfg
- NVIDIAInfo-surround-save.log
- NVIDIAInfo-surround-reload.log
- triple.cfg
- triple-reload.cfg
- NVIDIAInfo-triple-save.log
- NVIDIAInfo-triple-reload.log
- cloned.cfg
- cloned-reload.cfg
- NVIDIAInfo-cloned-save.log
- NVIDIAInfo-cloned-reload.log

This will give me all the information I need to know whether it worked! This will help me confirm that NVIDIALibrary and WinLibrary are ready to be integrated back into DisplayMagician. 

Thanks
Terry

**Comment by pl4sma2389** [comment]
> Do you use a different display language in Windows other than English? I wonder if the Taskbar logic is failing because of that?

Nope.

> Or do you have the taskbar in a different place? Or do you run some other taskbar moving software? Or anything that changes the taskbar?

No, not really, and... yes, I use ExplorerPatcher- that might mess up the taskbar in the way you're talking about: https://github.com/valinet/ExplorerPatcher

I'll run the tests in a minute.

**Comment by pl4sma2389** [comment]
> Check if the second windows display config is equal with NVIDIAInfo equal triple.cfg (we want it to be equal)

This test returned NOT equal. All other tests returned as expected. Zip file is attached. 

[NVIDIAInfo-v1.7.7.zip](https://github.com/terrymacdonald/DisplayMagician/files/8822658/NVIDIAInfo-v1.7.7.zip)

**Comment by terrymacdonald** [comment]
Thanks! I'll take a look at the results in the morning before work.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@pl4sma2389 Excellent. That really helped, as it looks like Windows changes the order of a couple of displays sometimes, and that is messing with equality testing! That's what happened with triple.cfg and triple-reload.cfg - they are both valid CFG files because they both will work, but due to the display ordering the equality testing doesn't work properly.

I know what I need to do now. It is a little bit difficult to test, but now that I have a couple of test cfg files to test with I should be able to fix the bug. It might take a while to get the code written though :(. We'll soon see how difficult it is.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@pl4sma2389 Can you please download NVIDIAInfo v1.7.8 from here: https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.7.8

NVIDIAInfo v1.7.8 should fix the equality test problems you experienced before. But I'll need you to test again. 

Please perform all the **equality** tests again only from the last set of instructions I gave you. Please tell me whether they all worked, or if they failed, which equality tests failed.

Thanks
Terry

**Comment by pl4sma2389** [comment]
@terrymacdonald I just finished running the equality tests with the new version after using the new version to save and reload the profiles in the same manner as I ran the tests the first time, and all of the equality tests passed as expected.

However, once I was finished, I tried to reload the triple config while in the cloned config state, and it didn't apply correctly. The program returned "ERROR - NVIDIAInfo Windows CCD settings were not applied correctly.", and while it looks correct on my screen, when I maximize windows, the windows overlap the taskbar. I attached the log and all of the new profiles from the new version.

Also, I don't know if this matters or not, but I've had a HTC Vive plugged in the whole time while doing these tests.

[NVIDIAInfo-v1.7.8-error-after-reload.zip](https://github.com/terrymacdonald/DisplayMagician/files/8832042/NVIDIAInfo-v1.7.8-error-after-reload.zip)

**Comment by terrymacdonald** [comment]
@pl4sma2389 Great! Thank you for grabbing that log. Those are the sorts of errors that uncover difficult to find bugs. So thank you for stopping to grab the error - it will really help.

I'll take a look to see what could have caused it now.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@pl4sma2389 I found another big bug that would have been causing intermittent problems for people thanks to your awesome log file! 

The issue was that when applying the Windows GDI settings, I was applying them to each display in turn. This apparently is not the best way to do that on multiscreen devices (which is pretty much every DisplayMagician computer). I found out that you're supposed to apply the settings, but tell ChangeDisplaySettingsEx to wait, and then once you've applied settings to all display, then tell ChangeDisplaySettingsEx to actually make the change to all screens at once (see https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changedisplaysettingsexa). This is excellent as it actually removes a couple of screen flickers as well!

I've made the code changes to NVIDIAInfo-v1.7.9. Please download it from here: https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.7.9

**Please then test swapping backwards and forwards between triple config and the cloned config.** Please do this multiple times, and try to do it quickly as well so we can see if there are any race conditions. I want to make sure the code won't break.

And then as before, if there are any issues found please upload any logs to here again. And if it works, please tell me as I need some good news :).

Thanks
Terry

**Comment by pl4sma2389** [comment]
> **Please then test swapping backwards and forwards between triple config and the cloned config.** Please do this multiple times, and try to do it quickly as well so we can see if there are any race conditions. I want to make sure the code won't break.

All works fine now, no errors, using v1.7.9. Windows maximize correctly, and there are no errors in PowerShell. I'll test the new version of DisplayMagician shortly...

**Comment by pl4sma2389** [comment]
> * You are informed during first run of DisplayMagician that you will need to create new Display Profiles

Yep.

> * Your Game Shortcuts are still there, and that you can update them with the new Display Profiles you create.

I did not create any Game Shortcuts, so I can't test this. I did create and test a shortcut, and it seems to work perfectly.

> * That you can swap between all the Display Profiles you create without any errors.

Yep. Works fine.

However, there's one more thing to test-- the original issue. Restarting now...

**Comment by pl4sma2389** [comment]
@terrymacdonald After a restart, things appear to work exactly as they should. The original issue is fixed; DisplayMagician starts up correctly and is ready to use after login.

One more question: When switching from a "center triple" config to a "left triple" config (no surround), the primary display switches, but after it's finished switching, all the displays blank for 3 seconds. Is this intended behavior? This does not happen when simply switching primary displays in the Windows Settings. I can take a video if one is needed. Or should I open another issue?

**Comment by terrymacdonald** [comment]
Great news! Thanks for reporting back.

Yeah the display blanking thing is a windows thing. Changing the primary
display doesn't force a mode change, but moving windows around does force a
mode change. No idea why it's treated differently but Microsoft but it is...

DisplayMagician also does do multiple levels of changes if you have an
NVIDIA video card. It first resets any NVIDIA customisation, then applied
NVIDIA surround, then applies windows CCD display config, then applies
windows GDI display settings, then applies any NVIDIA customisations again
as needed. This process is needed so that all the various display layouts
and configs work. It's been about 2 years of trial and error to get to that
stage 😬.

So happy to hear it all works now for you. I'll get a few more people to
test and then hopefully that version is the one we release n.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi,

Did you have a previous version of DisplayMagician installed? If so, what
version was it?

There is a known issue that I just fixed in the code that may affect some
users with a prior install.

One way around it is to go back to v2.1.5 until I can release a fix in 2
weeks.

Alternatively, you could restart v2.3.1.60 again with a new configuration.
To do that:

- Rename the existing DisplayMagician configuration folder
C:\Users\<username>\AppData\Local\DisplayMagician to another name so you
keep the files in case you need them.

- Restart DisplayMagician and create new display profiles and game shortcuts

That should at least get you working again. A more permanent fix should be
coming out within the next two weeks.

Thanks
Terry
