### ISSUE TITLE
Switching profiles turns off display

### ISSUE THREAD

**Issue by TOCA2FREAK** [terrymacdonald/DisplayMagician#116]
**Describe the bug**
When changing profiles from nvidia surround on to nvidia surround off and vise versa my 4th monitor shows as disconnected under windows "Display Settings".  My triple monitors are all connected using display ports to my nvidia gfx card.  The 4th monitor is connected to the onboard (motherboard) HDMI port.

**Expected behaviour**
I expect when changing profiles that all monitors will stay on.

[DisplayMagician-Support-20220603-1556.zip](https://github.com/terrymacdonald/DisplayMagician/files/8833203/DisplayMagician-Support-20220603-1556.zip)

**Comment by terrymacdonald** [comment]
@TOCA2FREAK I think from the logs that the issue you are getting has been fixed in the codebase. This will be fixed when I release DisplayMagician v2.4.0 in the next week or so. 

The actual bits of the logs that show it are here:
````
2022-06-03 15:49:06.2966|WARN|DisplayMagician.Program|WinLibrary/SetActiveConfig: The combination of parameters and flags specified is invalid. Display configuration not applied. So trying again without SDC_FORCE_MODE_ENUMERATION as that works on some computers.
2022-06-03 15:49:06.2966|WARN|DisplayMagician.Program|WinLibrary/SetActiveConfig: Retry. The combination of parameters and flags specified is invalid. Display configuration not applied. So trying again without any specific data other than the topology as that works on some computers.
2022-06-03 15:49:06.2966|ERROR|DisplayMagician.Program|WinLibrary/SetActiveConfig: Retry 2. The combination of parameters and flags specified is invalid. Display configuration not applied.
2022-06-03 15:49:06.2966|TRACE|DisplayMagician.Program|ProfileItem/SetActive: The Windows CCD display settings within profile NVIDIA Surround Off were NOT applied correctly.
````

I believe it's getting those errors because the code that patched adapter IDs had missed patching a couple of adapters ids in the windows config. This meant that the display config was invalid, and that caused this issue. 

````
2022-06-03 15:49:06.2966|ERROR|DisplayMagician.Program|WinLibrary/PatchAdapterIDs: Exception while going through the display config modes to update the adapter id
````

This was an error found last week, and the codebase was fixed.

But it would be great if you could do a bit of extra testing for me. This will confirm that the changes I've made to NVIDIALibrary and WinLibrary both work.

I'll need you to test NVIDIAInfo, a little app that I wrote specifically to test the NVIDIALibrary and WinLibrary that I wrote. Because I want to only test the video manipulation works with multiple video cards, we don't want to test DisplayMagician. We want to test with NVIDIAInfo so that we only test NVIDIALibrary and WinLibrary.

Once we can confirm that NVIDIALibrary and WinLibrary work then we know they will work in DisplayMagician.

Can you please download and extract the latest NVIDIAInfo zip file to a folder on your computer from here: https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.7.9
 
Open a PowerShell window, and change to the same folder that you extracted NVIDIAInfo into.

**IMPORTANT - These instructions are likely to fail, so I need you to save/rename the NVIDIAInfo.log file as shown below. Each run of NVIDIAInfo overwrites the previous NVIDIAInfo.log, so I need you to rename it each time so it doesn't get overwritten. I need to see the log file entries to know what is broken.**

Please complete the following instructions in this specific order:

Create a surround display layout with some of your screens then:
- Save the first config as `NVIDIAInfo save surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-save.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)

Next create a second windows display layout, this time with individual triple screen:
- Save the second windows display as `NVIDIAInfo save triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-save.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Check if the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we want it to NOT be equal)

Next create a third windows display layout, this time with a cloned display in it:
- Save the second windows display as `NVIDIAInfo save cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-save.log"`
- Check if the third windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to NOT be equal)
- Check if the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we want it to NOT be equal)

Next swap back to the surround display layout:
- Load the first windows display as `NVIDIAInfo load surround.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-surround-reload.log"`
- Check if the first windows display config is equal with `NVIDIAInfo equal surround.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save surround-reload.cfg`
- Make sure the second windows display config is NOT equal with `NVIDIAInfo equal triple.cfg` (we DO NOT want it to be equal)

Next swap back to the triple screen display layout again:
- Load the second windows display as `NVIDIAInfo load triple.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-triple-reload.log"`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save triple-reload.cfg`
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Next swap back to the cloned screen display layout again:
- Load the third windows display as `NVIDIAInfo load cloned.cfg`
- Rename the NVIDIAInfo.log file to `Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-reload.log"`
- Check if the third windows display config is equal with `NVIDIAInfo equal cloned.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `NVIDIAInfo save cloned-reload.cfg`
- Check if the second windows display config is equal with `NVIDIAInfo equal triple.cfg` (we want it to be equal)
- Make sure the first windows display config is NOT equal with `NVIDIAInfo equal surround.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- surround.cfg
- surround-reload.cfg
- NVIDIAInfo-surround-save.log
- NVIDIAInfo-surround-reload.log
- triple.cfg
- triple-reload.cfg
- NVIDIAInfo-triple-save.log
- NVIDIAInfo-triple-reload.log
- cloned.cfg
- cloned-reload.cfg
- NVIDIAInfo-cloned-save.log
- NVIDIAInfo-cloned-reload.log

This will give me all the information I need to know whether it worked! This will help me confirm that NVIDIALibrary and WinLibrary are ready to be integrated back into DisplayMagician. 

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
I'm so sorry but this is a little over my head.  I am unsure how to do these tests.

**Comment by terrymacdonald** [comment]
@TOCA2FREAK have you used Powershell before, or windows command line? Powershell is what's known as a terminal, which is kinda like an old text based computer screen. It's used for doing some complicated things that can't easily be done through the Windows GUI.

Download NVIDIAInfo v1.7.9 from the link I provided. Save it in your Downloads folder

Open Windows Explorer.  Navigate to your Downloads folder. Right click on the NVIDIAInfo-v1.7.9.zip file you downloaded, and select 'Extract All', and click OK when the box popups asking you where to save it.

Now open Powershell:  click on the Windows Start button and type the word 'powershell". The start menu should show the 'Windows Powershell' app. Click on that.

Type the following into the Powershell window when it opens -  `cd "$HOME\Downloads\NVIDIAInfo-v1.7.9"` and then press the enter key.

The above command should move you into the same NVIDIAInfo folder you just extracted NVIDIAInfo into. Test that by typing in `NVIDIAInfo.exe` and then press the enter key. You should see a help message. This is how we know where are in the right folder.

Now - copy and paste each of the commands that I gave you in that last set of instructions IN ORDER. It's really important to do it in order so that the log files contain the information I need in them. 

Once you've completed all the set of commands, then ZIP up the cfg and log files that I mentioned in the previous set of instructions into a new zip file.

Upload that new zip file through your web browser to this github issue, and then I'll be able to take a look at what's causing your issue.

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
![Screenshot 2022-06-06 194026](https://user-images.githubusercontent.com/19865649/172225480-2a1ab2b5-bf16-437d-9481-8fadde2ff02c.png)

I get the following message in the screenshot attached when typing NVIDIAInfo.exe

Is this correct?

**Comment by terrymacdonald** [comment]
@TOCA2FREAK oh sorry, I just realised you'll need to put a `.\` in front of
each command. So type `.\NVIDIAInfo.exe` and then press enter.

That hopefully should work. Also well done on getting this far. I know how
complicated PowerShell looks when you first start out. Hopefully this
testing will help make it seem less daunting.

The information you will gather is really useful for me understanding where
things are broken.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@TOCA2FREAK there is a little 'shortcut' when typing in the name of a executable when you're in the same folder as the executable. You can type a bit of the name, then press the 'tab' key. It's kind of like an autocomplete. So if you want to use NVIDIAInfo.exe, then you can type 'NVI' and then press the Tab key. PowerShell will then expand out that name to the first one one that is closest e.g. '.\NVIDIAInfo.exe'. 

Interestingly, if you press Tab a second time, then it will choose the next matching item in the folder, which in our case would be '.\NVIDIAInfo.exe.config'. You can keep pressing Tab to cycle through all the matching items in the folder, or you can press the Esc key to cancel using the Tab functionality.

I use those features all the time.

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
I've just followed the instructions listed below...

Next swap back to the cloned screen display layout again:

- Load the third windows display as NVIDIAInfo load cloned.cfg
- Rename the NVIDIAInfo.log file to Rename-Item -Path "NVIDIAInfo.log" -NewName "NVIDIAInfo-cloned-reload.log"
- Check if the third windows display config is equal with NVIDIAInfo equal cloned.cfg (we want it to be equal)
- Save a copy of the current display config for me to compare: NVIDIAInfo save cloned-reload.cfg
- Check if the second windows display config is equal with NVIDIAInfo equal triple.cfg (we want it to be equal)
- Make sure the first windows display config is NOT equal with NVIDIAInfo equal surround.cfg (we DO NOT want it to be equal)

However when getting to step "Check if the second windows display config is equal with NVIDIAInfo equal triple.cfg (we want it to be equal)" I'm getting the message "The NVIDIA display settings in surround.cfg and the currently active display configuration are NOT equal."

Is this correct?  Shall I carry on and send the files you want?

**Comment by terrymacdonald** [comment]
That one is a mistake, we want it to be not equal. My instructions are
wrong.

Please continue with the rest of the tests, and then send all the files
together in a zip file. I'll then go through them forensic style looking
for things that went wrong.

Send through any other errors you get shown so that I know at what stage in
the testing process I need to look.

Thanks for your help!
Terry

**Comment by TOCA2FREAK** [comment]
Okay here is the zip file of my tests.

[TOCA2FREAK-Tests.zip](https://github.com/terrymacdonald/DisplayMagician/files/8856521/TOCA2FREAK-Tests.zip)

**Comment by terrymacdonald** [comment]
Awesome. Nice work. I'll get onto reviewing them over the next few days and see what I find.

As a next step, please test this version of DisplayMagician v2.4.0.10:
[DisplayMagicianSetup-v2.4.0.10.zip](https://github.com/terrymacdonald/DisplayMagician/files/8835910/DisplayMagicianSetup-v2.4.0.10.zip)

It is a test version of DisplayMagician that **hopefully**  is nearly ready to ship, and *may* fix your issue. It contains a lot of fixes since v2.3.1.60, and one of them may fix the issue you're getting. It also adds some more features such as Windows DPI Scaling and recording of NVIDIA 3D Settings.

PLEASE NOTE: It will rename your old DisplayMagician settings files which will stop older versions of DisplayMagician from working. This is reversible. 

PLEASE ALSO NOTE: You will be required to setup new Display Profiles. This is because we're added new settings (NVIDIA 3D Settings, and Windows DPI Scaling).

Please check the following when you test this version of DisplayMagician that:
- You are informed during first run of DisplayMagician that you will need to create new Display Profiles
- Your Game Shortcuts are still there, and that you can update them with the new Display Profiles you create.
- That you can swap between all the Display Profiles you create without any errors.

Please reply with the results of your testing.

Thanks
Terry

**Comment by TOCA2FREAK** [comment]
Hi,

Using v2.4.0.10 has fixed the issue where the 4th monitor used to turn off, so this is great news!

However when switching back to the profile where nvidia surround is off the centre display isn't set to the main display.  However windows display settings show it as the main strangely enough??

![Screenshot 2022-06-08 183917](https://user-images.githubusercontent.com/19865649/172682293-db18272c-e5c9-42ea-a3f1-699bc4f7f40b.png)

![Screenshot 2022-06-08 184210](https://user-images.githubusercontent.com/19865649/172682526-e4dd325b-06f4-4c8e-b9ee-495ec23b66b2.png)

I think this is a windows issue though and not sure if there is anything you can do to solve this with your software?  I fix this myself by setting "Display 1" to be the main display and then settings "Display 2" to be the main monitor again.  I did make sure "Display 2" was the main display when I created this profile in DisplayMagician.

Thanks,
Kevin

**Comment by TOCA2FREAK** [comment]
Forgot to say.  This also happened in the version I was using before v2.4.0.10

**Comment by terrymacdonald** [comment]
@TOCA2FREAK I'm going to branch that off as a new issue, as the codebase  updates fixed your original problem.
