### ISSUE TITLE
Display profile changes when alt-tab in fullscreen game.

### ISSUE THREAD

**Issue by Vixo4K** [terrymacdonald/DisplayMagician#125]
Whenever i'm playing on fullscreen, and minimize the game, the display profile switches to a different one.

Expected behaviour:
I would like to stay on the desired profile until i manually change it back without being switched to my TV in the middle of the game.

Specs:
 - Windows Version: Windows 10 21H2 19044.1766
 - DisplayMagician Version 2.3.1.60
 - Video Card: EVGA NVIDIA 1060 6gb
 - Number and make/model of monitors: Main: LG 24MK400H, Secondary; LG M1950A.
 - Date of last video driver update: A while ago. Will try updating them.
 - Date of last windows update: I'm up to date according to Windows Update.
[DisplayMagician-Support-20220622-0005.zip](https://github.com/terrymacdonald/DisplayMagician/files/8954293/DisplayMagician-Support-20220622-0005.zip)

**Comment by terrymacdonald** [comment]
@Vixo4K If you are running a Game Shortcut that changes the display layout, then DisplayMagician waits until it detects the game process has closed. It doesn't have anything to do with monitoring Display Profiles or whether the game is fullscreen or not. It's all about whether the game process is still there.

Some games use a game launcher which launches, starts the main game process, and then closes itself. An example of a game that does that is Assetto Corso Competitzione. If your game is doing this, then you need to follow the instructions here: [https://github.com/terrymacdonald/DisplayMagician/wiki/Troubleshooting-DisplayMagician#arrgh-displaymagician-doesnt-wait-for-my-game-to-load](https://github.com/terrymacdonald/DisplayMagician/wiki/Troubleshooting-DisplayMagician#arrgh-displaymagician-doesnt-wait-for-my-game-to-load)

I'll have a look through the logs you've dropped for me in case there is another weird error occurring, but at least give that wiki page a read and see if that's the underlying cause.

Thanks
Terry

**Comment by Vixo4K** [comment]
I forgot to mention that i have actually three displays, the third one being my TV. So i have two profiles: one for the two monitors on my desk and another one only for my TV (SONY KDL - 32EX405)

**Comment by terrymacdonald** [comment]
@Vixo4K Do you have any other software that changes the display layout, or that alters the Windows Taskbar at all?

I've updated the WinLibrary to workaround the issues I found in your log files. We now only accept the sources that use the `\\.\DIISPLAYXX` format, so that we make sure they are real valid sources. This should hopefully make things work for you.

In order to test this, I'll need you to perform some tests for me using CCDInfo. In order to make it easier to test display layout issues, I created CCDInfo that is designed to only test the WinLibrary video library. But performing these tests we can confirm that WinLibrary is working properly, and that in turn will mean it is more likely that DisplayMagician will work.

OK, so can you please perform these steps to test (NOTE: Please perform these steps in the EXACT order shown below):


Download the latest test version of CCDInfo from [CCDInfo-v1.8.2.zip](https://github.com/terrymacdonald/DisplayMagician/files/8961049/CCDInfo-v1.8.2.zip) to your Downloads folder.

Open a PowerShell window, and change to the same folder that you extracted CCDInfo into.

**Create a ESC layout with some of your screens then:**
- Save the first config as `CCDInfo save first.cfg`
- Rename the CCDInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-first-save.log"`
- Check if the first windows display config is equal with `CCDInfo equal first.cfg` (we want it to be equal)

**Next, create a SOLO TV windows display layout:**
- Save the second windows display as `CCDInfo save second.cfg`
- Rename the CCDInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-second-save.log"`
- Check if the second windows display config is equal with `CCDInfo equal second.cfg` (we want it to be equal)
- Check if the first windows display config is NOT equal with `CCDInfo equal first.cfg` (we want it to NOT be equal)

**Next swap back to the first display layout:**
- Load the first windows display as `CCDInfo load first.cfg`
- Rename the CCDInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-first-reload.log"`
- Check if the first windows display config is equal with `CCDInfo equal first.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `CCDInfo save first-reload.cfg`
- Make sure the second windows display config is NOT equal with `CCDInfo equal second.cfg` (we DO NOT want it to be equal)

**Next swap back to the disabled super display display layout again:**
- Load the second windows display as `CCDInfo load second.cfg`
- Rename the CCDInfo.log file to `Rename-Item -Path "CCDInfo.log" -NewName "CCDInfo-second-reload.log"`
- Check if the second windows display config is equal with `CCDInfo equal second.cfg` (we want it to be equal)
- Save a copy of the current display config for me to compare: `CCDInfo save second-reload.cfg`
- Make sure the first windows display config is NOT equal with `CCDInfo equal first.cfg` (we DO NOT want it to be equal)

Once that series of tests are done, please include the following files in a ZIP file, and upload the ZIP to this github issue through your web browser (click and drag the file from your File explorer into Github and it will upload):
- first.cfg
- first-reload.cfg
- CCDInfo-first-save.log
- CCDInfo-first-reload.log
- second.cfg
- second-reload.cfg
- CCDInfo-second-save.log
- CCDInfo-second-reload.log

Hopefully this set of files will show that we have successfully fixed the issue you were having.

Thanks
Terry

**Comment by Vixo4K** [comment]
I use TaskbarX to make the taskbar transparent if that's what you mean

**Comment by terrymacdonald** [comment]
@Vixo4K That TaskbarX may be the cause of this, but I'll have to see the results of your testing really. 

Please upload the ZIP file you create after going through those instructions I provided in the exact order they are listed. Then I should have much more information about what has been happening.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Vixo4K I've just confirmed a bug with the Windows DPI scaling that may be the cause of your issue. From my testing it seems some hardware (most likely laptops) return data outside the expected range. I've now made DisplayMagician tell windows what DPI awareness it has, so that we get the guaranteed right DPI settings, and I've made WinLibrary handle expected values (as in my testing these values still result in the correct Windows DPI Scale being applied). 

I've also adjusted the process for adding a '.old' to the end of the older json config files so that it does it to all of them reliably. This should help avoid DisplayMagician wanting to patch the wrong things.

I've also added a Windows display path processing improvement that should help on devices with a lot of display paths that have accumulated over time. Display Paths are the bits in windows that link a display source (a particular desktop) with a display target (a particular monitor). Windows keeps track of every monitor it's ever seen, and that eventually leaves a lot of stale entries in the list. We now try to skip over the ones that can't be used. 

I've wrapped this all up into a new test version of DisplayMagician v2.4..0.64 that *should* fix the issue you're experiencing. To test this, please perform the following:

- Download DisplayMagician-v2.4..0.64.zip from here: [DisplayMagicianSetup-v2.4.0.64.zip](https://github.com/terrymacdonald/DisplayMagician/files/8996434/DisplayMagicianSetup-v2.4.0.64.zip)
- Unzip the zip file
- Run the DisplayMagician-v2.4..0.64.msi
- See if it loads properly!
- Go to the Display Profiles window
- Delete any old Display Profiles listed in there
- Use Windows Setup or NVIDIA Control Panel or AMD Adrenalin to set up a display layout you want
- Swap back to DisplayMagician and save the display layout as a Display Profile.
- Swap back to Windows Setup or NVIDIA Control Panel or AMD Adrenalin to set up another display layout you want
- Swap back to DisplayMagician and save the display layout as a Display Profile.

Once you have finished setting up your Display Profiles, please try to swap between them *using the Apply button the Display Profiles window*. This is critical as I want to test that everything works using the simplest way to do so.

Please then create a Support ZIP File by going click the Settings button on the Main page, and then clicking on the Create Support ZIP File button. Please upload the ZIP file using you make to this issue using your Web Browser, so that I can see if this fixed the problem for you.

Hope it works!

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi @Vixo4K,

I can't wait any longer, so I'm releasing DisplayMagician v2.4.0 today which *should* fix you issue. I'm going to close your issue for now so I know what other issues I need to work on, but if you do some testing and this same issue is still causing you a problem, then please reopen this issue and we'll continue to test. If you get a different problem with DisplayMagician v2.4.0  please create a new issue so I can track them separately.

Thanks
Terry
