### ISSUE TITLE
Game Shortcut Audio Settings

### ISSUE THREAD

**Issue by sven25** [terrymacdonald/DisplayMagician#127]
Hi Terry,
sorry for answering that late.
First of all thank you very much for the effort in developing this nice tool.
With version 2.3.1.60 the Game Shortcuts are generally working now, which is great!

So now there is a little thing with the audio setting:

- Game Shortcut 1 sets the default microphone to lets say "mic 1"
- Game Shortcut 2 sets the default microphone to "mic 2"

Now i selected "default" in the Discord audio input setting, because i thought then i can switch between "mic 1" and 
"mic 2" without changing it manually in Discord.

But its only working when i set the specific mic also as "standard communication device" in the Windows Audio Settings.
So it seems like "default" isnt enough for Discord?!

Is it possible to add this "set as standard communcation device" also to the Game Shortcut Audio Settings?

Best regards

Sven

_Originally posted by @sven25 in https://github.com/terrymacdonald/DisplayMagician/issues/87#issuecomment-1169892856_

**Comment by terrymacdonald** [comment]
@sven25 sounds like a good idea! I could make it a simple 'Also change communication device' checkbox or something, and then revert it back after running the game shortcut. Windows sound device control is a pain. But I'll have a look at it once I've released the next DisplayMagician version 2.4.0.

**Comment by sven25** [comment]
Sound good. I´m looking forward to it! :)

**Comment by terrymacdonald** [comment]
@sven25 The codebase I'm working on now has this functionality. How it works is that you can check the 'Use as a communications device' checkbox next to the audio device or the microphone device, and it will change the device and also set it to the communications device too. It will also remember the devices and settings that were there before we changed it, and it will change them all back.

It looks like this:

![image](https://user-images.githubusercontent.com/5721772/177892793-410803fe-23d1-4ea4-b201-b3174c77c38c.png)

Hopefully that's what you're after. I'll drop a test version when I'm closer to a release, and then if you could please test it and make sure it works with discord the way you were wanting then that would be ace. 

I'm going to close this issue now so that I can keep track of the issues I've fixed, as I'm hoping to release the new version 2.5.0 in the next couple of weeks.

Thanks
Terry
