### ISSUE TITLE
Warn users about profile deletion before update

### ISSUE THREAD

**Issue by theblackhole** [terrymacdonald/DisplayMagician#130]
**Is your feature request related to a problem? Please describe.**
I love DisplayMagician but it's quite frustrating to loose my profiles, almost every update, without any warning.
As a developer myself, I understand that retrocompatibility can be time consuming and sometimes not possible to implement.
But the frustrating part is the element of surprise.

**Describe the solution you'd like**
Warn users in the app about breaking changes if cleaning profiles is necessary for the update.

**Describe alternatives you've considered**
- I suggest to be closer to [semver specs](https://semver.org/), with no hesitation to update the major version if it breaks things
- Warn users in the app so users can choose to update now or later, maybe by displaying the changelog and/or a warning about profiles deletion

Thanks again for your awesome app :)

**Comment by terrymacdonald** [comment]
Hi @theblackhole,

Yeah I get it. I am sorry for the number of breaking changes I've had to implement. There has been a lot of bugs I've had to fix which have necessitated display profile format updates, and I've taken the opportunity to roll in some more profile modifications at the same time to try and make things better. I know this has been frustrating for people, but in 99% of the cases it's been needed to get rid of fairly major bugs :(. Turns out it's pretty complicated to implement software that works with all video cards across all display layouts that windows can support...

With all that said, I'll try to do better.

DisplayMagician already does warn users when the new version starts, but it doesn't warn before the update. Here is a screenshot of the upgrade notification window I get when I run DisplayMagician 2.4.1.1 on first start:

![image](https://user-images.githubusercontent.com/5721772/177636369-6e99a260-5c5b-478c-bc4a-3f739afe2a0d.png)

But that, of course, doesn't warn users before they upgrade. I do think a warning is a good idea. I'll have a think about how I can do that with the libraries I am using.  It might be a while before I can get that sorted out.

I don't follow semver completely at this point because I don't believe that DisplayMagician is fully formed yet. I'm effectively still building out the custom NVIIALibrary, AMDLibrary and WnLibrary video card manipulation libraries that I wrote from scratch and still finding errors in them. If I changed the major version each time I needed you all to recreate Display Profiles, then we'd be on version 10.x by now. Instead, I am keeping the 2.x series as the version using this interface, and then I plan to move to the 3.x numbering when I move to .net6/MAUI.

Hope that clarifies.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@theblackhole This is what I've come up with:

![image](https://user-images.githubusercontent.com/5721772/177666375-21c03697-b590-4b98-bd17-c6071a054ca4.png)

This replaces the previous MessageBox way of doing things. The text in the middle is updated based on the additional settings I apply on the server side for that particular update requirements. Additionally I've added the ability to say remind me later', which will remind the user in 7 days time (a week).

**IMPORTANT!:** This will not work for the next upgrade, as the current version of DisplayMagician you have does not contain the new upgrade code. The upgrade AFTER the next upgrade will work as shown.

I think this is good enough for now. This will be included in DisplayMagician v2.5.0 when it is released. 

As this enhancement has been added to DisplayMagician now, I will close this issue so I know what other issues I have to work on. If DisplayMagician v2.5.0 is released and this feature does not work properly please reopen this issue and we'll continue debugging.

Thanks
Terry

**Comment by theblackhole** [comment]
Hi @terrymacdonald,

Wow that was quick !

> Yeah I get it. I am sorry for the number of breaking changes I've had to implement
Oh, don't be sorry about that, that's normal! It's a complicated project, and by looking at the past contributions, it looks like you're on your own. For an advanced app made by a single developer, it is truely magic! 😄 

> Hope that clarifies.
It does, totally :)

> I think this is good enough for now. This will be included in DisplayMagician v2.5.0 when it is released.
This is more than good enough: giving users the choice to upgrade later after being warned and the bonus ability to be reminded later is perfect! 🙂

Thanks again for your time and your app 👍

**Comment by terrymacdonald** [comment]
Thanks for the kind words. I do try to give people a solid working product.
It's been pretty challenging with all the different types of hardware out
there, not to mention the fact not all display connection types support all
the functionality.  It's taken a LOT of my time creating DisplayMagician,
but I do enjoy making the impossible happen.

Thanks for your great feedback. It's really humbling hearing about how
DisplayMagician is making people's lives easier.

Thanks
Terry
