### ISSUE TITLE
Nvidia Surround not working and crashing the App

### ISSUE THREAD

**Issue by Flymo74** [terrymacdonald/DisplayMagician#131]
**Describe the bug**
After updating I can create and save Nvidia surround profile as I had before but the app crashes and does not switch from single display to triple surround anymore.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create surround profile for triple display
2. Save profile
3. Switch back to single display
4. Click triple display profile and app crashes.

**Expected behaviour**
To be as it was before. It allowed me to change profiles easily between single and triple surround. After update it crashes and does not switch.

**Screenshots**

**Reporting Logs**

[DisplayMagician-Support-20220706-1849.zip](https://github.com/terrymacdonald/DisplayMagician/files/9057053/DisplayMagician-Support-20220706-1849.zip)

**Enviroment (please complete the following information):**
 - Windows Version: 10
 - DisplayMagician Version : 2.4.1.1
 - Video Card: [e.g. Asus NVIDIA GTX3060ti
 - Number and make/model of monitors: [e.g. 2xDell P2417H, 1x Viewsonic VX2476
 - Date of last video driver update: 2022-06-28
 - Date of last windows update: No idea. Very recent

**Additional context**

**Comment by terrymacdonald** [comment]
@Flymo74 I can see that you are attempting to load a Display Profile from a Desktop Shortcut. Your old Desktop Shortcut is pointing to your old Display Profile that no longer exists. During the upgrade to v2.4.1.1 you had to create a new Display Profile. This has a completely different UUID as it is a new Display Profile, meaning that the old Desktop Shortcut won't work with the new Display Profile. 

Each DisplayProfile has a UUID generated when it is created. This UUID is unique, and never changes for that Display Profile. Desktop Shortcuts use the UUID to apply the correct Display Profile (they don't use the Display Profile name). This is done so that people can change the name of their Display Profiles, and all their Desktop Shortcuts will keep working (though please note the Desktop Shortcut will keep the name that it was saved as!)

To generate a new working Desktop Shortcut, you will need to open up DisplayMagician, open the Display Profiles page, select the Display Profile you want to use, and then click on the **Save Desktop Shortcut** button. You can then save a Desktop Shortcut where ever you would like it to go. If you then double-click on that newly saved Desktop Shortcut it will work again, as there is a Display Profile with a matching UUID.

Please reply back with whether that process above worked for you, and if it did please close this issue.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Flymo74 One more question... do you still get a crash if you apply a different display profile from the Display Profile window, do you still get a crash? If you do get a crash, is it swapping from an NVIDIA surround profile to a 3x individual display profile?

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Flymo74 I *think* I may have found a problem that could have affected your 

There was an error that occurred in NvAPI_SetDisplayConfig when attempting to go from an NVIDIA Surround to a non-NVIDIA Surround setup on a machine that has multiple video cards installed in it. This is due to the fact that the NVIDIA driver only sees the displays connected to NVIDIA video adapters. 

The previous DM logic tried to set the DisplayConfig after switching to or from a Surround display profile, but this would fail when returning from a a Surround display profile on Win 10 devices. It appears that the NVIDIA driver AUTOMATICALLY disables all additional displays in windows when it returns from a Surround profile. This simple fact means that the DisplayConfig won't be applied properly, and it errors with an NVAPI_INVALID_ARGUMENT error. This doesn't actually matter though, as the WinLibrary comes to the rescue.

WinLibrary can see all the video adapters available, and so will turn the required displays back on and set them up just right! We *may* lose are some specific DisplayConfig parameters being set as part of this process, but I'm not totally sure about that as WinLibrary is basically feature parity with the DisplayConfig settings as far as I can tell.

The fix is to look specifically for the NVAPI_INVALID_ARGUMENT error when attempting to set the NvAPI_DisplayConfig, and if this happens we check if we were going from a surround profile to a non-surround profile. If that is true, then we simply ignore that error. WinLibrary then clears up that problem and everything proceeds as normal.

This should (fingers crossed) fix this issue once and for all!

This change also makes it far faster to grab and set the taskbar settings from registry, though this logic may not detect some Windows 10 formats which appear to be LOCALDISPLAY(\d,\d,\d\d) settings which I've never seen before. It should be generally much faster and more reliable.

Anyway - please download this test version 2.4.1.14 from here and install it, and please tell me if it now works: [DisplayMagicianSetup-v2.4.1.14.zip](https://github.com/terrymacdonald/DisplayMagician/files/9111122/DisplayMagicianSetup-v2.4.1.14.zip)

I will close this issue assuming that it is fixed based on the testing others have performed. Feel free to reopen once it is closed if you are still having the exact same issue. If it is a different issue you get after installing 2.4.1.14 then please log a new issue and we'll troubleshoot under that issue instead.

Thanks
Terry
