### ISSUE TITLE
Ways to make this work with Steam Remote Play?

### ISSUE THREAD

**Issue by geolessel** [terrymacdonald/DisplayMagician#140]
I've tried to figure out how to get this to work while using Steam Remote play. I have a triple monitor set up for sims but I have a Steam title I would like to stream to my living room via one monitor. Is there a "best" way to do this? I tried adding a desktop shortcut to my Steam library but that didn't work. I also tried adding DisplayMagician itself to my library but that didn't work either. Any suggestions?

**Comment by terrymacdonald** [comment]
Hi Geoffrey,

DisplayMagician can only control the screens that are connected to the
Windows 10/11 computer that it is running on. You'll need to describe to me
exactly how your computer is connected to your displays before I can help
you. I need to know:

   - What OS your computer is running
   - What makes and models of displays you have
   - How each display is connected to the PC (e.g. DisplayPort), HDMI,
   DPI-D) and if there are any conversion dongles in the connection
   - Any pointers to documentation about how Steam Remote play works.
   - Are you running DisplayMagician on the host computer that has the game
   installed on it? Or on the client computer connected to the TV?


Thanks

*Terry*

**Comment by geolessel** [comment]
Thanks for the reply. I found out that I can force the game I'm playing into a specific resolution that doesn't span three screens and it successfully is streamed to the Steam Link device. In case this comes up again (and I _do_ think this feature would still be helpful), here are the answers to your questions.

- host is running Windows 10
- 3x GIGABYTE M32Q all connected via DisplayPort
- [here is some documentation on Remote Play](https://help.steampowered.com/en/faqs/view/0689-74b8-92ac-10f2)
- DisplayMagician is running on the host computer

The client connected to the TV is actually an Apple TV running [Steam Link](https://apps.apple.com/us/app/steam-link/id1246969117). In short, all Remote Play does is stream video captured from the host computer to the client and sends control commands from the client to the host.

**Comment by terrymacdonald** [comment]
Hi @geolessel ,

I've had a look at Steam Remote Play, and it will work with DisplayMagician already. Steam Remote Play streams the view from the host PC to the remote play client PC itself, so there is nothing that DisplayMagician is involved in doing.

If you have problems running your chosen game over Steam Remote Play, then you can use DisplayMagician to set up a display profile that matches the resolution of the TV you're using for the Steam Remote Play client. In that way, you can set up a Game Shortcut specifically for when you want to remote play your chosen game. DisplayMagician would then change to a display profile that is suited to the TV you're remote playing on, then it could run the game. You could then separately start a Steam Remote Play session and it should work fine as the resolutions would match. Once you've completed your gaming session you should be able to close the game, and DisplayMagician will detect this on the host PC, and will revert the Display Profile to the one you were using earlier.

Hope that helps. I'll close this issue as there isn't really anything else I can do.

Also - if you have any tips and example commands that you used it could be good to drop them in this issue so that other people with the same problems will be able to find the answers here.

Thanks
Terry
