### ISSUE TITLE
Close programs by switching monitor profiles?

### ISSUE THREAD

**Issue by Miiinttt** [terrymacdonald/DisplayMagician#141]
Hi Terry, hope you're doing well. Would it be possible to add a feature to shortcuts to close programs when switching display profiles? I have a game shortcut to open a couple of applications and switch my display profile to my sim racing profile. I don't have it linked to a game so I'm not using the option to monitor and close the applications or change the display profile back when I exit a game. The reason is quite often I'll exit out of a game but keep my racing profile and applications running if I need to step away from the rig briefly but plan on coming back to it. When I know I'm done racing for the day, I switch my display profile back to my daily use one and manually exit out of the applications that I launched with the shortcut. Currently it's 1 click to get on the sim rig with the game shortcut switching my display profile and launching the applications but it's 5 clicks to get back to my desk setup because I manually switch the display profile and close out the 4 applications that I launched.

I'd like to be able to have an option to switch audio inputs or close applications that are part of a game shortcut when I manually switch monitor profiles. Similar to how the existing system works with monitoring the game executable, but instead of it being linked to the game maybe it could be monitoring the active display profile. I'm not sure if this is even possible, but in theory, it would be 1 click to get on the sim rig and 1 click to get back to my desk setup.

Let me know if I can elaborate further or if this is even possible and thank you for everything you do.

**Comment by terrymacdonald** [comment]
Hi,

It's not possible to do it within display profiles, but you can use a game
shortcut to get close to what you have proposed.

You can create a game shortcut that doesn't run a game, and that is
permanent. You can set it up for how you want the display layout and start
up programs to load. You can then save that as a shortcut.

You can then create another game shortcut, also with no game monitored,
permanent, and have this one run start program commands that shutdown the
same helper organs you started in the first game shortcut. E.g using
taskkill to kill processes.

In this way you would use one game shortcut to set things up, and the other
game shortcut to tear things down.

Does that make sense?

Thanks
Terry

**Comment by Miiinttt** [comment]
It does make sense and I got it working for the most part, except for 1 of the programs not closing. I set it up so it starts Powershell and runs the stop-process commands and that's working for everything except Heuskinveld Smart Control. I've tried running the command using PID as well as process name with no luck. I've also tried doing it through CMD using taskkill but that didn't work for any of the programs so I resorted to PowerShell. Running as administrator has no effect either. Any idea how I can get it to kill Smart Control as well?

If not, I'm still happy as this is better than it was before. Thanks!

**Comment by terrymacdonald** [comment]
Hi Miiinttt,

I just tried downloading and installing 'Heusinkveld Smart Control' to see
how it was structured, and the only thing I would say that may be causing
you issues is that the process name has the version string included in it.
For example Heusinkveld Smart Control 1.4.1 has a process name of
'SmartControl V1.4.1'

What this means in practice is that you need to add a wildcard into the
process name matching in your Powershell, so that Powershell will kill all
the SmartControl processes  e.g.

Stop-Process -Name "SmartControl*"

I just tested the above Powershell command on my test PC and it killed
the Heusinkveld Smart Control process on my machine. I also managed the
same result using taskkill with the cmd command below (runs taskkill using
a filter looking for a process name of SmartControl<something>):

taskkill /FI "imagename eq SmartControl*"

Hope that helps! I'll go ahead and close this issue in Github as I think we
have a work around now.

Thanks
*Terry *

**Comment by terrymacdonald** [comment]
Closing this case as there is a workaround.

**Comment by terrymacdonald** [comment]
I've used your example in the troubleshooting guide as well just in case anyone else wants to do the same thing: https://github.com/terrymacdonald/DisplayMagician/wiki/Troubleshooting-DisplayMagician#i-want-one-shortcut-to-setup-my-system-and-another-one-to-tear-it-down

**Comment by Miiinttt** [comment]
Thanks again Terry. I hadn't realized I could still comment on a closed thread or I would have confirmed earlier that it's working 100% now with the workaround you provided.
