### ISSUE TITLE
DisplayMagician is preventing Steam from updating games.

### ISSUE THREAD

**Issue by Chrius** [terrymacdonald/DisplayMagician#151]
**Describe the bug**
If I have DisplayMagician running, it accesses steams appinfo.vdf. If I try updating any games while the file is being accessed, steam doesnt save the update data. Then, next time I restart steam it will revert to the previous update. Closing DisplayMagician releases the appinfo.vdf file, and steam updates start working as intended again.

**To Reproduce**
Steps to reproduce the behaviour:
Launch DisplayMagician
Wait for a steam update (it should update correctly)
Restart steam (it will update again, and return to the previous version)

Trying to manually delete the appinfo.vdf file will also show that it's being used by DisplayMagician.
![File in use](https://user-images.githubusercontent.com/11493529/196715469-9a3a9090-87b8-429d-83b7-15704cf79962.jpg)

**Expected behaviour**
DisplayMagician shouldn't keep the file locked.

**Reporting Logs**
[DisplayMagician-Support-20221019-1104.zip](https://github.com/terrymacdonald/DisplayMagician/files/9821163/DisplayMagician-Support-20221019-1104.zip)
Not sure if there's anything useful here since it's something that happens all the time while DM is running.

**Enviroment**
Windows 11 reinstalled and updated 2 days ago (the issue was happening before, I reinstalled windows because I thought it could be the cause of the problem).
Display Magician version 2.4.1.14

**Comment by terrymacdonald** [comment]
Oh this is an interesting find. We'll done on finding it. I'll have a test
myself in a few days when I have some free time, and then I'll issue a fix.

It shouldn't be too difficult to solve. I'm probably just going to have to
release a file handle.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Chrius Sorry for the delay. I had to take a bit of time off from doing DisplayMagician as life got a bit hectic. I'm hoping that I'll get a bit more free time now, so let's see how that goes :).

I went through the codebase, and I think I know where the error lies. There was some example code I used from an upstream source and it unfortunately contains a bug that doesn't free the steam files after it has finished with them. Strangely it looks like Steam is the only library that has this issue, so sorry about that.

I'll try to fix it during this week, but it could be a little while before I get a new hot fix out that fixes this bug. I'd really love it if you could test the fix first so that we can confirm the bug is fixed before I drop the new release publicly,

Thanks for your patience, and thanks for logging the issue!

Terry

**Comment by Chrius** [comment]
No problem, let me know when you need me to test it.

**Comment by terrymacdonald** [comment]
Hi @Chrius,

Can you please download, extract and install the test version of DisplayMagician attached to this reply? It should be v2.4.2.1. The only change is the adjustment to free the Steam files after parsing them. It should hopefully fix the issue you were experiencing. 

Can you please test this hotfix and then reply with your results?

[DisplayMagicianSetup-v2.4.2.1.zip](https://github.com/terrymacdonald/DisplayMagician/files/9945240/DisplayMagicianSetup-v2.4.2.1.zip)

Thanks

Terry

**Comment by Chrius** [comment]
I didn't have updates on any games yet, but the file is not locked anymore. Seems to be working now.
I'll leave it running and see if any updates pop up to test.

**Comment by Chrius** [comment]
Ok, got some updates today, everything seems to be working correctly now with the hotfix.

**Comment by terrymacdonald** [comment]
Excellent news. I'll close this issue now, as it will be in the next version of DisplayMagician released.
