### ISSUE TITLE
Green vs blue monitor in profiles

### ISSUE THREAD

**Issue by mutton44** [terrymacdonald/DisplayMagician#175]
Hi. 

First. Thankyou for this piece of software!

Second. Quick question. What is the difference between a blue and green monitor on the profiles page?

See attached image. "Normal" profile works. "Nvidia Surround" doesn't appear to do anything. "Surround temp" works. The only difference (as far as I can tell) is the colour. 
![image](https://user-images.githubusercontent.com/42210926/208154928-9867d8b0-b0a0-4afe-b3a6-890072f3d2db.png)
This was created with a fresh install of V2.4.1. Running WIndows 10 21H2.

Finally. On a separate note. I'm not sure if this is playing 100% nicely with FancyZones in Microsoft PowerToys (V0.65.0). It may just be FancyZones struggling with connected monitors changing. Windows are moving all over the place (which is entertaining to watch) and swapping docks. This is a minor inconvenience, not a show stopper. Just a bit of window dragging required. This is a minor trouble compared to the vanilla behaviour of disabling surround without your software! At least I can see the windows to move them and FancyZones doesn't completely forget its settings :). 
I suppose a succinct question would be... Does Display Magician try to resize and place windows back where they were?

Thanks again!

**Comment by terrymacdonald** [comment]
Hi @mutton44 ,

The different colour is because it is using the NVIDIA surround functionality. NVIDIA surround display profiles are NVIDIA green in colour for the primary display, AMD Eyefinity display profiles are AMD red for the primary display, and everything else is blue in colour for the primary display. All other monitors are grey in colour.

Regarding fancy zones, DisplayMagician does not change window positions at all. Amy window positions changes are left up to windows to decide where to put things. DisplayMagician only changes the display configuration.

Hope that clarifies!

Terry

**Comment by mutton44** [comment]
Hi Terry,

That does indeed clarify.

Many thanks for the info!
