### ISSUE TITLE
Right Click "DisplayMagician Profiles" doesn't load current profiles

### ISSUE THREAD

**Issue by Impal3rVlad** [terrymacdonald/DisplayMagician#181]
**Describe the bug**
When right-clicking on my desktop and selecting "DisplayMagician Profiles", I only see "Create a new display profile" and not any of my current profiles. I'm able to see and switch between my current profiles flawlessly when I open up the program itself.

**To Reproduce**
1. Right click desktop
2. Select "DisplayMagician Profiles"
3. See error (doesn't include any of my profiles)

**Expected behavior**
I would expect to see my display profiles.

**Screenshots**
![Screenshot 2022-12-27 183242](https://user-images.githubusercontent.com/121529713/209748185-32e46633-1fa7-49b6-8de5-8278c667d038.png)

**Environment (please complete the following information):**
 - Windows Version: Win10
 - DisplayMagician Version 2.4.1.14
 - Video Card: NVIDIA RTX 3090
 - Number and make/model of monitors: 3x LG 32GK650F-B 32"
 - Date of last video driver update: 2022-12-08
 - Date of last windows update: 2022-12-17

**Additional context**
[DisplayMagician-Support-20221227-1844.zip](https://github.com/terrymacdonald/DisplayMagician/files/10311740/DisplayMagician-Support-20221227-1844.zip)

**Comment by terrymacdonald** [comment]
Hi,

This bug is fixed in the codebase, but the next full release isn't quite
ready to go yet. I do have a test version that has the fix in it.

Please see this comment in issue #173 to get the download link:
https://github.com/terrymacdonald/DisplayMagician/issues/173#issuecomment-1352776631

Download, unzip and then install, and your problem should go away. You'll
also get a sneak peak at all the new cool features I've added over the last
few months!

Hooper that works for you.

Thanks
Terry

**Comment by terrymacdonald** [comment]
This has been fixed in the latest version of DisplayMagician released here: [DisplayMagician v2.5.0](https://github.com/terrymacdonald/DisplayMagician/releases/latest)

I will close this issue for now as the issue should have been fixed, but please feel free to reopen this if that specific issue is not fixed. If you find a different issue please create a new separate issue so that I can work on them separately.

Thanks
Terry
