### ISSUE TITLE
"display manager" game shortcuts unhandled exception

### ISSUE THREAD

**Issue by ssna** [terrymacdonald/DisplayMagician#185]
**Describe the bug**
"display manager" game shortcuts unhandled exception

**To Reproduce**
The Profile Manager works and changes between profiles.  But the "Game Shortcut" has "Unhandlesd exception error", quit closes DM, continue goes to Game Shortcut Library.  Selecting New Game starts scanning for games, can edit and fill in details but Libray does not have game.

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/15314850/213037993-a13121dc-8f28-443b-90f3-5a2b9fb58168.png)

**Reporting Logs**
[DisplayMagician-Support-20230118-1056.zip](https://github.com/terrymacdonald/DisplayMagician/files/10440562/DisplayMagician-Support-20230118-1056.zip)

**Enviroment (please complete the following information):**
 - Windows Version: [e.g. Win10]
 - DisplayMagician Version [e.g. 2.5.0.0.352]
 - Video Card: [e.g. Asus NVIDIA RTX3080]
 - Number and make/model of monitors: [e.g. 2xADC, 1x Leovo]
 
**Additional context**
Was using prior Helios, which still works.  Is it possible this may be interfering.
System is installed on C:SSD
Some games and steam installed on D:

**Comment by terrymacdonald** [comment]
@ssna Hmmm. Looks like DisplayMagician is trying to get some info from the NVIDIA driver that your system doesn't return. This is different to what is returned on my test system, so there will be a bit of analysis while I try to figure out where that is.

Can you please tell me what your layout is for the 3 screens you have? Are they all landscape, or are some portrait? 

Also, are all 3 screens plugged directly into the RTX3080 or are there any dongles also connected into them?

For reference, Helios Display Management won't affect DisplayMagician at all. I've replaced pretty much all the code from Helios except the EDID detection stuff. You can run either app fine (just don't try to apply the display profiles at the same time :))

Thanks
Terry

**Comment by terrymacdonald** [comment]
@ssna Hi! I notice that the DisplayMagician logging level was set to 'Info'. Can you please set it to 'Trace' in the Settings window, and then try causing the error to occur again? Trace level logging has more detail in it, and it may provide a bit more light on what is going wrong.

Once you've made the error occur then please create a new Support ZIP File, and then set your logging level back to 'Info' to keep the log file a nice small size again for the future.

Thanks
Terry

**Comment by ssna** [comment]
3 landscape screens all hooked directly to RTX3080 display ports.  

Generally run 2 profiles
1) Default for work and single screen games, 3 x single side by side
2) Surround 3 screens as 0ne 5760x1080 for some driving games.
Sometimes give a screen to my laptop but haven't set that profile up yet.

![image](https://user-images.githubusercontent.com/15314850/213091842-71203e74-f64d-4f96-9bd5-e935b7a9b6ce.png)
[DisplayMagician-Support-20230118-1628.zip](https://github.com/terrymacdonald/DisplayMagician/files/10442442/DisplayMagician-Support-20230118-1628.zip)

**Comment by terrymacdonald** [comment]
ok @ssna, I've done some digging and I know what is causing the issue. There are two Game shortcuts that are invalid: 

- Content Manager.exe - Shortcut (SLI Surround Display Profile)
- SLI Surround Display Profile (Temporary)

"Content Manager.exe - Shortcut (SLI Surround Display Profile)" is invalid because it is a shortcut .lnk file. Earlier versions of DisplayMagician wouldn't have been able to notice that the shortcut link doesn't contain an icon embedded within it, and as such i accidentally left the image null (that is why there is an error when trying to show the game shortcut image).

The "SLI Surround Display Profile (Temporary)" game shortcut has a similar error, as there isn't a game being run, so there is no file to scan for an icon. 

I have removed these two Game Shortcuts from the file, so that you will be able to replace your Shortcuts_2.5.json config file with this new version and DisplayMagician should start working again. You then try and recreate the two Game Shortcuts again if you want and hopefully this time they will start working.

To replace the Shortcuts_2.5.json file do these steps:


- Close down DisplayMagician so it is not running.
- Open Windows File Explorer
- Navigate to C:\Users\<username>\AppData\Local\DisplayMagician\Shortcuts\
- Rename the existing Shortcuts_2.5.json file to Shortcuts_2.5.json.old
- Save the Shortcuts_2.5.zip file attached to this email to your PC, and extract the updated Shortcuts_2.5.json file from within the archive.
- Copy the extracted Shortcuts_2.5.json file into C:\Users\<username>\AppData\Local\DisplayMagician\Shortcuts\
- Open DisplayMagician and see if the problem goes away!

I would suggest avoiding targeting the .lnk files in future game shortcuts, and instead target the exe files directly e.g. the "C:\Program Files (x86)\Content Manager\Content Manager.exe" file rather than trying to load the shortcut link.
[Shortcuts_2.5.zip](https://github.com/terrymacdonald/DisplayMagician/files/10443427/Shortcuts_2.5.zip)

Good luck!
Terry

**Comment by ssna** [comment]
Thankyou for very clear instructions, unfortunately it didn't work, same error, but did manage a fix.  

I renamed directory to shortcuts# and restarted.  No great loss if I had to create new shortcuts and easy to change back.  No error, created first shortcut and it worked.  

A Utility like this is practically essential for any multimonitor setup. I used Helios nearly everyday.  It was great but hard to setup and I think a bit slower (or all the flashing screens and no countdown makes time seem quicker).  

Thankyou.
Stephen

FYI Screenshot of directory.  Can only assume there was an issue with the old icon files.  Assume they were created before the unhandled exception as they never showed in library.
![image](https://user-images.githubusercontent.com/15314850/213294002-c5f79169-b104-4259-89d3-5e732e06e02d.png)

**Comment by terrymacdonald** [comment]
@ssna Hmmm. I wonder what other bits in the Shortcuts file were causing the error? Oh well, glad you got it all working.

I won't troubleshoot it any further at this point, as I've pretty much stopped development on the 2.x branch of the codebase, as I'm rewriting DisplayMagician from scratch again as part of a move towards using .net 7 and WinUI 3 (completely different application style, UI and structure. I'm going to make use of all the new functionality within Windows 10/11 and potentially even distribute it via Windows Store (though still not absolutely sure about that part).

Hope the rest of your DisplayMagician usage goes smoothly for you.

I'll close this issue.

Thanks
Terry
