### ISSUE TITLE
Unsure if this is NV Surround or DisplayMagician?

### ISSUE THREAD

**Issue by Globespy** [terrymacdonald/DisplayMagician#189]
**Describe the bug**
I load my NVSurround profile before beginning iRacing.
I have noticed that sometimes I will lose a monitor (often the left of my triples setup).
When the image returns I will see the display resolution of that monitor as 2560x2880 instead of 2560x1440, and this is confirmed in the settings UI within the monitor itself. I'm guessing this larger resolution than what the monitor is could be causing bandwidth issues for the DP 1.4 ports?
I doubt this has anything to do with DM, and I need to check if this happens also when just using NVSurround natively without DM running, but thought I would mention in case it's ever been reported as an issue.
Thanks again for such an amazing app.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Reporting Logs**
If DisplayMagician starts:
- Open DisplayMagician and perform whatever actions are needed to make the bug occur.
- Click on the Settings button on the main DisplayMagician window
- Click on 'Create a Support Zip File' button
- Save the Support Zip File on your computer.
- Come back here, and upload the Support Zip File through your web browser and attach it to this issue.

If DisplayMagician does not:
- Open a terminal window and run `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` to create a TRACE-level DisplayMagician.log file.
- The above command will create a DisplayMagician.log file in `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Logs` which should contain a LOT of detailed TRACE level log entries. 
- Come back here, and upload the DisplayMagician.log file through your web browser and attach it to this issue.
- Also attach the following files to this issue:
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Profiles\DisplayProfiles_2.1.json` 
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Shortcuts\Shortcuts_2.0.json`
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Settings_2.0.json`

**Enviroment (please complete the following information):**
 - Windows Version: [e.g. Win10]
 - DisplayMagician Version [e.g. 1.1.0]
 - Video Card: [e.g. Asus NVIDIA GTX1070]
 - Number and make/model of monitors: [e.g. 2xDell UH2718H, 1x LG G27U17D]
 - Date of last video driver update: [e.g. 2021-02-15]
 - Date of last windows update: [e.g. 2021-02-15]

**Additional context**

**Comment by terrymacdonald** [comment]
Hi @Globespy,

Based on what you have mentioned, I would say it is a problem with the NVIDIA driver and NVIDIA hardware, how it talks to your monitors. There won't really be anything that DisplayMagician can do about that I'm afraid.

We could attempt to get the NVIDIA driver to add a new display layout to its internal database. You can do by creating a new display layout in NVIDIA Control Panel, then delete the old display profile in DisplayMagician. You can then try to use the new profile rather than the old profile. Creating a new layout in NVIDIA Control Panel will recreate the NVIDIA settings, and creating a new DM profile should re-grab those updated settings from the NVIDIA Driver. That *might* fix the issue for you.

I'm going to close this issue as there isn't anything I can do about it I'm afraid.

Thanks
Terry
