### ISSUE TITLE
"Pass arguments to Program" not retaining checkbox check

### ISSUE THREAD

**Issue by stringfieldmark** [terrymacdonald/DisplayMagician#19]
**Describe the bug**
When checking the checkbox for "Pass arguments to Program" and entering an argument, the checkbox does not retain the check, therefore the argument does not get passed to the program. I have also just done a clean install on another PC that has never had DM installed and it exhibits the same behaviour.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open DisplayMagician
2. Click on 'Game Shortcuts'
3. Select game shortcut to edit
4. Click 'Edit'
5. Select the 'Choose what happens before' tab
6. Enable the 'Checkbox' next to 'Pass arguments to program:'
7. Enter an argument (i.e. -switchgame iRacing)
8. Click 'Save'
9. Reselect the game shortcut just edited
10. Click 'Edit'
11.  Select the 'Choose what happens before' tab

**Expected behaviour**
'Checkbox' next to 'Pass arguments to program:' should now be checked (enabled) but it is not

**Screenshots**
N/A (I can do a video if needed)

**Reporting Logs**
N/A - if required let me know and I'll get the logs attached

**Enviroment (please complete the following information):**
 - Windows Version: 21H1 (OS Build 19043.1023)
 - DisplayMagician Version: 1.1.2.0
 - Video Card: Asus NVIDIA GTX1080Ti OC
 - Number and make/model of monitors: 3xMSI MAG322CQR and 1xBenQ PD3200U (running at 1440)
 - Date of last video driver update: 2021-06-03 (466.63)
 - Date of last windows update: 2021-05

**Additional context**
This is the first time I am using the arguments feature so am not sure if this worked before in older versions

**Comment by terrymacdonald** [comment]
Gah, I thought I tested all the bits of the start program stuff :(. Very sorry to all. Looks like I'll need a new release.

**Comment by terrymacdonald** [comment]
@stringfieldmark Can you please upgrade your DisplayMagician to v1.1.3 and try again. I found I'd missed two simple assignments within the code :/. Took me 10 seconds to fix....

I'm planning on adding some unit tests to the app eventually to alleviate some of these errors, but I want to wait and do it as part of the move from .NET Framework 4.8 to .NET6 and MAUI. Hopefully the big functional changes are all completed now, and it will be just little features and enhancements to add.

Anyway - please report back here as to whether this issue is now fixed.

**Comment by stringfieldmark** [comment]
Hi Terry,

The arguments now work, however, I cannot see any icons in the game shortcut library.

1.1.2.0:
![Version - 1 1 2 0](https://user-images.githubusercontent.com/29753726/121045367-a6677600-c7ad-11eb-8981-97f3034007f0.png)

1.1.3.0
![Version - 1 1 3 0](https://user-images.githubusercontent.com/29753726/121045380-a7000c80-c7ad-11eb-98d4-1b73b7bf8342.png)

I had to create a new shortcut to check the arguments and saved it to the desktop fine, but the app library shows up as blank.

**Comment by terrymacdonald** [comment]
Aarrgghh! Ok, do you use iRacing through a game library, or from a directly
specified application exe? I've an hunch my new redundancy fixes don't work
for applications 🙁

Thanks
Terry

**Comment by terrymacdonald** [comment]
@stringfieldmark Just letting you know I've fixed the issue. It was another stupid bug where the resiliency changes I made to ignore unsupported game libraries also inadvertently also filtered out application-based game shortcuts :/. 

Now fixed in v1.1.4. Hopefully this is the last problem for a while as so many silly errors on my part means everyone has to keep applying updates (and that gets frustrating as a user). Really sorry that my missing these errors is causing you so much testing effort.

Thanks for helping me out by reporting all these issues so I can straighten them out. It really helps.

Thanks
Terry

**Comment by stringfieldmark** [comment]
Hey Terry,

1.1.4 has worked a treat. So far so Gr8!

This is now, for me anyway, the ultimate start-up sequence program and not only for my gaming. I can see myself using this as a sequence for starting up what I need for my workday every morning.

Oh, and I am more than happy to do any testing, it is no effort at all and I've not found this frustrating at all. The effort you are putting into this is for us (the users), we should have no complaints.

Keep up the gr8 work.

Mark

**Comment by terrymacdonald** [comment]
Success! \o/

The next thing on the list for me is adding AMD Eyefinity support to fully
round out the application's functionality. But for that I need to source a
compatible AMD video card while I attempt to map the AMD ADL C language DLL
into C# managed code to enable me to do some testing. I'll need to find
some older AMD Radeon card to test with:
https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-5-2 .  I
might put a call out on Race Department to see if anyone has an old one
they can send me. I'm not 100% confident I have the needed skills to add
the Eyefinity support, but I might as well try it. Learning this sort of
stuff is the fun part!

Thanks

*Terry MacDonald *| Principal Security Consultant | Chief Operating Officer



M: +64 211 918 814 <+64+211+918+814>
E: ***@***.***
W: www.cosive.com
