### ISSUE TITLE
Another one with saving profile bug

### ISSUE THREAD

**Issue by Supertriton** [terrymacdonald/DisplayMagician#210]
**Describe the bug**
I have a bug when I want to save a profile and the grey zone is empty, I don't have any screen picture

**To Reproduce**
Click on Save profile

**Expected behaviour**
- Save my profiles :)
- Create 3 separated screens or 3 screens merged in 1

**Screenshots**
Error :
![image](https://user-images.githubusercontent.com/101670167/227374742-9e075ab8-8a47-43af-ab72-367170d6ae5d.png)
Empty grey zone :
![image](https://user-images.githubusercontent.com/101670167/227376394-a35a3fce-73ae-4f9f-ae7c-cb5140c5e784.png)

**Reporting Logs**
[DisplayMagician-Support-20230323-2302.zip](https://github.com/terrymacdonald/DisplayMagician/files/11056688/DisplayMagician-Support-20230323-2302.zip)

**Enviroment (please complete the following information):**
 - Windows Version: Win11
 - DisplayMagician Version 2.5.0.352
 - Video Card: Intel Arc A770
 - Number and make/model of monitors: 3x Iiyama G2530HSU plugged in displayport
 - Date of last video driver update: 2023-02-22
 - Date of last windows update: Latest ? 22H2 installed on 2023-03-21

**Additional context**
- I recently changed motherboard, cpu, ram and GPU without reinstall Win10 but I upgraded to Win11.
- I don't have another problem.
- I used a tool to remove old Nvidia drivers that came with my old GTX1080.
- I use Intel Graphics Command Center to create merged screen
- I'm not especially good to transcribe issue in English ! :)

**Comment by terrymacdonald** [comment]
Hi @supertriton,

Unfortunately there aren't any log files in the Support ZIP File. Can
you please go into DisplayMagician settings and change the Logging Level to
TRACE, then try and create that error again? Once you can manage to get the
error message to come up and make DM crash, then reopen DisplayMagician
again and create the Support ZIP File and upload it to this GitHub issue
with your web browser (attaching to this email doesn't work.

Thanks
*Terry *

**Comment by Supertriton** [comment]
Sure,

Here : 
[DisplayMagician-Support-20230324-0002.zip](https://github.com/terrymacdonald/DisplayMagician/files/11057069/DisplayMagician-Support-20230324-0002.zip)

**Comment by terrymacdonald** [comment]
Darn it. There still aren't any log files in that support zip file. That is
so weird!

Can you please go into
C:\Users\<username\AppData\Local\DisplayMagician\Logs and zip up all the
.log files into a ZIP file manually please? For some reason that Create
Support ZIP File button isn't working on your computer, and I'm not sure
why. It will be good for you to see if the log files are actually being
created or not...

Can you please

Thanks
*Terry*

**Comment by Supertriton** [comment]
There seems to be more information
[DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/11057196/DisplayMagician.zip)

**Comment by terrymacdonald** [comment]
@Supertriton thanks for that log file.

So I firstly have some bad news. DisplayMagician support 'merged' multiscreens via NVIDIA Surround or AMD Eyefinity only. **It doesn't currently support Intel Arc merged screens at all.** In order to make that work I would need to write a brand new video library that uses the Intel Arc video library. That's not going to happen for quite a while as I am trying to write a new version of DisplayMagician that uses the .net7 and WinUI3.... and that is going to take ages to do.

What this means is that DisplayMagician will definitely not be able to turn on the Intel Arc merged mode, and it _may_ not be able to turn off the Intel Arc merged mode either (that very much depends on the Intel Arc video driver restrictions). Sorry.

The error you are seeing is that DisplayMagician is seeing when DisplayMagician's display setting parsing code is confused by something it's seeing. I cannot see what it is getting confused by, as it isn't shown in the logs. 

In order to understand what is happening I'm going to need you to do some tests for me using my other video library software. Is that something you would be able to help me with? I hope so, as I would like DisplayMagician to at least be able to partially work when a computer has an Intel Arc video card.

Thanks
Terry

**Comment by terrymacdonald** [comment]
I've also opened a new feature request to add Intel Arc support so that I don't forget it.

**Comment by Supertriton** [comment]
> @Supertriton thanks for that log file.
> 
> So I firstly have some bad news. DisplayMagician support 'merged' multiscreens via NVIDIA Surround or AMD Eyefinity only. **It doesn't currently support Intel Arc merged screens at all.** In order to make that work I would need to write a brand new video library that uses the Intel Arc video library. That's not going to happen for quite a while as I am trying to write a new version of DisplayMagician that uses the .net7 and WinUI3.... and that is going to take ages to do.
> 
> What this means is that DisplayMagician will definitely not be able to turn on the Intel Arc merged mode, and it _may_ not be able to turn off the Intel Arc merged mode either (that very much depends on the Intel Arc video driver restrictions). Sorry.
> 
> The error you are seeing is that DisplayMagician is seeing when DisplayMagician's display setting parsing code is confused by something it's seeing. I cannot see what it is getting confused by, as it isn't shown in the logs.
> 
> In order to understand what is happening I'm going to need you to do some tests for me using my other video library software. Is that something you would be able to help me with? I hope so, as I would like DisplayMagician to at least be able to partially work when a computer has an Intel Arc video card.
> 
> Thanks Terry

Hello,

Of course with pleasure.  Your software is really great, I used it with my Nvidia, I wish I could help you with my Intel.

**Comment by Supertriton** [comment]
Hi,

I uninstall DisplayMagician while waiting to be able to help you because it launches at each start and ask me to setup.
Don't hesitate to contact me when you need me.

Triton

**Comment by terrymacdonald** [comment]
Will do. As mentioned above it will be a while, maybe up to a year from now :(. I'm doing all this work in my spare time, and I don't have as much time spare as I used to....

I'll definitely use your help testing though!

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Supertriton  I think this issue was related to a bug I recently found in the screen processing logic. I have completely rewritten the logic in this area, and I will be shortly releasing v2.6.0. This should hopefully fix your issue. I will post a link in this issue for you to download a test version of the software. Once you can confirm this fixes things then I'll be hopefully able to release this to the general public.

Expect something in the next 2 weeks.

Thanks
Terry

**Comment by Supertriton** [comment]
Hi, it's okay, i'm waiting :)

**Comment by terrymacdonald** [comment]
@Supertriton I've created a new test version of DisplayMagician that *may* fix the issue that you're experiencing, and I've attached it to this Github issue. Please download the attached zip file, extract the msi installer from the zip file, and then run the installer. It should upgrade your existing Display Profiles.

[DisplayMagicianSetup-v2.6.0.446.zip](https://github.com/terrymacdonald/DisplayMagician/files/14018624/DisplayMagicianSetup-v2.6.0.446.zip)

This new version of DisplayMagician has the ability to 'update' Display Profiles - effectively overwriting the display layout with the one that is currently being used. So if you start If you still start having issues with a Display Profile not working, simply:
- setup your display layout the way you want it
- then open DisplayMagician's Display Profiles Window
- select on the saved Display Profile you wish to update
- click the Update button
- say 'Yes' when asked if you really want to overwrite settings

Your DisplayMagician Display Profile will now be recreated using the current display settings, and they will overwrite the old settings. This will hopefully get rid of any display layout issues, and it doesn't require any changes to your Game Shortcuts. Nice!

There is a single known issue at the moment, which is that the NVIDIALibrary SetDisplayConfig function doesn't work for NVIDIA video cards. Luckily this issue shouldn't have much impact at all as the WindowsLibrary functions should do enough configuration of their own to ensure it all works. If you have some special NVIDIA settings that you use then this version of DisplayMagician *may* not apply them correctly. You will unfortunately just have to test if that is the case for your particular setup. 

I am currently troubleshooting the NVIDIALibrary SetDisplayConfig function error but it looks like it could be a bit of a pain to fix, so I didn't want to hold up the test release; I'd rather get the test version into your hands so I can see what other bugs are in there!

If this fixes your issue please reply here, and if you find another bug please log a new Github issue so I can track them separately.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Supertriton  I did find some issues with the earlier v2.6.0.446 version. I've made a lot of revisions to how DisplayMagician works in v2.6.0.485 (attached) that should make it way more reliable. But it is highly likely you will need to 'update' your Display Profiles to make them work properly.

I'd recommend first of all applying a Display Profile, and then press the 'update' button. That will recreate the config for the Display Profile and should make it work properly. You'll need to do that to each of your saved Display Profiles. Then please test out changing between your Display Profiles to see if everything works as expected.

Here is the latest test version of DisplayMagician: 
[DisplayMagicianSetup-v2.6.0.485.zip](https://github.com/terrymacdonald/DisplayMagician/files/14075432/DisplayMagicianSetup-v2.6.0.485.zip)

Thanks for all your help testing.

Terry

**Comment by terrymacdonald** [comment]
@Supertriton, I've added in more checks and logic to avoid crashes. Could you please try this latest version? 
[DisplayMagicianSetup-v2.6.0.508.zip](https://github.com/terrymacdonald/DisplayMagician/files/14135107/DisplayMagicianSetup-v2.6.0.508.zip)

I'm hoping this will work, but at the very least it should allow DisplayMagician to boot up enough for you to create a Support ZIP File. Let's see whether I've fixed it 🤞.

**Comment by terrymacdonald** [comment]
@Supertriton The latest test version should be working properly, and hopefully fixes your issue. Could you please test it for me so I know that it fixes your issue? If it does then I'll be able to close this issue as the fix will be part of the next full release.

[DisplayMagicianSetup-V2.6.0.515-No-NvApi_SetDisplayConfig.zip](https://github.com/terrymacdonald/DisplayMagician/files/14200905/DisplayMagicianSetup-V2.6.0.515-No-NvApi_SetDisplayConfig.zip)

As I've not really had any feedback from you recently I'll give it a week and then close this issue if I have no further responses. We can always reopen this issue in the future if you are still having problems.

Thanks!

**Comment by Supertriton** [comment]
Hi @terrymacdonald,

Apologies for the delay, I've been busy.

I've installed the latest version you provided, and I'm encountering an issue, I can't switch between the 2 profiles. The Intel Graphics Command Center appears to create a new display when it merges the 3 displays.

![displaymagician](https://github.com/terrymacdonald/DisplayMagician/assets/101670167/2a0d17fc-8dbc-4999-afa0-2a3baf5f31c4)

**Comment by terrymacdonald** [comment]
Does it still do that if you create a new display profile that's the same
as the one not working? In other words if you create a new Triple profile,
does that work?

Are you using an Intel Arc GPU for your triple, or is it NVIDIA or AMD?

Can you please attempt to change b0 between your Single and Triple profile
and back again please? And then create a Support ZIP File and attach it to
this issue.

Thanks again for your testing help!

Thanks
Terry

**Comment by Supertriton** [comment]
Yes, it's the same issue. I can't switch between merged or separated profiles.

Yes, I'm using an Intel Arc A770. I can create a support zip file, but I'm not sure if it will help you because the "Apply Profile" button is greyed out and non-clickable, so nothing happens.

**Comment by terrymacdonald** [comment]
Hi @Supertriton,

OK, Unfortunately DisplayMagician doesn't support Intel Arc Merged Screens,
as any merged screen support requires creation of a new video library to
interrogate and record the new video card. I would need to write the Intel
Arc video library  from scratch in order to use merged screens, and this is
impossible at the moment as I do not have an Intel Arc device to test with.

I'm hoping to get enough donations to be able to cover getting an Intel Arc
for testing (or if someone has an old Intel Arc that is still supported by
the Intel driver and they want to donate it to me), because otherwise I
won't be able to add support.

Any Intel Arc display layout will work as long as it is a 'standard'
windows display layout, as the WinLibrary will able to grab the settings.
The issue arises swapping between merged screens and non-merged screens, as
DisplayMagician currently has no way to tell the Intel Arc card to setup a
merged screen or tear it down. This is the new functionality I would have
to add.

Sorry there isn't anything I can do right now. Hopefully I get my hands on
an Intel Arc card one day and I can spend the 2-3 months working on a new
library.

Thanks
*Terry *

**Comment by terrymacdonald** [comment]
Oops I broke the setup with my previous version.  This version has a corrected setup that should install everything properly.

[DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip](https://github.com/terrymacdonald/DisplayMagician/files/14249946/DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip)

FYI I'm tracking the Intel Arc merged screen support in issue #212. You can follow along there if you want.

Thanks
Terry

**Comment by Supertriton** [comment]
I've tried your latest update, but it's still the same issue.

I attempted switching from merged to separated and vice versa.

But I'm still open to any further testing. :)

**Comment by terrymacdonald** [comment]
Ok, I think that this issue has now morphed into a replica of the Intel Arc
support issue in #212.

As it looks like the original issue of profile facing is now fixed, I'll
close this issue, and you can follow along with the #212 issue there. I'll
update that with any Intel Arc work I do under that issue and hopefully
you'll be able to help me do some testing.

Thanks
Terry
