### ISSUE TITLE
Ability to overwrite Profiles

### ISSUE THREAD

**Issue by NightHammer1000** [terrymacdonald/DisplayMagician#215]
It would be nice to have the ability to overwrite Profiles by just saving a new Profile with the Same name.
The UUID should stay the same so that I dont have to change out Batch Scripts and Shortcuts.

Sometimes after Driver Updates all the Profiles won't work anymore.
Especially if you have to DDU after a driver fucks something up.

This could save us a lot of Work in the Future.

**Comment by terrymacdonald** [comment]
Hi @NightHammer1000 ,

Unfortunately the way that Profiles works prevents me from adding this functionality as you have described it. There is, however, a potential alternative.

I was thinking about adding a 'replace profile' functionality into the Game Shortcuts. This would mean that when you created a game shortcut with a previous display profile, if that display profile was deleted, then you would automatically be asked which other display profile you wanted to replace it with in all your game shortcuts. The idea would be to easily all your game shortcuts with a single click when you have to replace display profile.

With this functionality you wouldn't need to have the UUID stay the same, as the game shortcut would be updated, and you would only need to be able to run the game shortcut from the command line.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@NightHammer1000 do you mind if I change the name of this issue to be 'Ability to replace Profiles in Game Shortcuts'? It's more accurately what I think I'll be able to do.

Thanks
Terry

**Comment by NightHammer1000** [comment]
To bad. That actually won't help me that much as I don't use Game Profiles at all.

Display Magician only works as a Display Profile Switcher with hotkeys for me.
I also use the Desktop Shortcuts for said Profiles in a Batch files to Switch to a HDMI Dummy Plug Display when I play with my Steam Deck Remotely over Moonlight and back to the Default Profile after I disconnect.

I just need a way to keep the UUID the same for those Shortcuts in some way. Maybe a ability to set custom UUIDs?

**Comment by NightHammer1000** [comment]
Okay. That sounds like it could work.
Great!
Thanks!

**Comment by terrymacdonald** [comment]
@NightHammer1000  I've nearly finished development of a way to update a display profile to the current display layout in use. This should enable people to simply recreate a display layout and update the Display Profile with the current settings, eliminating the need for making changes to any Game Shortcuts. I'm hoping this makes everyone's lives easier.

Expect something in the next 2 weeks.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@NightHammer1000 The latest test version should be working properly, and it has an 'Update' button for Display Profiles. 

Could you please test it for me so I know that it fixes your issue? If it does then I'll be able to close this issue as the fix will be part of the next full release.

[DisplayMagicianSetup-V2.6.0.515-No-NvApi_SetDisplayConfig.zip](https://github.com/terrymacdonald/DisplayMagician/files/14200905/DisplayMagicianSetup-V2.6.0.515-No-NvApi_SetDisplayConfig.zip)

As I've not really had any feedback from you recently I'll give it a week and then close this issue if I have no further responses. We can always reopen this issue in the future if need be.

Thanks!

**Comment by NightHammer1000** [comment]
Hi.

This Version does not start on my System.
Flat out refuses to start up without writing out a log file.

**Comment by NightHammer1000** [comment]
<img width="351" alt="image" src="https://github.com/terrymacdonald/DisplayMagician/assets/1979250/d5f4459c-4b5f-485c-beec-b6627414f399">

**Comment by terrymacdonald** [comment]
Can you please create a ZIP file of your DisplayMagician folder in
C:\Users\<username>\AppData\Local\DisplayMagician? And then upload it to
this issue? I might be able to see if there is a configuration issue
somewhere.

Was there any more text with that error message? Where did you get that
error from?

Lastly, can you please remind me what GPUs and CPUs you have, and how many
displays you have and how they are connected? Are any connected through
adapters like USB to display port adapters?

Thanks
Terry

**Comment by NightHammer1000** [comment]
Nope. There is no more Info. That screenshot is from the Event Viewer. And thats everything there is in there.

I also tried to delete the App data local folder to recreate it because I already suspected it might be something with the configs.

Did not help.

The Program crashed before it even recreated the folder.

**Comment by terrymacdonald** [comment]
Hmmmm. Can you please tell me what GPUs and CPUs you have, and how many
displays you have and how they are connected? Are any connected through
adapters like USB to display port adapters?

It might be something in your set up causing DM to error.

Did you have an old video card that you used and now you swapped to
something else? For example did you use the have an NVIDIA card and now use
AMD? Or do you use Intel Arc?

Thanks
Terry

**Comment by NightHammer1000** [comment]
Always had NVIDIA in that Machine.
Its an AMD Ryzen 9 7900X3D and a RTX 4080

4 Displays are connected. 3 on DisplayPort one on HDMI.

Nothing Fancy. The exact same setup I used with the current Version.

Old Version from the Releases Page works just fine.

**Comment by NightHammer1000** [comment]
Had time to fire up Visual Studio and run the debugger on the exe.
It throws pre-Init, while loading references.

DisplayMagician.Shared, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null

Thats what it can not find.

**Comment by NightHammer1000** [comment]
It seems that file is Missing in the Installer.
If I install a old Version, the file is there in the root directory of the App.
In the newest version, its not.

Sooo. Dont think its my rig^^

**Comment by NightHammer1000** [comment]
If I copy the file over from the old to the new, it starts up.

**Comment by NightHammer1000** [comment]
But does not seem to handle DPI Scaling very well:
<img width="982" alt="image" src="https://github.com/terrymacdonald/DisplayMagician/assets/1979250/31701c1f-4fa1-442b-a03b-190fbe1f1633">

**Comment by terrymacdonald** [comment]
Huh! That's weird.

Ok that's an excellent find. It's a Setup building problem. Thank you so
much for debugging! This is perfect! I'll have to test a new build to make
sure it does copy things across properly.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@NightHammer1000 could you please test this version? Its got the corrected setup that should install everything (I've yet to fully test myself!) but it doesn't have any DPI scaling fixes. If you'd be able to get back to me with whether this works, and if it still has the DPI scaling issues then please reply with how you got it to look like the picture you provided earlier.

[DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip](https://github.com/terrymacdonald/DisplayMagician/files/14249946/DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip)

Thanks
Terry

**Comment by NightHammer1000** [comment]
@terrymacdonald got to test it out.
Now it works as it should.

Updating Profiles works.

For the DPI Issue, I had to set DPI Scaling in Compatibility Settings to "System (Advanced)"
Now everything looks good again.
There should be a way to tell the System to handle DPI instad of DotNet. I think something in the Manifest.
My C# is a bit rusty.

Thanks!

**Comment by terrymacdonald** [comment]
Hi All,

Time for an update.

The fix is in the code and works (also we now support 3rd apps and games added to Steam library too!) but my current hold up is actually in the packaging of the application into a windows installer. I've been testing different ways to do this as the move from .net framework 4.8.1 to .net core 8.0.0 has been a massive change. It has resulted in a completely different set of binaries and dlls and other files being created, as well as a different build process too. This is all taking some time to figure out.

I've gone from a WIXv3 based installer to a windows default installer to an NSIS installer then back to a WIXv4 installer all within the last month. It's necessitated me building a brand new way of handling the desktop background context menu, and even down to which libraries are used within the application. It's been a ton of work.

I'm now down to the last few bugs to iron out, and to finish the new packaging process. I think I should have something ready for everyone to test within the next month (assuming there aren't anymore show stoppers.

My goal is to then send out messages through this issues list to get you all to test some DM v2.6.0 test builds, and then once the major bugs are ironed out I will push out the DM v2.6.0 beta to those users who opted in the beta builds. And then I'll finally push the DM v2.6.0 update to the main user group.

Lastly, I've decided to hold back the NVIDIALibrary update for now until DM v2.7.0 as it requires a LOT more work testing and troubleshooting many errors. The Steam beta client changing file structures has forced my hand here a little bit, so a better NVIDIALibrary will just have to wait for now.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi!

This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here: 
 https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1

It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing. 

Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).

Thanks
Terry

**Comment by terrymacdonald** [comment]
ok I believe this is fixed now in the latest alpha, so I will go ahead and close this issue for now. Please feel free to reopen it if you still have the issue after testing it.

Thanks
Terry
