### ISSUE TITLE
DisplayMagician CurrentProfile doesn't provide an output

### ISSUE THREAD

**Issue by EthanGJ123** [terrymacdonald/DisplayMagician#223]
When using DisplayMagician CurrentProfile, the program doesn't return a value, and exits.

Steps to reproduce the behaviour:
1. Go to command prompt
2. cd to the DiaplayMagician directory
3. Execute the command `DisplayMagician CurrentProfile`
4. See that the program exits without output

I would expect either a name or identifier of a profile

[DisplayMagician-Support-20230516-0719.zip](https://github.com/terrymacdonald/DisplayMagician/files/11484592/DisplayMagician-Support-20230516-0719.zip)

 - Windows Version: Win11 Pro
 - DisplayMagician Version 2.5.0.352
 - Video Card: MSI NVIDIA GTX1050Ti
 - Number and make/model of monitors: 2x Acer S240HL, 1x MSI G271
 - Video driver version: 528.49
 - Windows version: 22621.1702

**Comment by terrymacdonald** [comment]
@EthanGJ123 I just tested and yes, you are correct. It has stopped working at some point, so I will have to go back and try and troubleshoot why that is. Thank you for bringing this to my attention.

Pleas note it will be a month or so before I'll be able to work on this in depth, as real life has gotten substantially busier over the last little while. I'll do my best to investigate as the issue *hopefully* won't be too difficult to fix.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@EthanGJ123 I tried to get the CurreentProfile to work on this WinForms application but unfortunately I haven't been able to get this to work. WinForms apps don't natively have support for console output, so you have to kind of glue it in there, and every method I tried didn't work.

So, I've decided to work on creating a separate console programme that will use the shared profile libraries to provide that feedback, much like Soroush Falahati did with the original Helios Display Management back in the day. This will take a little while to sort out, but I'm hopeful I'll be able to get the basics built in before the next release happens. We shall see.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@EthanGJ123 Good news! I've made a new separate console application called DisplayMagicianConsole.exe that allows you to interact with DisplayMagician Display Profiles from a script. This allows the following three commands:

- **DisplayMagiciancConsole.exe CurrentProfile**: This will show the name and UUID of the display profile in use
- **DisplayMagiciancConsole.exe AllProfiles**: This will show the name and UUID of all the available display profile that have been saved within DisplayMagician.
- **DisplayMagiciancConsole.exe ChangeProfile <ProfileName|UUID>**: This will change to the display profile with the Name or UUID provided by the user. If the Display Profile is valid to use right now then it will be  applied. You can re-apply the same profile that is in use now. If applying the display profile is not successful then you will be given an error message explaining what happened.

The idea is that you use the first two commands to figure out which Display Profile you want to use, and then use the last command to swap to it. 

I've made a special new test version of DIsplayMagician for you to try. Please give it a test and give me any feedback.

[DisplayMagicianSetup-v2.6.0.517-console.zip](https://github.com/terrymacdonald/DisplayMagician/files/14227722/DisplayMagicianSetup-v2.6.0.517-console.zip)


And if you like what I do, then I'm open to [receiving donations](https://github.com/sponsors/terrymacdonald). I'm hoping to save up for an Intel Arc video card so that I can add some Intel Arc support to DisplayMagician.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Oops I broke the setup with my previous version.  This version has a corrected setup that should install everything properly.

[DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip](https://github.com/terrymacdonald/DisplayMagician/files/14249946/DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip)

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi All,

Time for an update.

The fix is in the code and works (also we now support 3rd apps and games added to Steam library too!) but my current hold up is actually in the packaging of the application into a windows installer. I've been testing different ways to do this as the move from .net framework 4.8.1 to .net core 8.0.0 has been a massive change. It has resulted in a completely different set of binaries and dlls and other files being created, as well as a different build process too. This is all taking some time to figure out.

I've gone from a WIXv3 based installer to a windows default installer to an NSIS installer then back to a WIXv4 installer all within the last month. It's necessitated me building a brand new way of handling the desktop background context menu, and even down to which libraries are used within the application. It's been a ton of work.

I'm now down to the last few bugs to iron out, and to finish the new packaging process. I think I should have something ready for everyone to test within the next month (assuming there aren't anymore show stoppers.

My goal is to then send out messages through this issues list to get you all to test some DM v2.6.0 test builds, and then once the major bugs are ironed out I will push out the DM v2.6.0 beta to those users who opted in the beta builds. And then I'll finally push the DM v2.6.0 update to the main user group.

Lastly, I've decided to hold back the NVIDIALibrary update for now until DM v2.7.0 as it requires a LOT more work testing and troubleshooting many errors. The Steam beta client changing file structures has forced my hand here a little bit, so a better NVIDIALibrary will just have to wait for now.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi!

This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here: 
 https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1

It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing. 

Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).

Thanks
Terry

**Comment by terrymacdonald** [comment]
ok I believe this is fixed now in the latest alpha, so I will go ahead and close this issue for now. Please feel free to reopen it if you still have the issue after testing it.

Thanks
Terry
