### ISSUE TITLE
DisplayMagician not passing launch arguments to Steam games

### ISSUE THREAD

**Issue by pl4sma2389** [terrymacdonald/DisplayMagician#226]
**Describe the bug**
The "Pass arguments to Game" box in the Steam game launch section appears to be non-functional for at least the following games:
Assetto Corsa Competizione
Automobilista 2

**To Reproduce**
1. Create a profile that launches ACC or AMS2 with a certain launch option (e.g. "steam://launch/1066890/vr" for AMS2 or "-vr hmd=SteamVR" for ACC (without quotes)).
2. Run the profile.
3. Observe that it does not launch with those launch parameters.
4. Check with Process Explorer to determine that no launch parameters are passed.

**Expected behaviour**
The game would launch with the specified launch parameters.

**Screenshots**
N/A

**Reporting Logs**
[DisplayMagician-Support-20230522-1701.zip](https://github.com/terrymacdonald/DisplayMagician/files/11537063/DisplayMagician-Support-20230522-1701.zip)

**Additional context**
I run a triple screen setup with my computer for work and flight sim, but my racing rig is off to the side without a monitor (VR only). I'd like to take advantage of DisplayMagician (which I already use for flight sim and other monitor config loading duties) for launching various racing games and their support applications in VR, but not being able to quickly launch them into VR with launch options isn't letting that happen.

**Comment by terrymacdonald** [comment]
@pl4sma2389  I'll try doing some testing over the next couple of weeks to see if this is still passing things through to steam. It did in the past, but some other changes may have broken this feature.

Terry

**Comment by terrymacdonald** [comment]
@pl4sma2389 I found the issue. I had inadvertently dropped a forward slash off the URL. The format that works was `steam://run/<id>//<args>/`, as shown here: https://developer.valvesoftware.com/wiki/Steam_browser_protocol

I was using `steam://run/<id>/<args>/ `(so it didn't work. I just confirmed this change does pass commandline options through tot he game (I tried Beat Cop) and passed some arbitrary commands through and confirmed it with ProcessExplorer.

This will be fixed in v2.6.0 which should be released in a week or so.

Thanks 
Terry
