### ISSUE TITLE
Ability to open Windows Store Apps

### ISSUE THREAD

**Issue by dewijones94** [terrymacdonald/DisplayMagician#238]
While trying to create shortcuts to Xbox App Games i get an access denied launching the actual exe, this is because of the way permissions are handled by Xbox and there is no way to alter the permissions of the exe. The actual app that i am trying to create a shortcut to is Forza Horizon 5.

I'd assume that having the ability to choose an app installed on the device as the shortcut, rather than just an exe or com library would negate this message, bypassing the need to use the exe.

**Comment by terrymacdonald** [comment]
@dewijones94 The issue here is that all Xbox App Games I've seen are actually Microsoft Store Games, and those have a completely different way of running. They use the new UWP or Windows App way of operating, which doesn't really work easily with .net Framework-based software like DisplayMagician. I've already had a person request some support for UWP games under #98, but it's really not very simple to add.

I've already added the ability to start a UWP app (but not monitor it for closure), but that is under the Application section, not the game one. To use it, create an Application shortcut rather than a Game shortcut. You should be able to select Forza Horizon 5 from the list of Applications, and it will still work ok - though please note that DisplayMagician is unlikely to be able to detect that the game has started so it will likely just finish the game shortcut and revert everything back straight away. Unfortunately this is a windows permission thing, and the only way I can get around that is to completely rewrite DisplayMagician from scratch as a new WinUI3 Windows App.

I've actually started doing just that, but it will take 6 month to a year to port everything over as it is such a massive change in the background. The WinUI version will be called DisplayMagician v3, and will be able to run/monitor UWP and Windows App games just as well as traditional apps.

Hope that clarifies?

Thanks
Terry

**Comment by dev1981** [comment]
hi,

maybe it will help to use the cmdline mentioned in that article; (bottom)
https://answers.microsoft.com/en-us/windows/forum/all/starting-windows-10-store-app-from-the-command/836354c5-b5af-4d6c-b414-80e40ed14675

AND / OR a dedicated powershell script which u can reference in DPM.
Then the cmdline in DPM will point to powershell.exe + script-cmdline
 as well starting the game process and have a wait for the started Application might be possible. But yes, it will be a workarround.

**Comment by dewijones94** [comment]
Thanks both. Completely understand it’s not a quick think @terrymacdonald, just wanted to put it forward for consideration. I’m happy to work round it for now, honestly loving the app so far! And also happy to help beta test anything for you 😉

@dev1981 using the shell command works to launch it, unfortunately using the exe to detect when it’s closed doesn’t work either, so I’ve built a loop in the script to monitor for the exe and close when it ends so it can use that to switch back the display, so definitely a workaround for now as well!

**Comment by terrymacdonald** [comment]
Hi @dewijones94

Would you be open to providing me a copy of the script with the loop in it
so I can add it to the troubleshooting page of the wiki so that others can
make use of it? I'd really love to provide others with a temporary
workaround until I can find time to get DisplayMagician v3 completed.

To be clear, your coffee would become part of the DisplayMagician codebase
and so would be licensed as GPL v3.

Thanks
Terry

**Comment by dewijones94** [comment]
Hi @terrymacdonald certainly, I can send over first thing with some instruction to customise it for other apps as well. 7:45pm here and I’m not sat at my computer right now!

**Comment by dewijones94** [comment]
Hi @terrymacdonald 

Here is the batch i am using, just a very simple launch and wait essentially. The App launch shortcut is done using the link above that Dev1981 shared also https://answers.microsoft.com/en-us/windows/forum/all/starting-windows-10-store-app-from-the-command/836354c5-b5af-4d6c-b414-80e40ed14675
To note, when looking at the target in the shortcut to find the app name, there is a section that has the exclamation and then the app name, if this is present it already contains everything you need to launch the app without having to go to the XML as the person in the link mentions. And to also note, if this is for a game using the Xbox app, the location of that XML will be in the location that you install the game to.

In my example below, i use a loopback ping to wait because the pre-wrapper takes ages to launch the actual executable (forza things) but i would recommend leaving it in and reducing it based on the time it takes for their app to launch. Then i am just using tasklist to search for the exe and loop if its still running every 5 seconds. Also, to note, tasklist results are case sensitive, so for example, my "ForzaHorizon5" would not be detected if it was in lower case.

```
explorer.exe shell:appsFolder\Microsoft.624F8B84B80_8wekyb3d8bbwe!Forzahorizon5

ping 127.0.0.1 -n 21 > nul

:LOOP
Tasklist | find "ForzaHorizon5" >nul
IF ERRORLEVEL 1 (
  GOTO CONTINUE
) ELSE (
  ECHO Forza is still running
  ping 127.0.0.1 -n 6 > nul
  GOTO LOOP
)

:CONTINUE
Exit
```


On a complete side note, when game shortcuts are created in your application, are they stored somewhere? I am getting an unhandled exception when loading the shortcuts screen, displaying the shortcuts, and i think its because it might be referencing an icon no longer there? So justy wanted to try manually deleting them and seeing if it'll load then. If the icon is the issue, might be worth opening another issue to add a default icon if one is not found to catch the exception?

**Comment by dewijones94** [comment]
Hi @terrymacdonald 

Further on the above regarding the unhandled exception, i have found the cause. I managed to find the JSON file that the shortcuts are listed in and removed the one i created pointing to the batch file. This then stopped displaying the unhandled exception. To be sure it was that i recreated the shortcut and as soon as i click save, the unhandled exception comes up. If i click continue, the area where the shortcuts displayed just displays a red cross over it.

I'm guessing this is because im referencing a bat file and its unable to scrap the icon for this? I've pasted the exception text for you below. Would it be best to have a fallback on this scrape, where the launching file is not an exe, and falls back to a default DisplayMagician Icon?



************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DisplayMagician.UIForms.ShortcutILVRenderer.DrawItem(Graphics g, ImageListViewItem item, ItemState state, Rectangle bounds)
   at Manina.Windows.Forms.ImageListView.ImageListViewRenderer.RenderItems(Graphics g)
   at Manina.Windows.Forms.ImageListView.ImageListViewRenderer.Render(Graphics graphics)
   at Manina.Windows.Forms.ImageListView.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by terrymacdonald** [comment]
Yeah I guess it is that for the exception. I'll have to update the file
scanning code to find that post. Nice find!

Thanks
Terry

**Comment by dewijones94** [comment]
Thanks, so wouldn't really be able to use that as a workaround until thats handled, as it would break the shortcuts menu for users.

**Comment by terrymacdonald** [comment]
@dewijones94 Are you able to test your batch file with this new test version of DisplayMagician I've made?

The latest test version should be working properly, and hopefully fixes your issue. Could you please test it for me so I know that it fixes your issue? If it does then I'll be able to close this issue as the fix will be part of the next full release.

[DisplayMagicianSetup-V2.6.0.515-No-NvApi_SetDisplayConfig.zip](https://github.com/terrymacdonald/DisplayMagician/files/14200905/DisplayMagicianSetup-V2.6.0.515-No-NvApi_SetDisplayConfig.zip)

Thanks!

**Comment by terrymacdonald** [comment]
@dewijones94 I've been testing opening UWP apps and monitoring them from DisplayMagician, and I think the most recent code changes may have managed to get this working.

[DisplayMagicianSetup-v2.6.0.521-uwp.zip](https://github.com/terrymacdonald/DisplayMagician/files/14227964/DisplayMagicianSetup-v2.6.0.521-uwp.zip)

Can you please install this test version and see that you can open Windows Store apps and DisplayMagician will wait for them to close?

Thanks
Terry

**Comment by terrymacdonald** [comment]
Oops I broke the setup with my previous version.  This version has a corrected setup that should install everything properly.

[DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip](https://github.com/terrymacdonald/DisplayMagician/files/14249946/DisplayMagicianSetup-v2.6.0.522-corrected-setup.zip)

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi All,

Time for an update.

The fix is in the code and works (also we now support 3rd apps and games added to Steam library too!) but my current hold up is actually in the packaging of the application into a windows installer. I've been testing different ways to do this as the move from .net framework 4.8.1 to .net core 8.0.0 has been a massive change. It has resulted in a completely different set of binaries and dlls and other files being created, as well as a different build process too. This is all taking some time to figure out.

I've gone from a WIXv3 based installer to a windows default installer to an NSIS installer then back to a WIXv4 installer all within the last month. It's necessitated me building a brand new way of handling the desktop background context menu, and even down to which libraries are used within the application. It's been a ton of work.

I'm now down to the last few bugs to iron out, and to finish the new packaging process. I think I should have something ready for everyone to test within the next month (assuming there aren't anymore show stoppers.

My goal is to then send out messages through this issues list to get you all to test some DM v2.6.0 test builds, and then once the major bugs are ironed out I will push out the DM v2.6.0 beta to those users who opted in the beta builds. And then I'll finally push the DM v2.6.0 update to the main user group.

Lastly, I've decided to hold back the NVIDIALibrary update for now until DM v2.7.0 as it requires a LOT more work testing and troubleshooting many errors. The Steam beta client changing file structures has forced my hand here a little bit, so a better NVIDIALibrary will just have to wait for now.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi!

This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here: 
 https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1

It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing. 

Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).

Thanks
Terry

**Comment by terrymacdonald** [comment]
ok I believe this is fixed now in the latest alpha, so I will go ahead and close this issue for now. Please feel free to reopen it if you still have the issue after testing it.

Thanks
Terry
