### ISSUE TITLE
Can Only Svae One Display Profile

### ISSUE THREAD

**Issue by WebSpectrum** [terrymacdonald/DisplayMagician#244]
**Describe the bug**
When trying to rename the existing profile or save a second display profile, ger error message 'sorry each display proflle needs a unique name...'

**To Reproduce**
Try to rename an existing display profile or save a second display profile

**Expected behaviour**
Should be able to save a second display profile or renamy the existing one

**Screenshots**

**Reporting Logs**
If DisplayMagician starts:
- Open DisplayMagician and perform whatever actions are needed to make the bug occur.
- Click on the Settings button on the main DisplayMagician window
- Click on 'Create a Support Zip File' button
- Save the Support Zip File on your computer.
- Come back here, and upload the Support Zip File through your web browser and attach it to this issue.

If DisplayMagician does not:
- Open a terminal window and run `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` to create a TRACE-level DisplayMagician.log file.
- The above command will create a DisplayMagician.log file in `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Logs` which should contain a LOT of detailed TRACE level log entries. 
- Come back here, and upload the DisplayMagician.log file through your web browser and attach it to this issue.
- Also attach the following files to this issue:
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Profiles\DisplayProfiles_2.1.json` 
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Shortcuts\Shortcuts_2.0.json`
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Settings_2.0.json`

**Enviroment (please complete the following information):**
 - Windows Version: [e.g. Win10]
 - DisplayMagician Version [e.g. 1.1.0]
 - Video Card: [e.g. Asus NVIDIA GTX1070]
 - Number and make/model of monitors: [e.g. 2xDell UH2718H, 1x LG G27U17D]
 - Date of last video driver update: [e.g. 2021-02-15]
 - Date of last windows update: [e.g. 2021-02-15]

**Additional context**

**Comment by terrymacdonald** [comment]
Hi @WebSpectrum,

DisplayMagician only allows you to save and apply Display settings. Any Display Setting changes need to be made within Windows Settings, NVIDIA or AMD software. 

A design decision was taken early on with DisplayMagician to only allow users to have a single Display Profile with the same name. This is the reason that the **Save** button turns into the Rename button once a Display Profile has been saved.

It isn't always clear to new users that if you want to create a new Display Profile, then you need to change the settings within Windows Settings, NVIDIA or AMD software, and then swap back top DisplayMagician to save those settings. Once you swap back and click on the **View Current Display** button, the display layout image should have updated and should reflect just how the screens look in real life. At the point you can then click the Save button to save the new Display Profile.

Does this explanation help? Based on my reading of your issue it's related to you not knowing that you have to click on the **View Current Display** button in order to see your current display layout, and therefore being able to save that as a new Display Profile.

I'll take it onboard to add some help text to point new users towards that button.

Thanks
Terry
