### ISSUE TITLE
Steam launch parameters are ignored

### ISSUE THREAD

**Issue by FormelLMS** [terrymacdonald/DisplayMagician#27]
Steam launch parameters are ignored if set into DisplayMagician
There is no way to get them to work.

**Comment by terrymacdonald** [comment]
Hmmm. I'll have to do some testing on this one. 

Each Game library is different for what level of command line parameters it supports. I will have to do some testing and roll any fixes into Display Magician v2.0.0.

**Comment by terrymacdonald** [comment]
Hi @FormelLMS,

Letting you know I've found the issue, and I've managed to fix it as part of this issue, which will be fixed in v1.1.5.

I am also letting you know that I still have to fix launch parameters for the other game libraries (i.e. Origin, Uplay, GOG, etc) at a later date, as I'd like to avoid offering the launch parameter option if it's not supported by that game library. I also want to link to useful launch parameters if they are held anywhere.... I was thinking something similar to this but for main games might be useful: https://github.com/terrymacdonald/DisplayMagician/wiki/Start-Program-Examples

What do you think?

Anyway, as with the other issue I'll close this for now so that I know what I've finished working on. The fix will be available when DisplayMagician v1.1.5 is released in a few weeks.

Thanks
Terry

**Comment by FormelLMS** [comment]
This is a good idea. Hopefully there would be more Startup things like „open dash da on Simhub when starting game xy“ but I definitely think that Simhub can’t do that.
