### ISSUE TITLE
Not all displays connected

### ISSUE THREAD

**Issue by Gonzz45** [terrymacdonald/DisplayMagician#28]
I get an error saying something like, profile cant open not all displays connected. Yet all 3 displays are clearly operating in windows.

**Comment by terrymacdonald** [comment]
Hi @Gonzz45,

I'm going to need WAY more information than that to be able to offer you any help. 

Can you first please describe more detail about what you are doing when you see the problem? Is it only one screen that isn't showing up? Can you describe how it is connected and the make and model of the screen? And what type of video card do you have? Can you please see issue #5 for an example of the information you need to provide in order for me to be able to help you fix the problem you're experiencing. I need you to provide that level of information, and then I'll understand your issue more.

DisplayMagician is a complicated bit of code, and there are a lot of potential failure points, as there are hundreds of different video cards, display drivers, screens and similar. Without logs and good bug reports I can't actually fix bugs.

I will need to see a TRACE DisplayMagician.log file, and I need a copy of your Shortcuts_1.0.json file and your DisplayProfiles_1.0.json file as well in order to troubleshoot this.

You can create a TRACE DisplayMagician.log by opening a command prompt (press Ctrl + R, and type cmd and press enter), and running `C:\Program Files\DisplayMagician\DisplayMagician --trace`. This command will make DisplayMagician generate a DisplayMagician.log file in the `C:\Users<yourusername>\AppData\Local\DisplayMagician\Logs` folder. Please go there, open the DisplayMagician.log file and check that there are a lot of 'TRACE' log entries in the log file. If there aren't, then you'll need to try to run the command again to make DisplayMagician generate the DisplayMagician.log file.

The Shortcuts_1.0.json file will be in the `C:\Users<yourusername>\AppData\Local\DisplayMagician\Shortcuts` folder, and the DisplayProfiles_1.0.json file will be in the `C:\Users<yourusername>\AppData\Local\DisplayMagician\Profiles` folder. I'll need both of them in order to troubleshoot this.

Then please reply in this issue chain and attach the DisplayMagician.log, Shortcuts_1.0.json and DisplayProfiles_1.0.json files to the issue so that I can see them. 

Thanks
Terry

**Comment by Gonzz45** [comment]
Hi, i was able to get it working again by deleting the monitor profiles and starting over. But it worked great for a few days then just quit before.I am running a viotex 34" uwhd 1440 center and 2x spectre 27" 1080 sides. Msi 3070gpu and ryzen 3700x. B550mb 32gb 3200 ramAll my monitors were still on and working in windows, but display magician claimed they werent all connected.Next time this happens i will see if i can figure out a way to create log files.Thank you, this software is great if i can figure that issue out i plan to make a donation for your work.Mike
-------- Original message --------From: terrymacdonald ***@***.***> Date: 7/12/21  3:13 PM  (GMT-07:00) To: terrymacdonald/DisplayMagician ***@***.***> Cc: Gonzz45 ***@***.***>, Mention ***@***.***> Subject: Re: [terrymacdonald/DisplayMagician] Not all displays connected (#28) 
Hi @Gonzz45,
I'm going to need WAY more information than that to be able to offer you any help.
Can you first please describe more detail about what you are doing when you see the problem? Is it only one screen that isn't showing up? Can you describe how it is connected and the make and model of the screen? And what type of video card do you have? Can you please see issue #5 for an example of the information you need to provide in order for me to be able to help you fix the problem you're experiencing. I need you to provide that level of information, and then I'll understand your issue more.
DisplayMagician is a complicated bit of code, and there are a lot of potential failure points, as there are hundreds of different video cards, display drivers, screens and similar. Without logs and good bug reports I can't actually fix bugs.
I will need to see a TRACE DisplayMagician.log file, and I need a copy of your Shortcuts_1.0.json file and your DisplayProfiles_1.0.json file as well in order to troubleshoot this.
You can create a TRACE DisplayMagician.log by opening a command prompt (press Ctrl + R, and type cmd and press enter), and running C:\Program Files\DisplayMagician\DisplayMagician --trace. This command will make DisplayMagician generate a DisplayMagician.log file in the C:\Users<yourusername>\AppData\Local\DisplayMagician\Logs folder. Please go there, open the DisplayMagician.log file and check that there are a lot of 'TRACE' log entries in the log file. If there aren't, then you'll need to try to run the command again to make DisplayMagician generate the DisplayMagician.log file.
The Shortcuts_1.0.json file will be in the C:\Users<yourusername>\AppData\Local\DisplayMagician\Shortcuts folder, and the DisplayProfiles_1.0.json file will be in the C:\Users<yourusername>\AppData\Local\DisplayMagician\Profiles folder. I'll need both of them in order to troubleshoot this.
Then please reply in this issue chain and attach the DisplayMagician.log, Shortcuts_1.0.json and DisplayProfiles_1.0.json files to the issue so that I can see them.
Thanks
Terry

**Comment by terrymacdonald** [comment]
Just a thought... it is possible that the monitors aren't sending the EDID information when DisplayMagician requests it. Some monitors don't always respond to the EDID request on time, and that is guaranteed to stop DisplayMagician from understanding what items are connected. People have issues with particular monitors, so that DisplayMagician works some of the time with them, and fails some of the time.

Maybe you can check the following:

- Keep recording which monitor DisplayMagician can't find (it should be in the logs). If its the same monitor each time then there may be an issue with that Monitor.
- When it happens, turn off the affected monitor and turn it back on, and see if that makes things work again
- IF that doesn't make it work. restart the computer and see if that makes it work again.
- If that doesn't, then shut down the computer completely so its powered off, then start the computer again, and try again. 
- If its always with the same monitor, then maybe try a different DisplayPort or HDMI cable just to check its not a problem with the cable (this one is a long shot)

All of those tests above need to be done in that order, and you'll need to record the outcomes of each step. With that information and the TRACE DisplayMagician.log file I mentioned earlier we should be able to work out what is happening.

Thanks
Terry

**Comment by Gonzz45** [comment]
Okay, thanks, if it doea it again i will follow these tests 
-------- Original message --------From: terrymacdonald ***@***.***> Date: 7/12/21  11:04 PM  (GMT-07:00) To: terrymacdonald/DisplayMagician ***@***.***> Cc: Gonzz45 ***@***.***>, Mention ***@***.***> Subject: Re: [terrymacdonald/DisplayMagician] Not all displays connected (#28) 
Just a thought... it is possible that the monitors aren't sending the EDID information when DisplayMagician requests it. Some monitors don't always respond to the EDID request on time, and that is guaranteed to stop DisplayMagician from understanding what items are connected. People have issues with particular monitors, so that DisplayMagician works some of the time with them, and fails some of the time.
Maybe you can check the following:

Keep recording which monitor DisplayMagician can't find (it should be in the logs). If its the same monitor each time then there may be an issue with that Monitor.
When it happens, turn off the affected monitor and turn it back on, and see if that makes things work again
IF that doesn't make it work. restart the computer and see if that makes it work again.
If that doesn't, then shut down the computer completely so its powered off, then start the computer again, and try again.
If its always with the same monitor, then maybe try a different DisplayPort or HDMI cable just to check its not a problem with the cable (this one is a long shot)

All of those tests above need to be done in that order, and you'll need to record the outcomes of each step. With that information and the TRACE DisplayMagician.log file I mentioned earlier we should be able to work out what is happening.
Thanks
Terry

**Comment by terrymacdonald** [comment]
@Gonzz45 I'll go ahead and close this issue for now, but if it does happen again, please reopen this issue so I know it's happened again.

**Comment by Gonzz45** [comment]
Okay, been working 3 days without the issue. Kinda wonder if it was an Nvidia update that messed it up. I know i had an update, but dont recall if it was before or after i setup display magician.
-------- Original message --------From: terrymacdonald ***@***.***> Date: 7/14/21  3:39 PM  (GMT-07:00) To: terrymacdonald/DisplayMagician ***@***.***> Cc: Gonzz45 ***@***.***>, Mention ***@***.***> Subject: Re: [terrymacdonald/DisplayMagician] Not all displays connected (#28) 
@Gonzz45 I'll go ahead and close this issue for now, but if it does happen again, please reopen this issue so I know it's happened again.

**Comment by terrymacdonald** [comment]
Oh, I wonder if NVIDIA fixed their driver. Some versions of the driver were
not reporting info correctly for the rtx2080 cards, and that meant that the
display identifiers weren't matching, which meant the display profiles
weren't usable. The fix was to recreate the display profiles again, and
that would recreate the display identifiers again using the latest driver
functions, which would make them match again.

If NVIDIA updated their driver to fix it, then everyone who had a problem
before would need to recreate their display profiles again (and change to
the new Display Profiles in their game shortcuts too) so that they work
with the new updated driver.

This unfortunately is an NVIDIA problem, not a DisplayMagician one (if this
is the problem you're having).

That could explain the problem you're seeing?

Hope everything stays working for you.

Terry

**Comment by Gonzz45** [comment]
Makes sense to me.Thank you for this software,  should advetise it in the DCSworld community. So far its the only one that worked after a month of searching. Only found yours because it was mentioned by another developer who wasnt able to keep up with his, so recerrex people to yours.
-------- Original message --------From: terrymacdonald ***@***.***> Date: 7/14/21  4:20 PM  (GMT-07:00) To: terrymacdonald/DisplayMagician ***@***.***> Cc: Gonzz45 ***@***.***>, Mention ***@***.***> Subject: Re: [terrymacdonald/DisplayMagician] Not all displays connected (#28) 

Oh, I wonder if NVIDIA fixed their driver. Some versions of the driver were

not reporting info correctly for the rtx2080 cards, and that meant that the

display identifiers weren't matching, which meant the display profiles

weren't usable. The fix was to recreate the display profiles again, and

that would recreate the display identifiers again using the latest driver

functions, which would make them match again.



If NVIDIA updated their driver to fix it, then everyone who had a problem

before would need to recreate their display profiles again (and change to

the new Display Profiles in their game shortcuts too) so that they work

with the new updated driver.



This unfortunately is an NVIDIA problem, not a DisplayMagician one (if this

is the problem you're having).



That could explain the problem you're seeing?



Hope everything stays working for you.



Terry
