### ISSUE TITLE
Shortcut keys

### ISSUE THREAD

**Issue by ganzoni** [terrymacdonald/DisplayMagician#288]
I have a new issue, my shortcuts are "CTRL (left) + ALT (left) + 1 (for 1 screen, 2 for 2 screens and 3 for 3 screens)".

But when i use "ALT GR (right) + 1 (2 or 3)" it change the settings????

<img width="223" alt="image" src="https://github.com/terrymacdonald/DisplayMagician/assets/31613494/8cdf5e81-de4f-48d5-8ca7-2ee89e9a9138">

The saved shortcut is CTRL + ALT + 3 
But when i press **ALT GR + 3** its like i press CTRL + ALT + 3 ???? Thats strange

**Comment by terrymacdonald** [comment]
@ganzoni Do you still have the same problem with v2.6.0.515?

**Comment by ganzoni** [comment]
Hi Terry,

No, with the new version it's ok 😉

You can close the bug.
________________________________
De : terrymacdonald ***@***.***>
Envoyé : jeudi 8 février 2024 22:21
À : terrymacdonald/DisplayMagician ***@***.***>
Cc : ganzoni ***@***.***>; Mention ***@***.***>
Objet : Re: [terrymacdonald/DisplayMagician] Shortcut keys (Issue #288)


@ganzoni<https://github.com/ganzoni> Do you still have the same problem with v2.6.0.515?

**Comment by terrymacdonald** [comment]
Excellent news. I'll close this issue then.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi!

This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here: 
 https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1

It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing. 

Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).

Thanks
Terry
