### ISSUE TITLE
AMS2 and the well known problem with quad screens configuration

### ISSUE THREAD

**Issue by thebaz** [terrymacdonald/DisplayMagician#290]
It is well known that AMS2 has problem to run the triple monitors configurations if 4 monitors are connected to the pc...

So I solved by creating a Display Profile where the 4th monitor is switched off before launching AMS2; I also had to select the option to monitor a different executable after the launch because if I am not doing it after the launch of AMS2 I loose the ability to stay on that configuration, the 4th monitor switches on and the game turn back to the main monitor and the triple screen option doesn't work...

I assigned a hotkey to every single Display Profile but it seems I cannot switch back to the 4 monitor profile until the game is running... Display Magician seems "stuck" until AMS2 is closed.

Is this a possible bug or there is nothing I can do and iis it the expected way it works?

Thanks

![image](https://github.com/terrymacdonald/DisplayMagician/assets/7090323/4b460635-e0c0-4146-a6af-c388d685dd6d)
[DisplayMagician-Support-20240208-2343.zip](https://github.com/terrymacdonald/DisplayMagician/files/14215421/DisplayMagician-Support-20240208-2343.zip)

**Comment by terrymacdonald** [comment]
Hi @thebaz. Yeah the AMS2 thing is mentioned in the wiki as I found exactly that myself: https://github.com/terrymacdonald/DisplayMagician/wiki/Main-Game-and-Application-Examples#automobilista-2

DisplayMagician is designed to cover the 95% of situations where you want to change the display layout before you run the game. It isn't designed to adjust the display setting after running the app.... with that said I think we can still give you the outcome you want, it just might be a 2 step process.

I suggest firstly saving a Display Profile Desktop Shortcut for the 4 screen layout, and save it to your desktop. We will use that later.

Next edit your AMS2 Game Shortcut to use your 3 screen Display Profile, and then go to the 'Choose what happens afterwards' tab and choose the 'Keep Using ...' options for the Display Profile, the microphone and audio output. Then save the Game Shortcut. Save a Game Shortcut Desktop Shortcut for the AMS2 Game and save it to your desktop.

Now, to start your game you need to do the following:

- Run the AMS2 Game Shortcut from your desktop. This will swap to the 3 screens and then will start AMS2 and then DisplayMagician should finish running (it shouldn't wait for the game to be closed).
- After AMS2 has started, Alt-Tab to your Desktop, and run the 4 screen Display Profile Desktop Shortcut. This will then get DisplayMagician to change the display layout to the four screens that you want.
- You should be able to Alt-Tab back to the game and everything should be set how you want it,

This process will have downsides though, as you will need to revert your Display Profile, Audio settings and microphone to whatever they were afterwards separately. But if you can do that then this may work!

Hope that helps
Terry

**Comment by thebaz** [comment]
Hello Terry,

This is exactly what I was used to do… but switching to desktop and
applying the 4-screen display profile doesn’t work…

Nothing happens if I’ve chosen to monitor a different executable… if I
haven’t, well it works but AMS won’t stay on 3 screens and stretches to
just one

Anyway… I can live with 3 when using AMS2 (which is not my favorite sim)

Luca

Il giorno ven 9 feb 2024 alle 04:18 terrymacdonald ***@***.***>
ha scritto:

**Comment by terrymacdonald** [comment]
Hi Luca,

Can you please explain a bit more about this part in your reply?

Nothing happens if I’ve chosen to monitor a different executable… if I haven’t,
well it works but AMS won’t stay on 3 screens and stretches to just one

Can you please explain that statement in more detail. I don't think I
understand what you mean.

You won't be able to monitor the executable as that will cause
DisplayMagician to wait until the exe had closed. I forgot that
DisplayMagician will still wait for the game to end in all situations, and
there is no way to disable that. Luckily AMS2 uses a launcher exe, which
does exit after it starts that 2nd exe, so it effectively should stop
DisplayMagician monitoring the first AMS2 run.

I have no idea why this then causes AMS2 to stretch to just a single screen
I'm afraid. I don't think I can help with that part sorry.

I'm not sure if there is anything else I can do.

Thanks
Terry

**Comment by thebaz** [comment]
Terry,

I perfectly understand what you mean... And I can understand you cannot do
more than what you already do... so, I am ok with this situation

**Comment by terrymacdonald** [comment]
@thebaz I might have a solution for you!

As far of fixing #223, I actually figured out a way to help you out. I've made a new separate console application called DisplayMagicianConsole.exe that allows you to interact with DisplayMagician Display Profiles from a script. This allows the following three commands:

- **DisplayMagiciancConsole.exe CurrentProfile**: This will show the name and UUID of the display profile in use
- **DisplayMagiciancConsole.exe AllProfiles**: This will show the name and UUID of all the available display profile that have been saved within DisplayMagician.
- **DisplayMagiciancConsole.exe ChangeProfile <ProfileName|UUID>**: This will change to the display profile with the Name or UUID provided by the user. If the Display Profile is valid to use right now then it will be  applied. You can re-apply the same profile that is in use now. If applying the display profile is not successful then you will be given an error message explaining what happened.

The idea is that you use the first two commands to figure out which Display Profile you want to use, and then use the last command to swap to it. 

I've made a special new test version of DIsplayMagician for you to try. Please give it a test and give me any feedback.

[DisplayMagicianSetup-v2.6.0.517-console.zip](https://github.com/terrymacdonald/DisplayMagician/files/14227722/DisplayMagicianSetup-v2.6.0.517-console.zip)

In your case I think you'll be able to use the **DisplayMagiciancConsole.exe ChangeProfile <ProfileName|UUID>** in a Powershell/Batch script to change to the display layouts you want. You would do something like this:
- Change to the triple screen display profile
- Start AMS2
- Add a delay to wait until AMS2 has started
- Change to the 4 screen AMS2 display profile

This will work as the ChangeProfile command just applies the display profile, and doesn't wait for a game or anything. This will let you do changes in the order that you want.

The one downside is that you won't be able to do this within DisplayMagician itself. You'll need to have AMS2 as a special powershell/batch script until they change their code to support starting with 4 screens (then you can try DM again!). Hopefully that works!

If you like what I do, then I'm open to [receiving donations](https://github.com/sponsors/terrymacdonald). I'm hoping to save up for an Intel Arc video card so that I can add some Intel Arc support to DisplayMagician.

Thanks
Terry

**Comment by thebaz** [comment]
What a great news! Thank you

I'll test for sure when back at home (in 4 days)

**Comment by thebaz** [comment]
The DisplayMagicianConsole.exe works as expected! It's great... now I have to understand the strange behaviours of AMS2 on my PC... When I switch on the 4th monitor, I miss the ability to use the triple monitor settings even if the game is launche with the 3 screens configuration...

**Comment by thebaz** [comment]
I probably had a problem on my 4 screen profile... I just updated it and now everything works as expected!

Very well done Terry!

**Comment by terrymacdonald** [comment]
Excellent news!

**Comment by thebaz** [comment]
I also implemented the bat file looking for the AMS process until it runs, wait some seconds and then switch the display profile… Just like a “magician” 😉

**Comment by terrymacdonald** [comment]
Brilliant! Could you please reply with the Bat file contents so that an
example is left in this issue that others can use in the future? Having an
example to show them how it's fine could help someone else.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Perfect thanks!
