### ISSUE TITLE
Do not apply profile if active

### ISSUE THREAD

**Issue by Starbuck1991** [terrymacdonald/DisplayMagician#297]
Currently, I use DisplayMagician to automate the launch of several programs simultaneously and close them automatically when I’m done. Sometimes, this process involves changing screen profiles (for instance, adjusting screen resolutions when using software like DaVinci Resolve). However, there are instances when the screen profile remains the same as the one I currently have active.

I believe it would be a valuable improvement if DisplayMagician could prevent the re-application of the active profile. This would help avoid unnecessary screen flickering and delays. While the problem is partially mitigated when I close the programs (thanks to an option that allows me to retain the current profile), having a similar option when opening the programs would be a welcome addition.

**Comment by terrymacdonald** [comment]
Hi,

DisplayMagician is coded to not apply a display profile change if the
current display layout matches the target display profile. It already
checks for this.

One important thing to realise though is that the display profile has to
match the current layout EXACTLY. Every setting needs to match. If there is
one single difference then the display layout are considered different, and
therefore the display profile is applied.

If NVIDIA or AMD introduces a new default setting into their driver (say
for a new feature they've added) then this means that the current display
layout will now be different from the saved display profile that previously
matched. The equality test that we perform will now think that the saved
display profile is different, and the logic will try applying the display
profile every time.

The fix to this is to 'update' the display profile with the current display
layout. In v2.5 and before you can't do this easily, but in v2.6.0
(currently under development) there is a new button that I added to do
exactly that.

DisplayMagician v2.6.0 is currently still being developed, but it seems
reasonably stable at the moment. I've attached the latest test version of
it so that you can download it and test it out.

If you find any problems with it please log another GitHub issue and we can
help troubleshoot it together.

Thanks
Terry

**Comment by Starbuck1991** [comment]
Hi!

Thank you for your response. Yes, it seems that updating the profile should resolve the issue.

I’m eager to test the new version and provide feedback. However, I noticed that there is no attachment in your message.

Best regards,

Joe

Sobre 28/02/2024 19:39:14, terrymacdonald ***@***.***> escribió:
Hi,

DisplayMagician is coded to not apply a display profile change if the
current display layout matches the target display profile. It already
checks for this.

One important thing to realise though is that the display profile has to
match the current layout EXACTLY. Every setting needs to match. If there is
one single difference then the display layout are considered different, and
therefore the display profile is applied.

If NVIDIA or AMD introduces a new default setting into their driver (say
for a new feature they've added) then this means that the current display
layout will now be different from the saved display profile that previously
matched. The equality test that we perform will now think that the saved
display profile is different, and the logic will try applying the display
profile every time.

The fix to this is to 'update' the display profile with the current display
layout. In v2.5 and before you can't do this easily, but in v2.6.0
(currently under development) there is a new button that I added to do
exactly that.

DisplayMagician v2.6.0 is currently still being developed, but it seems
reasonably stable at the moment. I've attached the latest test version of
it so that you can download it and test it out.

If you find any problems with it please log another GitHub issue and we can
help troubleshoot it together.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Starbuck1991 Try this one and see if it works. 
[DisplayMagicianSetup-v2.6.0.524-devicemode-fields.zip](https://github.com/terrymacdonald/DisplayMagician/files/14440306/DisplayMagicianSetup-v2.6.0.524-devicemode-fields.zip)

If it does please come back here and close your Github issue so I know I don't need to work on this any more. 

Thanks
Terry

**Comment by Starbuck1991** [comment]
Yes, it did the trick.
The option to update a profile is a very welcome addition.
Thank you so much for your help! I’ll go ahead and close the issue.

Sobre 28/02/2024 23:00:59, terrymacdonald ***@***.***> escribió:
@Starbuck1991 [https://github.com/Starbuck1991] Try this one and see if it works.
DisplayMagicianSetup-v2.6.0.524-devicemode-fields.zip [https://github.com/terrymacdonald/DisplayMagician/files/14440306/DisplayMagicianSetup-v2.6.0.524-devicemode-fields.zip]
If it does please come back here and close your Github issue so I know I don't need to work on this any more.
Thanks
Terry

**Comment by Starbuck1991** [comment]
Hi!

I've been testing this version since its publication, and so far so good.
