### ISSUE TITLE
BSOD when switching profiles

### ISSUE THREAD

**Issue by BladeZ80** [terrymacdonald/DisplayMagician#298]
Hi there,

Up until a few days ago, I had no issues with my profiles. Now, when I switch between them, the PC will give me a BSOD and restart with no changes.

I have 2 sets of profiles. 1 for switching between single and triple monitors, and the other set for the same process but also loading an appropriate game.

Either set will cause the BSOD when used and yes, nvidia surround is enabled. I tried deleting and making new profiles but the problem still exists.

I have attached a .zip file from the last crash. 

Thank you for any help as I love using this software for my setup.
[DisplayMagician-Support-20240302-1716.zip](https://github.com/terrymacdonald/DisplayMagician/files/14470217/DisplayMagician-Support-20240302-1716.zip)

**Comment by terrymacdonald** [comment]
Hi,

Had anything changed in your machine since last time? Have you got a new
video card? New display monitors? Installed a new NVIDIA driver? Updated
windows from windows 10 to 11?

If you have then one of the above could be the cause of the issue. If not,
then it could be a bug in the DisplayMagician configuration files.

One thing you can do is to test the v2.6.0 installer that I've been working
on. It has a lot of bugfixes built into it, and it works in a slightly
different way that uses all the video libraries at once rather than
choosing NVIDIA mode or AMD mode or windows mode.

You can get the latest test version of DisplayMagician v2.7.0 from here:
https://github.com/terrymacdonald/DisplayMagician/issues/297#issuecomment-1970837562

Give that a go and then let me know what happens.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@BladeZ80  looking at your config, this is a bit odd:

```
"MosaicConfig": {
        "IsMosaicEnabled": false,
        "MosaicTopologyBrief": {
          "Version": 65552,
          "Topo": 3,
          "Enabled": 0,
```

Your NVSurround profile doesn't have the `"IsMosaicEnabled": true,` , and instead has it set to false. This should be true if it was an NVIDIA surround profile.

It could be that causing the BSOD. I'd recommend deleting that NVSurround profile, and then get into NVIDIA Settings and recreate the NVIDIA Surround layout, and then wait 15 seconds for everything to settle down, and then save it again in a new Display Profile in DisplayMagician.

This will hopefully fix the issue. Please report back here if it does or not.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@BladeZ80 is everything working ok now? If I don't hear back from you shortly I'll have to assume that the above suggestion worked and now everything is working again. If not, please feel free to reopen this issue.

**Comment by BladeZ80** [comment]
I did manage to get it working again but haven't used it for a little while because of irl issues. Thank you for the help with it though.

Kind Regards
Darren Brownlee
________________________________

**Comment by BladeZ80** [comment]
It may be a while before I get to try it as currently on a single monitor due to wanting to upgrade but will try as soon as I can.

Kind Regards
Darren Brownlee
________________________________
