### ISSUE TITLE
Doesnt work with sli?

### ISSUE THREAD

**Issue by jaydonchantre** [terrymacdonald/DisplayMagician#319]
i fully read through all old versions and they said they where adding sli support but i dont think that works yet?

atleast when i press a hotkey or apply a profile nothing happens?

**Comment by jaydonchantre** [comment]
o welp never mind your beta download i found somewhere just instantly works lol maybe you should bring that one out soon

**Comment by terrymacdonald** [comment]
ok I'll close this now. Be warned though that it is likely to not work when v2.6.0 is released. You will probably need to wait until v2.7.0 is released before my new NVIDIALibrary is released as I think that's the functionality that should work with SLI configs. I don't have SLI and I don't know anyone else who has it, so there is no way I can test it.

Also, I cannot just ship partially working software. There is a lot of testing and coding that goes into a release, so it's not something you I can rush. I have over 13,000 users now, so I cannot rush any changes out any more. They all need to be released when they're ready.

As your issue is now fixed, I will close your issue, as this is fixed in the codebase.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi!

This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here: 
 https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1

It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing. 

Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).

Thanks
Terry

**Comment by jaydonchantre** [comment]
Hello I already fixed it with a beta version of your software some time ago (probably basically your new version you got?)But sold my sli setBut still thanks for respondingGreetingsJaydon ChantreOn Oct 3, 2024 11:46 AM, terrymacdonald ***@***.***> wrote:
Hi!
This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here:
https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1
It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing.
Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).
Thanks
Terry
