### ISSUE TITLE
Virtual display only - error on saving profile

### ISSUE THREAD

**Issue by hassanhabbak** [terrymacdonald/DisplayMagician#328]
When trying to save a profile with only a virtual display, the app throws an error and does not save the profile. 

Any workarounds for that?

**Comment by terrymacdonald** [comment]
Hi,

I'll need waaaay more information than that I'm afraid of I'm going to find
out what's going on.

First step, can you please tell me which version of DisplayMagician you are
using?

Next, please tell me what sorry of video card, screens, dongles and cable
types that you're used to connect everything together hardware-wise.

After that, please run DisplayMagician and go into settings, and set the
logging level to Trace.

Next, try to save the profile again to make DisplayMagician crash. We want
to try and force the bug to occur, so that it will be captured in the log
files.

Lastly, start DisplayMagician again, and go back into settings. Click on
the 'Create Support Zip file' button, and save the zip file it creates
somewhere.

Come back to GitHub in your web browser, and upload the zip file you just
created. That should give me enough information to have a better
understanding of what error you found.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi!

This may be fixed by the brand new version of DisplayMagician I just released. I would suggest that you try to the new DisplayMagician v2.7.0-alpha.1 test build available here: 
 https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.7.0-alpha.1

It should fix your problem, but it may also cause other problems instead. This version has had a complete backend change, new installer, new features, and so it may have some bugs that need squashing. 

Please test it out. and if you find any new problems please log a new issue. If it fixes this issue then please update this issue to tell me and then close this issue (it helps me keep track of what I've still got to fix).

Thanks
Terry

**Comment by terrymacdonald** [comment]
@hassanhabbak As I've not received any more information like logs in a Support ZIP File, I'm going to have to close this case for now. Please feel free to respond to this issue and I will reopen it if needed.

Thanks
Terry
