### ISSUE TITLE
Unable to switch profiles since v2.7.2.1

### ISSUE THREAD

**Issue by colinator19** [terrymacdonald/DisplayMagician#340]
**Describe the bug**
I am unable to switch to any profile. Since the latest update, I am having troubles with my profiles as they do not switch any more. Even when removing all profiles, recreating them, reinstalling the software does not seem to work.

When setting up the profiles, I can configure the screens as I would like via Windows or AMD software, then save the profile. The profile will always have an exclamation mark after saving. There is a small message on the top stated "This display profile can't be used as not all displays are connected" - Which is weird since the profile I just saved, is for the screen I am looking at and is active...

This issue occurs with any display I have connected to my system in any configuration (extended, single screen, duplicate screens)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open DisplayMagician
2. Click on 'Display Profiles'
3. Set monitor configuration as preferred
4. Save the profile with a custom name
5. Profile is saved however exclamation mark is shown. 
6. Unable to switch profiles.

**Expected behaviour**
Able to switch to the saved profiles without the error about the displays not being connected.

**Screenshots**
<img width="550" alt="image" src="https://github.com/user-attachments/assets/ad361c6c-4648-4edb-94b3-16454278cf40">

**Reporting Logs**
[DisplayMagician-Support-20241026-1316.zip](https://github.com/user-attachments/files/17530725/DisplayMagician-Support-20241026-1316.zip)

**Enviroment (please complete the following information):**
 - Windows Version: Windows 11 23H2
 - DisplayMagician Version: 2.7.2.1
 - Video Card: AMD Radeon RX 7900 XTX
 - Number and make/model of monitors: 1x Gigabyte M28U + LG Ultragear 49GR85DC-B
 - Date of last video driver update: 24.8.1
 - Date of last windows update: 26-10-2024

**Additional context**
The issue started with the latest update of DisplayMagician I performed. The previous version was working fine.
Manually switching the monitors via Windows or AMD software works fine.

**Comment by colinator19** [comment]
Noticed there was an update for the AMD drivers, after installation it is working again :-)
For reference, the now installed version of the AMD drivers is 24.10.1.

**Comment by terrymacdonald** [comment]
Oh cool! Nice work on finding the fix!

I was getting a bit worried as I don't have an AMD video card that I can
test with, so I'd have to remotely debug any AMD errors... which is very
difficult to do.

Thanks
Terry

**Comment by Wob76** [comment]
I have noticed this issue, it's not fully resolved, it seems to be an order of install thing. And the version of AMD installed at the time of the install of DM just never seems to work with that version. I have rolled versions of AMD back 2 revisions and they will work, roll to the version that was installed when DM and it doesn't work, next release then seems to fix it again.

It is odd, It always has the "Not All Displays are Connected error".

If I don't touch the profiles after installing DM, I can switch to them fine, and they show no errors, but it doesn't detect the current profile as matching any of the saved ones, so that breaks any shortcuts as they don't detect the display profile as loading.

**Comment by terrymacdonald** [comment]
Hopefully the new 'Update' button available in v2.7.2 helps fix this, as
you can perform the following steps to fix this:

   - apply the display profile that is not being detected by clicking the
   Apply button
   - check that the layout of how you want the displays laid out is
   correctly (i.e. check in the AMD software)
   - Change to the display profile that you want to overwrite and then
   click the Update button to overwrite the old display profile settings with
   the current display profile settings.

To test if this has worked and fixed the current display profile matching,
click on a different display profile to change the UI, then click on the
'View Current Display' button, and see if it matches the display profile
you just overwrote. If it does, then it worked!

Hope that helps
Terry

**Comment by Wob76** [comment]
Thanks for the tips, unfortunately this doesn't work.

I just did a test here on my "2 Screens" profile, prior to the steps you list I was able to apply this profile, but it would not detect as being active using the "View Current Display".

After following those steps, it does detect as being the active profile, but it now has a Error "This Display Profile can't be used as not all Displays are connected", this means that I can no longer apply it.

Just a note that the AMD Software (Adrenalin) does not offer a layout tool, it does show the connected displays and a button to "Arrange Displays" but this takes you to the Windows System > Display options.

Let me know if I can do any further debugging

![image](https://github.com/user-attachments/assets/0d06cb60-80e5-4d8c-a9c1-6effb697eefc)

![image](https://github.com/user-attachments/assets/c4d91c75-1357-4ec0-a4a2-29a2c84f04cb)

**Comment by terrymacdonald** [comment]
What happens if you create a completely new display profile, and then click
on the "View current display" button?

Once you've done that testing, can you please also go into the Settings
from the main form (the one that loads first) and then click on the 'Create
Support ZIP File' to generate a ZIP file containing the logs? Save the ZIP
file, and then using your web browser upload the ZIP file to the issue. I
will then take a look at what I can see.

I don't have a separate AMD GPU, so that will reduce the amount of testing
and debugging I'll be able to do I'm afraid. We shall see what the logs
tell us.

I will separate this problem off to a new issue as I think it's different
enough that we need to track it separately.

Thanks
*Terry*

**Comment by Wob76** [comment]
The Profile creates fine, and it does detect it as being the "Current Display Profile" but it still reports that not all displays are connected.

Support Zip attached.

If it doesn't supply enough details I can try rolling back the AMD Drivers and running through the same steps, as that has "fixed" it in past, then I just wait for the next release, it always just seems to be an issue with the AMD version that is installed when I update DM.

![image](https://github.com/user-attachments/assets/f0c4536d-9ac0-49ad-b518-9dfbac6392d4)

[DisplayMagician-Support-20241029-0256.zip](https://github.com/user-attachments/files/17551011/DisplayMagician-Support-20241029-0256.zip)

**Comment by terrymacdonald** [comment]
DisplayMagician works by requesting settings from the AMD driver via their
ADL API. If AMD change settings and provide additional options, then the
option returned may either:

   - Not be available within DisplayMagician
   - The DM Display Profile won't match the option returned from the driver.

My gut feel is that the last option is what is affecting you.

It's been a while since I went through the AMD ADL driver files to figure
out what has changed. There may be some internal AMD driver changes that
haven't been backported to the ADL functions that DM uses, so I may need to
update my custom AMDLibrary to use those newer functions. I was planning on
doing the same for NVIDIALibrary anyway as I want to make updating the
Video Libraries the core focus of DisplayMagician v2.8.0. That could easily
be 6 months of work, but I'm interested in doing some testing for it.

I think I'll make this a new issue, and then that should enable me to link
that issue to the v2.8.0 milestone in github to track it accurately.

@Wob76 I'll probably need your help with some testing of a couple of
command line programmes called 'AMDInfo' and 'VideoInfo' that I've created
specifically to test the Video Libraries to make sure they work. Once we
get those working reliably they will be added back into DM and will become
v2.8.0.

Thanks
*Terry *

**Comment by Wob76** [comment]
Happy to complete any testing, just message me direct or @ me in the new issue.

As I mentioned on the previous Alpha I rolled back from 24.9.1 -> 24.8.1 to fix the issue, then upgraded to 24.10.1 and it was working fine till I upgraded DM.

I thought I would test again rolling back to 24.9.1 for the AMD Software, it again restored function for me in DM. I then installed 24.10.1 expecting it to remain the same (as it did on the previous alpha) but installing 24.10.1 crashed my system and I had to power cycle (I hadn't done any reboots between installs), when I go back in no AMD drivers where showing, installed 24.10.1 and everything is working.

**Comment by terrymacdonald** [comment]
When you say everything is working now, do you mean that the
DisplayMagician 'View Current Display' button works now? Or were you just
meaning that the AMD drivers are working again?

Thanks
*Terry *

**Comment by Wob76** [comment]
DM is working as expected. 'View Current Display' works as does the Update and Create.

So it appears that the crash that caused me to do a fresh install of the AMD drivers resolved the issue. Did you want a fresh support zip?

**Comment by terrymacdonald** [comment]
Yes please.

Based on your testing, my best guess is that the driver install needed a
reboot. Sometimes, depending on what driver components are changed, the
computer needs to be rebooted/restarted in order to properly load the new
DLLs/driver logic. It may be that this update caused something like this.

I think that was the underlying cause in the case you were experiencing
based on what you've described to me. I'm happy enough that your issue is
fixed, but I will reach out to you for some testing help once I start
working on the next version of DisplayMagician.

Thanks
*Terry *

**Comment by Wob76** [comment]
I usually do reboots between installs of drivers, particularly reinstalling the same one with different versions, just being lazy today :)

In the previous tests I did restart between reinstalls, no crashes and the issue as noted (never working with version installed when DM was updated) but the crash obviously refreshed something, logs might not help with that being it is outside DM, but can't help to have a working set of button presses.

Happy to run through testing when the time comes.

[DisplayMagician-Support-20241029-0559.zip](https://github.com/user-attachments/files/17552211/DisplayMagician-Support-20241029-0559.zip)

**Comment by terrymacdonald** [comment]
Thanks for all your help testing so far. All of these sorts of issues are
useful as we can often find edge cards that are difficult to find
otherwise.

I'll check through the support zip files over the weekend and get back to
you.

Thanks
Terry
