### ISSUE TITLE
Error while opening Game Shortcuts

### ISSUE THREAD

**Issue by Cardistymo** [terrymacdonald/DisplayMagician#35]
I tried to reinstall DisplayMagician but if I open Game Shortcuts, following error occurs:

https://pastebin.com/h4nkYYPa

**Comment by terrymacdonald** [comment]
Hi @Cardistymo 

I I will need the logs in order to troubleshoot this. This is an unusual error and one I've not seen before.

I will need to see a TRACE DisplayMagician.log file, and I need a copy of your Shortcuts_1.0.json file and your DisplayProfiles_1.0.json file in order to troubleshoot this.

You can create a TRACE DisplayMagician.log by opening a command prompt, and running "C:\Program Files\DisplayMagician\DisplayMagician --trace". This command will make DisplayMagician generate a DisplayMagician.log file in the C:\Users<yourusername>\AppData\Local\DisplayMagician\Logs folder. Please go there, open the DisplayMagician.log file and check that there are a lot of 'TRACE' log entries in the log file. If there aren't, then you'll need to try to run the command again to make DisplayMagician generate the DisplayMagician.log file.

The Shortcuts_1.0.json file will be in the C:\Users<yourusername>\AppData\Local\DisplayMagician\Shortcuts folder, and the DisplayProfiles_1.0.json file will be in the C:\Users<yourusername>\AppData\Local\DisplayMagician\Profiles folder. I'll need both of them in order to troubleshoot this.

Please attach all 3 files to this issue. You can simply drag the files over this issue in your web browser and it will start to be uploaded. 

I'll take a look and see what I can find.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Just an FYI, I'll close this issue after 4 weeks without any response, just to keep the issue log clear for new issues. That's two weeks from now.

Feel free to reopen after this time if you need.

**Comment by terrymacdonald** [comment]
Closing due to no response from issue creator.
