### ISSUE TITLE
Games outside of C:\ drive, non-Steam, not showing as options

### ISSUE THREAD

**Issue by DragRedSim** [terrymacdonald/DisplayMagician#38]
**Describe the bug**
I have five different Steam Library folders across different drives; however, only the content of the C:\ drive one (where Steam is installed) shows up when trying to create a shortcut.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have multiple Steam libraries, with the information on them stored in SteamPath\steamapps\libraryfolders.vdf
2. Click on Game Shortcuts, then New
3. Select Choose game to start
4. See lack of installed games, and those that are there have no image.

**Expected behaviour**
I have 813 games installed according to Steam, yet only the eight installed on the C: drive show up. Also, all other libraries installed (Origin, Uplay, etc.) are missing all games - it can be seen that the library plugins are attempting to load them.

**Screenshots**
![image](https://user-images.githubusercontent.com/5095074/132092742-f51b7590-e07e-420b-9a74-078d5fd0dea1.png)

**Reporting Logs**
- Create a TRACE-level DisplayMagician.log file by running `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` in a command prompt.
- The above command will create a DisplayMagician.log file in `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Logs` which should contain a LOT of detailed TRACE level log entries. 
- Feel free to check the DisplayMagician.log file for any information you might not want to share with the public. 
- Once you're happy, attach the DisplayMagician.log TRACE file you just created to this issue.
[Logs.zip](https://github.com/terrymacdonald/DisplayMagician/files/7109680/Logs.zip)

**Enviroment (please complete the following information):**
 - Windows Version: 10
 - DisplayMagician Version: 1.1.4.0

**Additional context**
Attached is my libraryfolders.vdf, to provide an example of the format.
[libraryfolders.zip](https://github.com/terrymacdonald/DisplayMagician/files/7109676/libraryfolders.zip)

I did have a quick attempt at trying to rewrite the SteamLibrary.cs file to also search the libraryfolders.vdf, but ran into some issues.

**Comment by terrymacdonald** [comment]
Hi,

I'll take a look over the next few days.

An important point to note is that DisplayMagician deliberately only shows
your installed games on the computer you're using, and those installed
games must have been played in order to appear in the list. This is for to
the way that Steam was working at the time the code was developed.

I also have Steam games installed across multiple drives with games
installed in each Steam library in each drive, and all my installed games
are currently being shown correctly (at least they were last night). I'll
check again tonight to be sure. I'm very interested in how that contrasts
with your set up.

Thanks for logging the issue. I'll have a proper read when I get time this
evening.

Thanks
Terry

**Comment by DragRedSim** [comment]
Yep, I get that the games must be local to the PC in question (not much point trying to deal with it for streaming) and I certainly have played more than showed up in Steam, though this may answer some of the questions regarding other launcher libraries.

I think the main issue is in regards to the library folders settings not being stored (for me) inside the config.vdf, but rather in its own separate file (libraryfolders.vdf), which the current SteamLibrary.cs does not even consider. I have had another account previously log in on the same PC in order to authorise family sharing, and given the user-specific nature of the contents of config.vdf, this may have induced the movement of that configuration out to a non-user-specific file. 

Having searched a few of these terms, I came across an interesting post (https://github.com/LostDragonist/steam-library-setup-tool/issues/8), that suggests further work may become required soon anyway. I am not currently in the Steam client beta, but have been in the past. The build date of my current version is July 20, according to the About page. This may also help explain some of the configuration differences, but may also be a red herring in that regard. 

David

**Comment by terrymacdonald** [comment]
Hmmm. Very interesting indeed. Thanks for the research, I'm going to have to do some deeper reading and testing on my own PC. 

TBH I've never really liked the games parsing part of DisplayMagician. It's always felt a bit too brittle, but it's weirdly been the most reliable bit of the software so far! These changes were always going to turn up sometime, but I was hoping that they'd happen AFTER I shipped DisplayMagician v2.0.0. There are some major changes coming in that new version of DisplayMagician that will make display profile changes much more reliable, and make DM record a LOT more information about the display configurations. It's also adding AMD Eyefinity support. 

I'll do a deep dive over the next week to see what I can find. I purposely move games into multiple drives and multiple libraries in each of the game libraries I support so that I could find where the information about them was stored, so I could properly support as effectively as possible, so it's a tad annoying to find out the info might have moved :).

I've got the same Jul 20 steam client, that at least helps. When was your Steam client last reinstalled? Did you move from another  PC to the one you're using now recently? I've had my Steam library for ages, and I wonder if it could be a newer feature for newer games? Actually, I might go buy a new game too, to see if it turns up in DM... something so I can find the pattern. 

Thanks for the file, the heads up and the additional info! It's all useful stuff.

Terry

**Comment by terrymacdonald** [comment]
FYI, fix was pretty easy to add. I've added it into DisplayMagician v2.0.0 codebase for now as that will be the next release I do. Should be within the next 2-3 weeks all things going well!

Thanks for your awesome help on this! 

Thanks
Terry

**Comment by terrymacdonald** [comment]
Just an update to add. The logic I recently created for this was slightly flawed, and additionally Steam appears to have updated the libraryfolders.vdf file structure from when I did my testing.

The upshot is that I had to redesign this parsing code, and it now uses a combination of the library folders.vdf and original config.vdf, and combines the library locations together into a list of places to check. 

This means that DisplayMagician will support old installs of steam, as well as new installs of steam equally well!

I'm closing this issue as its been integrated into DisplayMagician V2.0.0, and will be released when the next version is ready to go.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Great news! DisplayMagician v2.0.1 has been released, and it should fix this very issue. Please test it out, and if you still have any issues please log a new issue. You can get DisplayMagician v2.0.1 from here: https://github.com/terrymacdonald/DisplayMagician/releases/tag/v2.0.1

I'm closing this issue as the fix is in DisplayMagician v2.0.1, and I need to clear out the completed issues so I am able to work on the new issues that come in.

Thanks
Terry

**Comment by DragRedSim** [comment]
Well, good news and bad news. The good news is that all the Steam games show up now! The bad news is that other library games don't show up, nor do they have icons. I'm going to try a debug build shortly to see where it's falling over.

**Comment by terrymacdonald** [comment]
Darn. It all worked on my test computer, so I'll have to do some more
looking around. Can you please change the logging level in settings to
Application trace logging, and then restart DisplayMagician? Then try to
create a new shortcut. Close down DisplayMagician, and then visit this
issue in your web browser and attach  the DisplayMagician.log file
(replying to this email with the log file won't work).

I'll take a look at it later tomorrow.

Thanks
Terry

**Comment by DragRedSim** [comment]
Here's the latest trace - [DisplayMagician.zip](https://github.com/terrymacdonald/DisplayMagician/files/7273458/DisplayMagician.zip). Some notes I made:
Key line: `2021-10-04 01:00:35.2052|WARN|DisplayMagician.UIForms.GameAdaptor|GameAdapter/GetThumbnail: Exception caused while trying to get the Game Bitmap.`

There's nothing installed in GOG at the moment, so no issues there.
The function on the line https://github.com/terrymacdonald/DisplayMagician/blob/main/DisplayMagician/GameLibraries/OriginLibrary.cs#L440 isn't working correctly. A trace output gives the following:
`2021-10-03 21:08:51.7955|TRACE|DisplayMagician.GameLibraries.OriginLibrary|OriginLibrary/LoadInstalledGames: Found .mfst files in Local Content Directory C:\ProgramData\Origin\LocalContent: System.String[]`
Some of the Origin games use a different XML format for their installerdata.xml. I've included the file for Battlefield 1942 for reference. (not that this is necessarily a game I was wanting to use DM for, just the first one with a suitable example) I've also included the installerdata.xml from NFS Rivals, since that uses a manifestVersion of 3.0.
Some Origin games have their manifests point to the Registry for launcher locations; however, for some games, there is no entry in the 64-bit registry, but it is stored in the WOW6432Node version. I believe this may have been caused by installing via Origin, and not the EA app, a long time ago, when it was only a 32-bit application.

Side note: it would be handy to be able to filter the list when creating a shortcut, or at least to be able to select by typing the game name.

**Comment by terrymacdonald** [comment]
@DragRedSim please add yourself as a watcher to the new issue I've created (#43). We'll start tracking this origin parsing problem under that new issue. 

I'll have time to look at that later this evening. Thanks so much for all the hard work you've been putting in to track down the issue. I really appreciate it. It makes my job a while lot easier!

Thanks
Terry

**Comment by terrymacdonald** [comment]
@DragRedSim I've created that new issue #43, and I've created a new test build for you in that issue. Please read the issue here: https://github.com/terrymacdonald/DisplayMagician/issues/43#issuecomment-933322899

The test build above **should** now work for v3.0 manifest files, but I'll need you to do some sleuthing for me in order to support v2.1 manifest files. Turns out the v2.1 manifest files don't contain a link to the game exe.... so I need you to hunt around and see where else the game exe data exists. Please see that commen linked above for more info, and please reply within that other issue #43.

Thanks
Terry
