### ISSUE TITLE
2.0.1 does not start. Log indicates missing AMD driver

### ISSUE THREAD

**Issue by sneakingJ** [terrymacdonald/DisplayMagician#47]
I'm gonna create a new ticket since the other one was closed but basically I have the exact same problem as https://github.com/terrymacdonald/DisplayMagician/issues/42.

I installed v2.0.1 a few days ago and did not manage to start it up yet. The DisplayMagician.log file states the following:
`2021-10-07 19:39:50.7491|INFO|DisplayMagician.Program|Starting DisplayMagician v2.0.1.59
2021-10-07 19:39:50.8676|INFO|DisplayMagician.Program|AMDLibrary/AMDLibrary: Exception trying to load the AMD ADL DLL atiadlxx.dll. This generally means you don't have the AMD ADL driver installed.
`

Multiple PC restarts did not change anything. I am using Windows 10 and have an Intel processor and a Nvidia GPU.
If you need anything else, let me know.

**Comment by terrymacdonald** [comment]
Hi @sneakingJ ,

That error is expected and part of how the AMD driver detection works. It's not the cause of the failure to start. Something else is the cause of that.

In order to troubleshoot your issue I'll need you to generate a TRACE level log file. In order to do that, you'll need to start DisplayMagician from the command line with an extra `--trace` option added.

To do this:

* Press Windows key + R to open a run prompt
* Type `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` and press the Run button
* DisplayMagician will run, and will write extra TRACE level log to the log file.
*  Open up Windows Explorer, and go to `C:\Users\<username>\AppData\Local\DisplayMagician\ folder.
* Create a reply to this message at Github.com in your web browser
* Attach the following files to your Github.com reply (if the files exist):
  * Settings_2.0.json
  * Profiles\DisplayProfiles_2.0.json
  * DisplayMagician.log
* Send me your GitHub.com reply with the files attached to it.

That should give me enough information to be able to troubleshoot your issue.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sneakingJ  Lastly, I just noticed a bit of oddness in your cfg files.... they may indicate something weird but also may not.

The Mosaic Refresh rate thinks it's 144Hz (that's the NVIDIA Surround refresh rate):

```
"MosaicDisplaySettings": {
        "Version": 131096,
        "Width": 1920,
        "Height": 1080,
        "Bpp": 32,
        "Freq": 144,
        "Rrx1k": 0
      },
```

Whereas the Windows section of the cfg file thinks your screen is refresh rate of 70Hz (70000/1000=70):

```
"VSyncFreq": {
              "Numerator": 70000,
              "Denominator": 1000
            },
```

IIRC the NVIDIA NVAPI mosaic settings only returns the refresh rate of the primary monitor, so it may just be a red herring. My personal mosaic settings line up closer to the windows ones, as I have 59.551HZ for Windows, and 60Hz for Mosaic in my NVIDIA Surround profile.

As I said, it may be nothing, or it may be something. I'll need the results of your testing and your answers to my previous questions before I'll be able to confirm if this is an anomaly or not.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sneakingJ Hmmmm. I can't think of a good reason why it would delay so long on startup.. unless.... How many games do you have installed on your PC from Steam/Origin/Uplay/Gog/etc ? DisplayMagician loads the games in a parallel task on startup, so if you have a lot of games it could delay loading.

If you have a lot of games installed (DM only looks for those installed on the SDD/HDD) that could be part of the delay issue. If that's the case I might build a popup for that.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sneakingJ I'm completely at a loss now! This is by far the strangest issue I've had so far. 

The log file you uploaded was a TRACE log file so that's good. The log file though is very odd. The log file is completely out of the normal processing order. It's like the main UI thread was delayed in someway, and then other threads are running and completing before the UI thread can run. I've never seen this before!

There is a really odd error too: 

```
2021-10-10 08:52:03.2174|INFO|DisplayMagician.Program|Program/LoadGamesInBackground: Loaded all Installed Steam Games (found 18)
2021-10-10 08:52:03.2174|ERROR|DisplayMagician.Program|Program/LoadGamesInBackground exception during loadGamesActions
```

Comparing all the libraries, it looks like all Epic (3 games), Gog (3 games), Origin (0 games), Steam (18 games) were loaded, but there weren't any Uplay 'Loaded all Installed Uplay Games' messages there.  Looking at what Uplay messages are in the log files does point towards that being potentially part of the problem:

```
Line 25: 2021-10-10 08:52:01.8592|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Game Installs Registry Key = HKLM\SOFTWARE\WOW6432Node\Ubisoft\Launcher\Installs
	Line 26: 2021-10-10 08:52:01.8592|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found uplayGameKeyName = 46
	Line 27: 2021-10-10 08:52:01.8592|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: uplayGameKeyName is an int, so trying to see if it is a game
	Line 28: 2021-10-10 08:52:01.8592|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ubisoft\Launcher\Installs\46 contains an 'InstallDir' value so is an installed Uplay Game.
	Line 29: 2021-10-10 08:52:01.8592|INFO|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found 1 installed games in the Uplay library
	Line 30: 2021-10-10 08:52:01.8592|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Config File Path = C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\cache\configuration\configurations
	Line 43: 2021-10-10 08:52:01.8732|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Entry that starts with 'version: 2.0') = rsion: 2.0
	Line 145: 2021-10-10 08:52:01.8732|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Entry that starts with 'version: 2.0') = 
	Line 393: 2021-10-10 08:52:01.8732|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Entry that starts with 'version: 2.0') = 
	Line 436: 2021-10-10 08:52:01.8732|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Entry that starts with 'version: 2.0') = 
	Line 493: 2021-10-10 08:52:01.8891|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found uplayGameAppInfo.GameName = World In Conflict
	Line 500: 2021-10-10 08:52:01.8891|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found uplayGameAppInfo.GameUplayIconPath = C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\data\games\f7a87a33187d2f2d9ddcef87f8184c69.ico
	Line 501: 2021-10-10 08:52:01.8891|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found gameFileName = wic.exe
	Line 2828: 2021-10-10 08:52:03.2174|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Game Installs Registry Key = HKLM\SOFTWARE\WOW6432Node\Ubisoft\Launcher\Installs
	Line 2829: 2021-10-10 08:52:03.2174|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found uplayGameKeyName = 46
	Line 2830: 2021-10-10 08:52:03.2174|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: uplayGameKeyName is an int, so trying to see if it is a game
	Line 2831: 2021-10-10 08:52:03.2174|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ubisoft\Launcher\Installs\46 contains an 'InstallDir' value so is an installed Uplay Game.
	Line 2832: 2021-10-10 08:52:03.2174|INFO|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found 1 installed games in the Uplay library
	Line 2833: 2021-10-10 08:52:03.2174|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Config File Path = C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\cache\configuration\configurations
	Line 2834: 2021-10-10 08:52:03.2373|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Entry that starts with 'version: 2.0') = rsion: 2.0
	Line 2936: 2021-10-10 08:52:03.2373|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Entry that starts with 'version: 2.0') = 
	Line 3184: 2021-10-10 08:52:03.2373|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Entry that starts with 'version: 2.0') = 
	Line 3227: 2021-10-10 08:52:03.2373|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Uplay Entry that starts with 'version: 2.0') = 
	Line 3284: 2021-10-10 08:52:03.2373|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found uplayGameAppInfo.GameName = World In Conflict
	Line 3285: 2021-10-10 08:52:03.2373|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found uplayGameAppInfo.GameUplayIconPath = C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\data\games\f7a87a33187d2f2d9ddcef87f8184c69.ico
	Line 3286: 2021-10-10 08:52:03.2373|TRACE|DisplayMagician.GameLibraries.UplayLibrary|UplayLibrary/LoadInstalledGames: Found gameFileName = wic.exe
```

It looks from that log file above that Uplay is processing the same game twice! If it's processing that line twice, it is possible that the Uplay library **never** actually finishes processing that game, and instead, it times out or produce an exception, causing the 'exception during loadGamesActions' error I mentioned earlier.

I'm going to do some testing with my own Uplay library over the next few days, and then I'll iron out any bugs I find in the Uplay code. I'm still not 100% convinced this is the underlying problem, but I'll see what I find.

Thanks for the log file though! It's been very useful indeed.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Woah! Good find!

I've never tried cloned displays ever. Never thought about supporting them
at all. The concept for DisplayMagician was always simplifying display
layouts for games, so cloned displays were never part of that.

I wonder if it's something that might work with the new video libraries
once I've completed the device context extensions I need to add to support
different screen refresh rates and colour settings?

I'll have to do some testing, but I need to say up front that there is no
guarantee that I'll be able to support cloned displays. I'll take a look
and hopefully it will be simple enough to do, but I can't guarantee that
I'll get it working.

At the moment I need to fix the refresh rates and colour first as it's
affecting a bigger portion of the population, then I'll try to support
cloned display after that.

I have no idea how that is even represented within the display layout CCD
API, so it will be a while lot of experimentation.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sneakingJ I can't believe it, but I think I managed to get Cloned displays to work! I have them running on my machine and swapping between cloned and extended desktops works fine!

So, to test the library, can you please download NVIDIAInfo v1.1.1 and give it a test with cloned and non cloned displays? I think it should work 🤞 

https://github.com/terrymacdonald/NVIDIAInfo/releases/tag/v1.1.1

Thanks
Terry

**Comment by cp-jonas** [comment]
@terrymacdonald I tried running the .exe but got an immediate Windows Defender warning. The exe ran and stopped. Can you give me a run down what exactly I have to do with that program?

**Comment by terrymacdonald** [comment]
Argh not this again! We had this 2 months ago week another build! Windows
defender was incorrectly matching my code against a Trojan, and widows
defender was doing operation. I had to raise a ticket with Microsoft, and
after a day they reviewed the code and fixed the issue.

I can't believe it's happened twice! Greer.

I'll go log a ticket now.

Sadly
Terry

**Comment by terrymacdonald** [comment]
@sneakingJ Here is the previous Windows Defender issue I had (it was with AMDInfo): https://github.com/terrymacdonald/DisplayMagician/issues/37#issuecomment-923629582

I'm logging the false positive with Microsoft now.

**Comment by terrymacdonald** [comment]
@sneakingJ As I was doing my Windows Defender testing locally on my machine, I wasn't able to make Windows Defender trigger and block the program. I tried with NVIDIAInfo v1.1.1 and it was fine. It worked well.

I updated the Windows Defender security intelligence definition to the latest version (v1.351.536.0) and it was still working. Can you please tell me what version of the Windows Defender security intelligence definition you are running? You can check by going to **Windows Security > Virus & Threat Protection > Check for updates** and it will list it there. This will also update your security intelligence definition to the latest version, so you can try again and see if it still does it.

As I can't trigger the same thing locally, can you please also tell me what Windows Defender thinks NVIDIAInfo is? You can see that by going to **Windows Security > Virus & Threat Protection > Protection history** and it will list a detection there. Click on the detection text and it will provide a 'Detected" <name of detection>' bit of text. Please reply with that text which should be similar to PUA:Win32/SP2!BlahBlah or something like that.

It's very odd it's not triggering on my machine. Does anyone else have NVIDIAInfo v1.1.1 being blocked?

Anyway  - once you do get it running @sneakingJ, then you need to use it to create some display configs. NVIDIAInfo is the little test program I've written for the NVIDIALibrary and WinLibrary video manipulation libraries. It is a way of testing the video libraries only, without the rest of the DisplayMagician codebase. It means that we can only test the video libraries themselves, and we don't need to worry about effects from anything else.

So, once Windows defender is sorted, can you please do the following tasks:

- Open a windows command prompt in the same folder as the extracted NVIDIAInfo.exe
- Run `NVIDIAInfo save my-first-profile.cfg` to save the display profile as you have it right now to the my-first-profile.cfg file
- Use NVIDIA Control Panel or Windows Setup to change the screen to another display configuration 
- Run `NVIDIAInfo save my-second-profile.cfg` to save the display profile as you have it right now to the my-second-profile.cfg file

At this point, you now have two display profile configuration, and you can use NVIDIAInfo to swap between them.

- To use the first profile, run `NVIDIAInfo load my-first-profile.cfg`
- To use the second profile, run `NVIDIAInfo load my-second-profile.cfg`

Please run through swapping between each of the different profiles you want (you can make more than two) and please report back with whether they have worked now or not. Cloned windows worked for me last night in testing, so I want to try with someone else's hardware. **If you get an error, please make sure you also attach the NVIDIAInfo.log file to your reply.**

Thanks
Terry

**Comment by sneakingJ** [comment]
@terrymacdonald I think I already made an exception for Defender earlier when it first popped up, so I don't see a message for it anymore. There is also unfortunately nothing in my protection history about it. My definition version is the latest and it's 1.351.543.0.

I can swap between a cloned profile and a not-cloned profile via NVIDIAInfo and everything seems to work. However I do get an error in the terminal window when loading the cloned profile regardless of it working:
```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DisplayMagicianShared.NVIDIA.NVIDIALibrary.SetActiveConfigOverride(NVIDIA_DISPLAY_CONFIG displayConfig) in H:\vscode-projects\NVIDIAInfo\NVIDIAInfo\NVIDIALibrary.cs:line 1428
   at NVIDIAInfo.Program.loadFromFile(String filename) in H:\vscode-projects\NVIDIAInfo\NVIDIAInfo\Program.cs:line 319
   at NVIDIAInfo.Program.Main(String[] args) in H:\vscode-projects\NVIDIAInfo\NVIDIAInfo\Program.cs:line 110
   ```
   
   Here is my full NVIDIAInfo.log after switching profiles a couple of times:
[NVIDIAInfo.log](https://github.com/terrymacdonald/DisplayMagician/files/7358147/NVIDIAInfo.log)

**Comment by terrymacdonald** [comment]
OK - thanks - I'll check that out and try and squash the bug. Thanks for the error message that really helps. 

I've been working on DisplayMagician in the background and I wanted to show you this:

![image](https://user-images.githubusercontent.com/5721772/137601382-01ea06ba-8ef8-4331-8ff1-2ed6ccc24659.png)

It will now tell you the number of clones you have for each screen. Unfortunately with clones there is no way to tell where they are physically because they are just logical copies, so this was the best way I could get this to look :/. Oh well.

Cloned display support will come out in 2.1.0 which will be about 1-2 weeks away now. The main focus on this version is bugfixing the video libraries, and that's coming along nicely! I'll get you to test an pre-release version to confirm the cloned issue is fixed when I'm a bit further along in dev.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@sneakingJ Sorry to bother you again, but can you please upload your two NVIDIAInfo cfg files please? I need to compare them to see why that error is happening.

**Comment by sneakingJ** [comment]
Awesome. Just ping me for the pre-release version and I'll test it. 
Here are my two config files:
[cloned.cfg.txt](https://github.com/terrymacdonald/DisplayMagician/files/7358248/cloned.cfg.txt)
[not-cloned.cfg.txt](https://github.com/terrymacdonald/DisplayMagician/files/7358249/not-cloned.cfg.txt)

Thanks @terrymacdonald for your work on this <3

**Comment by terrymacdonald** [comment]
@sneakingJ I've made some changes to the logic to (hopefully) avoid those error messages. Can you please test this attached version of NVIDIAInfo? Same test as before please :).

[NVIDIAInfo-v1.1.2.zip](https://github.com/terrymacdonald/DisplayMagician/files/7358268/NVIDIAInfo-v1.1.2.zip)

**Comment by sneakingJ** [comment]
@terrymacdonald With this new version, I got the Defender warning again, but the program ran nevertheless. Defender redirected me to this site: https://support.microsoft.com/en-us/topic/what-is-a-cloud-security-scan-75112696-7660-4450-9194-d717f72a8ad8
In the Protection History it says "The setting to block potentially unwanted apps is turned off. Your device may be vulnerable."

This version made it worse unfortunately. The error when loading the cloned profile is the same as in my previous comment but it also does not switch to the profile now. While with the version before, the error popped up but it still loaded the cfg correctly.

**Comment by terrymacdonald** [comment]
And, once you've tested the above, @sneakingJ , I've got a new test build for DisplayMagician v2.1.0 for you to test for me please!

[DisplayMagicianSetup-v2.1.0.7.zip](https://github.com/terrymacdonald/DisplayMagician/files/7359540/DisplayMagicianSetup-v2.1.0.7.zip)

If this fixes your current color settings issue, then please log that fact here.

If you find another issue not related to this issue, then please log a new issue so that I can troubleshoot it separately. I need to iron out all the bugs so that I can bake a proper release. 

Thanks
Terry

**Comment by sneakingJ** [comment]
@terrymacdonald I already tested the above :) https://github.com/terrymacdonald/DisplayMagician/issues/47#issuecomment-945069999

What color setting issue do you mean though? I think you're confusing me with another ticket.

**Comment by terrymacdonald** [comment]
Yeah I think so too! There's a lot of moving pieces at the moment.

In that case, just test the new DisplayMagician test build for me if you
could. It should (hopefully) work flawlessly 😁.

Terry

**Comment by cp-jonas** [comment]
@terrymacdonald Ah damn, that is annoying. I'm sure you're not the only one struggling with this though. I tried other software before yours a few months ago and that one had problems with profiles as well. It might have been the same issue.

**Comment by terrymacdonald** [comment]
All is not lost yet. I'll let it bubble about in my mind for a few days and see if I get an idea.

**Comment by terrymacdonald** [comment]
And an idea has appeared overnight!

I'm going to try and detect when the screen layout has a cloned screen, and then I'm going to store that separately from the rest of the config, and effectively removing the cloned screen from the screen layout, but storing the settings. 

When it comes time to then apply that display profile, I will firstly apply the config without the clone, and then clone the screen separately afterwards in another call. In this way the existing codebase will work (as it doesn't include the cloned display which was causing errors) and the layout *should* work ok. 

There are a few questions I have though:

- Will it work :)
- Will it result in adding another display layout to the registry each time (eventually causing windows to store hundreds of unused display layouts over time
- Will it affect the DeviceContext afterwards? (THats the thing that sets the refresh rates and non-HDR colour settings)

I'll do some testing and see what happens....

Terry

**Comment by terrymacdonald** [comment]
Ok. That's progress at least.

After further testing locally, I'm now struggling with how to make it work
after a reboot. The problem now appears to be the GDI bits I added to
correct the colour settings/refresh settings issues.

I'll do some more testing and see what I come up with. I may not be able to
have refresh rate or colour settings applied to a cloned display...

I'll also have a look at what you've sent me to see if there are any other
clues I can get.

We're nearly there!

Terry

**Comment by terrymacdonald** [comment]
@sneakingJ @S4b0tage After about 11 hours of work(!) I think I've managed to work around the various issues I've found. This has been one of the hardest parts of the entire custom video library redevelopment, and I think it's finally coming to a conclusion. I've been able to get cloned and non-cloned displays working after multiple restarts and reboots, and I think I've found the golden combination of the right settings that will work with Windows 10. Bet it gets broken by Windows 11!

Anyway - can you both please test with CCDInfo v1.2.0: https://github.com/terrymacdonald/CCDInfo/releases/tag/v1.2.0

This software is designed to test just the Windows-specific library (no NVIDIA or AMD settings, or any other DisplayMagician bits) and so it allows me to make sure that the WinLibrary works. And now I need your help :).

So, once again, can you please do the following tasks:

- Open a windows command prompt in the same folder as the extracted CCDInfo.exe
- Run `CCDInfo save my-first-profile.cfg` to save the display profile as you have it right now to the my-first-profile.cfg file
- Use Windows Setup to change the screen to another display configuration (so that one of them is a cloned display and the other non-cloned)
- Run `CCDInfo save my-second-profile.cfg` to save the display profile as you have it right now to the my-second-profile.cfg file

At this point, you now have two display profile configurations, and you can use CCDInfo to swap between them.

- To use the first profile, run `CCDInfo load my-first-profile.cfg`
- To use the second profile, run `CCDInfo load my-second-profile.cfg`

Please run through swapping between each of the different profiles you want and please report back with whether they have worked now or not. **If you get an error, please make sure you also attach the CCDInfo.log file from the faulty run and the cfg files to your reply.**

Once you've tested CCDInfo and it's worked, then I'll roll those changes into a new version of NVIDIAInfo (which uses my NVIDIALibrary and WinLibrary together) and get you to test it, and then if that works, into DisplayMagician it goes!

Thanks
Terry
