### ISSUE TITLE
Nothing happends when apply display profile

### ISSUE THREAD

**Issue by Cardistymo** [terrymacdonald/DisplayMagician#59]
**Describe the bug**
One of my display profiles doesnt work.
If I press the 'apply' button nothing happends. I already recreated the profile...

[DisplayMagician-Support-20211128-1119.zip](https://github.com/terrymacdonald/DisplayMagician/files/7613273/DisplayMagician-Support-20211128-1119.zip)

**Enviroment (please complete the following information):**
 - Win11
 - DisplayMagician V2.1.1.1
 - Video Card: Nvidia GeForce GTX 1650
 - Number and make/model of monitors: 3x HP 27xq LED-Monitor
 - Date of last video driver update: dont know
 - Date of last windows update: Today I installed KB5007262

**Comment by terrymacdonald** [comment]
Hi @Cardistymo 

Did you upgrade to windows 11 after you've made a DisplayMagician profile? If you upgrade to windows 11 then you need to recreate all your display profiles and delete the old windows 10 display profiles. Then you need to edit all of your shortcuts to use the new display profiles.

The reason is that windows 11 has a different display configuration structure. DisplayMagician can track all the settings because it grand the display configuration from windows and saves it with minimal modification. This unfortunately means that it is very sensitive to changes in that display configuration, and that happens when the operating system is upgraded.

Can you please recreate a new display profile and see if that fixes it? You will need to edit your game shortcut to use that new display profile too.

Thanks
Terry

**Comment by Cardistymo** [comment]
As I mentioned in my last post, I already recreated the profile...

**Comment by Cardistymo** [comment]
Also I did not updated to Win11 instead I reinstalled Windows completly..

**Comment by terrymacdonald** [comment]
@Cardistymo Can you please tell me which profile doesn't work? 'Surround' or 'Current NVIDIA Display Profile'? 

And how are you applying it? Are you going into the Display Profiles page and clicking on the 'Apply' button for that profile? If that is what you are doing, what do you see on the screen? Does anything happen at all? Any error messages, or does the screen flash?

What version of NVIDIA video card driver do you have? 

What connection do you have between your 3x HP 27xq LED-Monitors and your Nvidia GeForce GTX 1650? 

Thanks
Terry

**Comment by Cardistymo** [comment]
The 'Current NVIDIA Display Profile' doesnt work...
I am just going into Display Profiles and click 'Apply'. The Button stays selected for a few seconds (I think the window freezes) and on my screens nothing happends at all. 
I use 2x Displayport and 1x HDMI. My video card driver version is 'NVIDIA 30.0.14.9676'.

**Comment by Cardistymo** [comment]
After updating the driver and recreating all display profiles it works now.
Thanks for your support and the great software @terrymacdonald !
