### ISSUE TITLE
Error message on attempting to either save a second profile or rename an existing one

### ISSUE THREAD

**Issue by Chris5gd** [terrymacdonald/DisplayMagician#70]
On my 3-monitor system in non-surround mode, creating the first saved profile worked, although Save As didn't give the option to give it a name.  It was saved as 'Current Nvidia Display Profile'.

Attempting to rename it gave: '**Sorry, each saved display profile needs a unique name**'.

Using the Nvidia control panel, switched to 3-monitor surround.  Restarted DM.  Current display correctly shown as one primary display spanning 3 monitors.

Save As gave the same error as above.

Selecting the saved profile and attempting to delete caused an unhandled exception the first time, but worked the second time.

**Enviroment (please complete the following information):**
 - Windows Version: Win 10 21H2
 - DisplayMagician Version [e.g. 2.1.5.5]
 - Video Card: e.g. Asus NVIDIA GTX970
 - Number and make/model of monitors:
 - Samsung SMS22A200/460
 - LG E2240
 - Benq GL2250H
 - Date of last video driver update: a few days ago
 - Windows updated to  21H2 about a week ago

**Comment by terrymacdonald** [comment]
@Chris5gd I've just tried the process you described (as far as I understood it), and it worked fine for me with 2.1.5.5. Here is my test:

![image](https://user-images.githubusercontent.com/5721772/147504310-2328f985-1399-4642-8fed-af2f0e83703e.png)

Have you used DisplayMagician much before now? DisplayMagician is designed to work in a particular way, so it might be helpful if I describe below how DisplayMagician is supposed to work, and then you can reply and tell me what parts of that process didn't work for you, or if the process wasn't obvious enough and needs refinement.

**IMPORTANT** Think of DisplayMagician as a display settings recorder/player. It doesn't let you edit any display settings - it only lets you record them, and then use those settings later.

**To use DisplayMagician:**
- Run 'DisplayMagician', and click on the 'Display Profiles' button to go to the Display Profiles window.
- Minimise the DisplayMagcian window.
- Open up 'Windows Display Settings', 'NVIDIA Control Panel' or 'AMD Radeon Adrenaline' to configure your display layout, HDR setting, refresh rates and what ever else you want to change, to get your display layout exactly as you would like it.
- When you have your display layout as you want it, ALT-TAB back to DisplayMagician, and you should see the new display configuration shown in the Display Profile window.
- Enter the name that you want to use for the Display Profile in the text box.
- Click the 'Save As/Rename' button so that DisplayMagician will save the current Display Profile.

Repeat all the steps above until you have saved each display profile layout that you want to have available. When you have finished, click the 'Back' button to go back to the main DisplayMagician window.

Now that you have some Display Profiles set up, you can create some Game Shortcuts that will use them! 
- Click on the 'Game Shortcuts' button.
- You will be shown your Shortcut Library window. This is where all your Shortcuts live, and where you have to go if you ever want to edit them.
- Click the 'New' button to create a new Game Shortcut
- Choose the Display Profile you want to use with the Game Shortcut. Make sure it matches what the game expects :).
- Click on the '2. Choose Audio' tab, to modify which speakers you use for sound, or which microphone you use to talk into.
- Click on the '3. Choose what happens before' tab, to choose any other programs you want to start before you start the main Game or Application. You can choose if you want to shut them down afterwards too! Click on the 'Find Examples' button if you'd like to see some example helper software and their settings for popular games.
- Click on the '4. Choose Game to start' tab, to choose the main game or application that the Game Shortcut will start and monitor.
- Choose the Game from the list shown (be sure to click it so it has a red border), or if it's not shown in this list then select the specific game or application executable in the 'Launch a Game executable' section of the page.
- Click on the '5. Chose what happens afterwards' tab, and choose if you want to rollback any changes made by the Game Shortcut when it runs, or if you want to keep them rather than rolling them back.
- If the 'auto-suggest name' option is enabled then you should have a Shortcut Name already entered in automatically. If not enter one in.
- You can optionally create a keyboard shortcut (Hotkey) for this Game Shortcut. To do this, click on the 'Hotkey' button.
- Click the 'Save' button to save the Shortcut to the Shortcut Library. If you can only see the outline of a button, then you have some missing fields you need to fill in. The Save button only shows if you have a valid Shortcut set up.
Once you've saved the Shortcut, you should see it in the Shortcut Library.
- To create a Desktop shortcut file from your Shortcut, select it in the list in your Shortcut Library, and click the 'Save to Desktop' button. This will then write the Shortcut to your computer, ready to use!

You now have 4 different ways you can start your shortcut:

- You can double-click on the Desktop shortcut you just saved to the Desktop to start your game; or
- You can right mouse click on the desktop background, and select the Game Shortcut from the DisplayMagician pop-up menu to start your game; or
- You can right mouse click on the DisplayMagician notification tray icon, and select the Game Shortcut from the DisplayMagician pop-up menu to start your game; or
- (optionally) If you've set a Hotkey for your Game Shortcut, you can press the Hotkey keyboard shortcut whenever DisplayMagician is running and your Game Shortcut will run.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Looking at the Display Profile window, I decided that the 'Save As' button needed to be changed to 'Save' to better describe what it does. 'Save As' implies that a 'Save File' window will popup, and you will be able to save the profile as another name, when this isn't the case. The only way to save a second display profile is to change the display layout to a new one. This needs to be communicated better within the app.

@Chris5gd Would it help if I added a 'Help' button to the display profile window? I'm envisaging that the help button would link to a 'how to use displaymagician' page on the wiki that would describe the steps you need to take. Would that make things clearer?

I also noticed that it is possible to save a display profile with no name at the moment. This shouldn't be allowed, so I've built in some protections in code to stop that happening again.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@Chris5gd Here is a test version of DisplayMagician that I've made that has some extra help buttons added to various pages that will hopefully help provide a better initial setup experience. Can you please download it, extract the zip file and install it, and tell me if that makes things better?

[DisplayMagicianSetup-v2.1.5.9.zip](https://github.com/terrymacdonald/DisplayMagician/files/7781852/DisplayMagicianSetup-v2.1.5.9.zip)

Thanks
Terry

**Comment by Chris5gd** [comment]
Hi Terry

 

This is much easier to work with, thanks so much.

 

Changing the text on the buttons does make it more obvious what to do.  What wasn’t obvious was that the default text “Current NVIDIA display profile” is actually an editable field.  I thought it was simply a caption for the current one.  And as you say, with ‘Save as’, I was expecting a dialogue to pop up.

 

I spend a lot of my time maintaining and enhancing a complex .NET Windows Forms app, and I know how hard it can be sometimes to get the UI right!

 

Perhaps style the text box a little differently so that it’s more obviously an enterable field?  But the changed text does make it a lot better.

 

Anyway, all good now.  Thanks for the super quick response!

 

It’s working well, and the actual switching is quite quick, compared with another one I’ve tried (Helios Display Management).

 

Great job.  Switching from surround back to three separate monitors is now easy.

 

All the best,

Chris

**Comment by terrymacdonald** [comment]
Hi Chris,

Great news! I'll close down your issue now then. I'm going to wait a couple
of weeks before I release this updated version to the public as I've
released a few bug fix versions just recently. Don't want people to have to
update so quickly.

I really recommend taking a look at the game shortcut features, as they can
be really helpful if you're into flight sim or sim racing. There is a 'show
me examples' button on some of the edit shortcut form tabs that will link
to some wiki pages with some examples of how to use things like the start
programs, or some main game application settings {some games need a
different exe monitored). I try to keep it updated with settings when I
find new ones.

Hope you have a great year!

Thanks
Terry

**Comment by terrymacdonald** [comment]
Issue fixed.

**Comment by Chris5gd** [comment]
Hello mate… me again 😊

 

Not a problem.. just wondering if there's anywhere I can leave a glowing review for you.

 

I’ve got myself some shortcuts sorted out now, and it’s like a miracle, how easy it is to swap between profiles.

 

I switch between non-surround (for my day job, writing code) and surround (for Elite: Dangerous and MS Flight Sim), and before finding your app it was a right PITA.

 

Happy to leave a positive review if you'd care to suggest where.

 

Chris

**Comment by terrymacdonald** [comment]
Hi Chris,

Thanks for the thoughtful idea.

You can reply to the race department thread, or the gtplanet one, or just
post it somewhere new like Reddit, or on a sim racing forum somewhere.
Basically anywhere that you think DisplayMagician will make people's lives
easier!

Thanks
Terry
