### ISSUE TITLE
Can we get an option to disable scanning for games?

### ISSUE THREAD

**Issue by arphex** [terrymacdonald/DisplayMagician#86]
**Is your feature request related to a problem? Please describe.**
When the app starts up it takes ages to scan all games every time.  This is especially problematic on startup.  If one just needs the app to switch monitor profiles quickly (e.g. 3 monitor to surround or one monitor etc.) then this feature is entirely unnecessary

**Describe the solution you'd like**
an option to disable scanning for games and just use the app to switch profiles!

**Describe alternatives you've considered**
I tried looking for such an option or similar but nothing worked.  Perhaps there is an app I couldnt find out there that does this

**Additional context**
Nothing else - just would like to avoid waiting for the game scan every time

**Comment by terrymacdonald** [comment]
Hi @arphex ,

You're in luck. I've already had a request for something similar, and I've been working hard on something for version 2.2 release. It's been a long time in development because it's required a lot of work to make the changes. I've had to move the program architecture to a single instance design which has required turning the application multithreaded, which in turn caused other knock on effects.

I've managed to bug fix most of the issues, and we're now in the final few weeks of development for the new release..

The revamped DisplayMagician is designed to run minimised on computer startup. It loads the games once at that time, and then sits and waits for further commands. When any desktop shortcuts are run then that instance hands over the command to the original single instance running in the background, and that actually does the work. 

It all makes the process much faster in general. It's as far as I can make it.

As this is already fixed in the codebase  I'm going to close this issue so I can keep track of the outstanding work I need to finish in order to generate a new release.

Thanks
Terry
