### ISSUE TITLE
NVidia - Bitdepth in surround mode is not restored to its original value

### ISSUE THREAD

**Issue by bjorg** [terrymacdonald/DisplayMagician#91]
**Describe the bug**

When I enable surround mode, I always get 8 bpc (bits per color) even though I stored the display profile with 10 bpc.

**To Reproduce**
1. Create a surround mode.
2. Under "Change Resolution" change "Output color depth" to "10 bpc".
3. Create a display profile for current display settings.
4. Create a desktop shortcut for current display settings.
5. Exit surround mode
6. Activate display settings shortcut.
7. OUTCOME: Surround mode is using "8 bpc" instead of "10 bpc".

**Expected behaviour**
Apply color depth that was set in NVidia Control Panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/63682/156431999-c4af333c-3e02-40d4-92c1-e3dbc7bec7c8.png)

**Enviroment:**
 - Windows Version: Win11
 - DisplayMagician Version: 2.1.5.5
 - Video Card: NVIDIA GeForce RTX 3080 Ti
 - Number and make/model of monitors: Sony C-LED Video Wall
 - Date of last video driver update: 2022-02-14
 - Date of last windows update: 2022-03-02

**Additional context**
Amazing tool BTW!!

**Comment by bjorg** [comment]
Looks like these settings are also not applied automatically.
![image](https://user-images.githubusercontent.com/63682/156509745-f32916f1-6a63-4586-93a3-7fce15a7c049.png)

Please let me know if I can supply any additional information. Thanks!

**Comment by terrymacdonald** [comment]
Hi Steve,

Thanks for your issue.

Not all NVIDIA settings are recorded or applied at present. NVIDIA has a
large number of separate functions within the NVAPI, and it takes quite a
lot of work to figure out which settings are in which functions, not to
mention the time spent trying to reverse engineer how to call the functions
and interact with the C DLL from C# in a way the provides the functions
with the data structures they need.

As such I'm slowly chipping away at the mountain of work, prioritising the
things that I think will make a difference and cover the most used
settings. At present I'm trying to get the main display config structures
from the NVAPI, but it's the API call I'm having the most difficulty with.
That function is called 3 times in 3 different ways, and returns different
things each time. In addition, the way that C# handles unmanaged memory
means that I'm going to have to manually handle unmanaged memory myself
which is a massive amount of testing and troubleshooting. I'm having many
issues getting the memory structured the correct way for the NVAPI function
call and to be honest it's taken months so far.

I *think* the settings you mention are returned in the display config
structure, but I'm not certain. I'll keep working on this and see what I
find.

I wanted to let people are the massive amount of work it takes to put
together something like this, and that while progress might seem slow, I
should eventually get to most settings.

I will caveat that with the fact that DisplayMagician will not ever get all
the settings that NVIDIA provides. NVIDIA changes things so often that is
be spending all my time chasing their config structure. In general I
concentrate on the main settings that matter, and impact the most number of
users.

Hope that helps understand where things are at? Sorry for the long post!

Thanks
Terry

**Comment by bjorg** [comment]
Thanks for the detailed explanation. Can you point me to the code that you think could be responsible for this? I don't want to promise anything, but maybe I could help track this down. Just curious where to start looking (and logging!).

**Comment by terrymacdonald** [comment]
I just got back from a holiday, and had a closer look at the settings you mentioned. Those BPC settings are already tracked by DisplayMagician, specifically we get the color settings here: https://github.com/terrymacdonald/DisplayMagician/blob/main/DisplayMagicianShared/NVIDIA/NVIDIALibrary.cs#L800 and we set the settings here: https://github.com/terrymacdonald/DisplayMagician/blob/main/DisplayMagicianShared/NVIDIA/NVIDIALibrary.cs#L1298.

IIRC there was a bug in DisplayMagician v2.1.5.5 about when it applied HDR and colour settings; in some situations it wouldn't correctly apply them. It's been so long that I've forgotten exactly which bug that was 🙄 . 

I have been working on a new version of DisplayMagician for the last 3 months (v2.2.0) so I've been concentrating on adding some new features and knocking over the older bugs from 2.1.5.5, so please forgive me for not remembering earlier. I'm not sure if this will fix your exact issue when it is released, but I hope it will. You'll at least be able to test for me!

WARNING - the new version of DisplayMagician will require recreating your Display Profiles from scratch, as it has a lot of new settings it tries to grab.

As for handling putting the taskbar on all displays for surround mode, it's not currently supported. It's been nearly a year's worth of work building a custom NVIDIA video card library from scratch, and I have had to cover the most commonly used parts of the NVAPI in order to best cover the features people want. It's a LOT of work, and to be honest, that particular setting isn't one that I'll add within the next few months. At the moment I'm trying to figure out how to place windows taskbars and delving deep into internal windows messaging so that will take precedence right now. 

For future reference, this is the API that I'm interfacing with in order to make this work. https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/modules.htmlNVIDIA supply a C API themselves, but there wasn't an official C# API, so I made one... this is why it's taken so long. DisplayMagician was using NvAPIWrapper by Soroush Falahati (he is awesome) but I wanted to be able to make bugfixes and create an AMD version of a library as well, so I decided to write my own from scratch instead. NVIDIA NVAPI is not easy to use, and the public documentation has errors and is missing useful information. I've had to reverse engineer a lot of functionality, and figure out how to use the PInvoke memory marshalling works in order to recreate the structures in memory that the NVIDIA NVAPI64.dll functions require (GetDisplayConfig took me 4 months to get working!).

Anyway, sorry for the long rambling post.

If you're still interested in me adding the surround taskbar stuff, then please raise that as a new 'feature request' github issue on it's own, and that will prompt me in the future when I'm looking for features to add.

I'll keep this issues open for now, and I'll get you to test the pre-release versions of DisplayMagician v2.2.0 when I release them in the new few weeks. My gut feel it that I'll be aiming for the next release in 4 weeks.

I'll post something then.

Thanks
Terry

**Comment by bjorg** [comment]
I just left for vacation but will try out the newer build. Before I left, I already cloned the repo and was able to build it (except for WIX, which I don't have installed).

Another piece of functionality I'd like to add is the ability to query which profile is currently active via command line. That will allow me to script out mode changes for my setup. NVidia Surround Driver is not super happy when I try to swap from one surround profile to another in one step when the displays also change at the same time. It's a weird situation specific to the display I use to switch between 4K@120Hz and 3D@60Hz. The Sony display controller reports them as different monitors instead of just different resolutions. Anyway, I'm thinking to add a console app for this that uses the `ProfileRepository` and prints out the current display mode.

Before I embark on this, I assume (a) this is not possible yet and (b) this is the right approach. Also, should I use the `develop` branch? Is that where the new v2.2.0 code resides?

NB: By the way, you've done some amazing work here! Thank you so much for all your effort to make this a reality. Super useful project!

**Comment by terrymacdonald** [comment]
Hi Steve,

DisplayMagician copes with turning on monitors, but cannot force a display
to appear if it's not already at least shown to be available to be
connected to Windows. If I'm reading your text correctly then your setup
acts like your unplugging one display and plugging in the other display.
DisplayMagician won't work in that situation, as it wouldn't detect the
other display and so wouldn't swap between them.

For a command line option I'd use my NVIDIAInfo application. NVIDIAInfo is
my little test application I made that only does display manipulation. It's
how I perform testing for the display manipulation libraries I made.

I'd recommend using that for what you're trying to do.

NVIDIAInfo allows you to save a display config to a file, and load a
display config from a file. It also allows you to test for equality, so you
can test that the current display layout is equal to the display config
saved in a file. That might be what you're looking for.

At the moment I don't think NVIDIAInfo is reporting error levels, so that
makes it a bit more challenging. I'm working on NVIDIAInfo now to add the
NVIDIA display config stuff to it, so I'll add that work to the list too.

Thanks
Terry

**Comment by bjorg** [comment]
@terrymacdonald I'm back from vacation. I'm hoping to dive into the code more end of this week.

1. How do I test the 2.2.0 build? Is that the version in the `develop` branch?
2. Do I need to copy the project binary to a specific location on the target machine?
 
Thx!

**Comment by bjorg** [comment]
Hopefully I got this mostly right. I wasn't sure what you meant by triple and cloned screens. So instead, I cycled through the 4 display combinations I have access to. Let me know if you need anything else.

[results.zip](https://github.com/terrymacdonald/DisplayMagician/files/8347647/results.zip)

# Testing for NVIDIAInfo-v1.7.0

## Step 1 - Surround 3D Configuration

4x displays (1920x2160 @ 60Hz) in side-by-side, surround configuraiton to create a single 7680x2160 display. Note, there should be an additional HDMI display in HD configuration used for sound output, but this display is not connected to the NVIDIA card.

### Save Configuration
```
$ ./NVIDIAInfo.exe save surround-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Display settings successfully saved to surround-3d.cfg.
```

### Backup log file
```
$ mv NVIDIAInfo.log surround-3d.log
```

### Verify configuration was properly stored for Surround 3D
```
$ ./NVIDIAInfo.exe equal surround-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in surround-3d.cfg and the currently active display configuration are equal.
```


## Step 2 - Individual 3D Configuration

4x individual displays (1920x2160 @ 60Hz). Note, there should be an additional HDMI display in HD configuration used for sound output, but this display is not connected to the NVIDIA card, but the motherboard HHDMI instead.

### Save Configuration
```
$ ./NVIDIAInfo.exe save individual-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Display settings successfully saved to individual-3d.cfg.
```

### Backup log file
```
$ mv NVIDIAInfo.log individual-3d.log
```

### Verify configuration was properly stored for Individual 3D
```
$ ./NVIDIAInfo.exe equal individual-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in individual-3d.cfg and the currently active display configuration are equal.
```

### Verify configuration is different from Surround 3D
```
$ ./NVIDIAInfo.exe equal surround-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in surround-3d.cfg and the currently active display configuration are NOT equal.
```


## Step 3 - Switch Display from 3D to 2D

**NOTE:** This requires a display mode change from 3D to 2D that is done out-of-band. This forces the OS to recognize a new set of displays at a new resolution (4x 1920x1080 @ 120Hz).


## Step 4 - Individual 4xHD Configuration

4x individual displays (1920x1080 @ 120Hz). Note, there should be an additional HDMI display in HD configuration used for sound output, but this display is not connected to the NVIDIA card, but the motherboard HHDMI instead.

### Save Configuration
```
$ ./NVIDIAInfo.exe save individual-4xHD.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Display settings successfully saved to individual-4xHD.cfg.
```

### Backup log file
```
$ mv NVIDIAInfo.log individual-4xHD.log
```

### Verify configuration was properly stored for Individual 4xHD
```
$ ./NVIDIAInfo.exe equal individual-4xHD.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in individual-4xHD.cfg and the currently active display configuration are equal.
```

### Verify configuration is different from Individual 3D
```
$ ./NVIDIAInfo.exe equal individual-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in individual-3d.cfg and the currently active display configuration are NOT equal.
```


### Step 5 - Surround 4K Configuration

4x displays (1920x1920 @ 120Hz) in 2x2 grid, surround configuraiton to create a 4K display. Note, there should be an additional HDMI display in HD configuration used for sound output, but this display is not connected to the NVIDIA card.

### Save Configuration
```
$ ./NVIDIAInfo.exe save surround-4K.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Display settings successfully saved to surround-4K.cfg.
```

### Backup log file
```
$ mv NVIDIAInfo.log surround-4K.log
```

### Verify configuration was properly stored for Surround 4K
```
HTPC /c/Projects/NVIDIAInfo-v1.7.0
$ ./NVIDIAInfo.exe equal surround-4K.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in surround-4K.cfg and the currently active display configuration are equal.
```

### Verify configuration is different from Individual 4xHD
```
$ ./NVIDIAInfo.exe equal individual-4xHD.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in individual-4xHD.cfg and the currently active display configuration are NOT equal.
```

### Verify configuration is different from Individual 3D
```
$ ./NVIDIAInfo.exe equal individual-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in individual-3d.cfg and the currently active display configuration are NOT equal.
```

### Verify configuration is different from Surround 3D
```
$ ./NVIDIAInfo.exe equal surround-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in surround-3d.cfg and the currently active display configuration are NOT equal.
```


## Step 6 - Reload Individual 4xHD Configuration

### Reload Individual 4xHD Configuration
```
$ ./NVIDIAInfo.exe load individual-4xHD.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Attempting to apply NVIDIA display config from individual-4xHD.cfg
NVIDIAInfo Display config successfully applied
```

### Backup log file
```
$ mv NVIDIAInfo.log individual-4xHD-reload.log
```

### Verify configuration is identical to Individual 4xHD
```
$ ./NVIDIAInfo.exe equal individual-4xHD.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in individual-4xHD.cfg and the currently active display configuration are equal.
```

### Store reloaded Individual 4xHD Configuration
```
$ ./NVIDIAInfo.exe save individual-4xHD-reload.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Display settings successfully saved to individual-4xHD-reload.cfg.
```

### Verify configuration is different from Individual 3D
```
$ ./NVIDIAInfo.exe equal individual-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in individual-3d.cfg and the currently active display configuration are NOT equal.
```


## Step 7 - Reload Surround 4K Configuration

### Reload Surround 4K Configuration
```
$ ./NVIDIAInfo.exe load surround-4K.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Attempting to apply NVIDIA display config from surround-4K.cfg
NVIDIAInfo Display config successfully applied
```

### Backup log file
```
$ mv NVIDIAInfo.log surround-4K-reload.log
```

### Verify configuration is identical to Surround 4K
```
$ ./NVIDIAInfo.exe equal surround-4K.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in surround-4K.cfg and the currently active display configuration are equal.
```

### Store reloaded Surround 4K Configuration
```
$ ./NVIDIAInfo.exe save surround-4K-reload.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Display settings successfully saved to surround-4K-reload.cfg.
```


## Step 8 - Reload Individual 4xHD Configuration and then Individual 3D

### Reload Individual 4xHD Configuration
```
$ ./NVIDIAInfo.exe load individual-4xHD.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Attempting to apply NVIDIA display config from individual-4xHD.cfg
NVIDIAInfo Display config successfully applied
```

### Switch Display from 2D to 3D
**NOTE:** Need to switch from 2D mode to 3D mode which is done out-of-band. This forces the OS to recognize a new set of displays at a new resolution (4x 1920x2160 @ 60Hz).

### Reload Individual 3D Configuration
```
$ ./NVIDIAInfo.exe load individual-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Attempting to apply NVIDIA display config from individual-3d.cfg
NVIDIAInfo Display config successfully applied
```

### Backup log file
```
$ mv NVIDIAInfo.log individual-3D-reload.log
```

### Store reloaded Individual 3D Configuration
```
$ ./NVIDIAInfo.exe save individual-3d-reload.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Display settings successfully saved to individual-3d-reload.cfg.
```

### Verify configuration is identical to Individual 3D
```
$ ./NVIDIAInfo.exe equal individual-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in individual-3d.cfg and the currently active display configuration are equal.
```

## Step 9 - Reload Surround 3D Configuration

### Reload Surround 3D Configuration
```
$ ./NVIDIAInfo.exe load surround-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Attempting to apply NVIDIA display config from surround-3d.cfg
NVIDIAInfo Display config successfully applied
```

### Backup log file
```
$ mv NVIDIAInfo.log surround-3d-reload.log
```

**NOTE**: Here I noticed that the other HDMI out got disabled again in the OS and it was only showing Display 1 in the OS settings.

### Verify configuration is identical to Surround 3D
```
$ ./NVIDIAInfo.exe equal surround-3d.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

The NVIDIA display settings in surround-3d.cfg and the currently active display configuration are equal.
```

### Store reloaded Surround 3D Configuration
```
$ ./NVIDIAInfo.exe save surround-3d-reload.cfg

NVIDIAInfo v1.7.0
=================
By Terry MacDonald 2022

Display settings successfully saved to surround-3d-reload.cfg.
```

**Comment by bjorg** [comment]
@terrymacdonald Not sure if my logs helped you, but NVIDIAInfo is pretty much what I needed for my use case. It restores the bits-per-pixel as well. To determine the current display mode, I used `EnumDisplayDevices` and `EnumDisplaySettings`. Knowing the current display mode was needed, because the NVidia Surround implementation is not fond of having it's monitors switch resolutions while enabled. It pretty much requires a reboot to get out of the bad state.

From my perspective, this issue can be closed. Also, NVIDIAInfo is brilliantly awesome. You should consider making it the goto command line tool. It's solid!!! Thanks again!

**Comment by terrymacdonald** [comment]
@bjorg Hey that's cool news! FYI I've added a `DisplayMagician CurrentProfile` command line option that will spit out the current profile in use. Hopefully that makes things work for you.

Also, the new library we tested in NVIDIAInfo is now in the DisplayMagician develop branch, and I'm just finishing up some troubleshooting around shutting down start programs before I think about a new release. Also wondering if I can add G-SYNC functionality or even head mounted device support to this next release but I might wait for v2.4 for that...

Anyway, hope that helps

Thanks
Terry

**Comment by terrymacdonald** [comment]
Sorry! We just found an issue with some botched Display Profile upgrade logic :(.  Now fixed.

Please do the following:

- Delete `C:\Users\<Username>\AppData\Local\Displaymagician\Profiles\DisplayProfiles_2.3.json` if it exists.
- Install this new DisplayMagician version:
[DisplayMagicianSetup-v2.3.0.36.zip](https://github.com/terrymacdonald/DisplayMagician/files/8467396/DisplayMagicianSetup-v2.3.0.36.zip)
- Run DisplayMagician
- Create your Display Profiles again the way you want them
- Update your Game Shortcuts to use the new Display Profiles
- Have fun with your games!

Hopefully it should work this time.  Please log a new issue at https://github.com/terrymacdonald/DisplayMagician/issues/new/choose if you experience any new bugs that you've not seen before, and I'll get right on fixing them.

Thanks
Terry
