### ISSUE TITLE
4 monitor, switching to surround as triples and 4th as extra positioned wrong

### ISSUE THREAD

**Issue by gptech2444** [terrymacdonald/DisplayMagician#93]
**Describe the bug**
I have the 4th monitor set above the triples but when DM switches to the surround profile it places the 4th monitor to the right of the triples instead of on top.

https://youtu.be/-1y8C5SBncQ

**Comment by terrymacdonald** [comment]
Hi @gptech2444,

Unfortunately I need a lot more information in order to help troubleshoot.

* What version of DisplayMagician are you using?
* what is the make and model of you video card?.
* what make and model are your displays, and how are they connected to the video card (Display Port, HDMI, etc)
* are you using windows 10 or windows 11?

Also, I'll need you to attempt to apply the display profile that isn't working, then create and upload a Support ZIP File. To create the Support ZIP File open DisplayMagician and click on the Settings button, then click on the Create Support ZIP File button. Upload the zip files to this issue using your web browser by dragging and dropping the file on a new GitHub comment on this issue.

I should be able to go through the config and log files within that Support ZIP File to see what the errors are.

Thanks
Terry

**Comment by gptech2444** [comment]
I was hoping there was an easy fix or something I was doing wrong.
I have a PNY XLR8 RTX3090 with latest driver
4th monitor is LG 24GL600F connected by HDMI
triples are Dell S2721DGF connected by DP
DisplayMagician is 2.1.5.5 version just downloaded from github.
and Windows 10 that is fully updated.
Attached is zip file.
Thanks.

**Comment by terrymacdonald** [comment]
Hi @gptech2444,

I've just finished DisplayMagician v2.3.0.35 which is hopefully the next big release of DisplayMagician. It has a lot of improvements and bug fixes to the NVIDIALibrary, and it's possible that it will solve the issues that you've been experiencing. NVIDIALibrary can now handle multiple physical adapters in a logical group, dvi-d and earlier connections, USB connected displays, adaptive sync, image scaling, cloned displays and more. 

[DisplayMagicianSetup-v2.3.0.35.zip](https://github.com/terrymacdonald/DisplayMagician/files/8457813/DisplayMagicianSetup-v2.3.0.35.zip)

Can you please download and install DisplayMagician v2.3.0.35, and then do the following two steps:

- Delete your old Display Profiles 
- Create new Display Profiles 
- Update your Game Shortcuts to use the new Display Profiles

If you have any issues, please create a Support ZIP File (main screen > Settings > Create Support ZIP File) and upload it here through your web browser. I'll then be able to use that for any bug fixing.
 
Thanks
Terry

**Comment by terrymacdonald** [comment]
Sorry! We just found an issue with some botched Display Profile upgrade logic :(.  Now fixed.

Please do the following:

- Delete `C:\Users\<Username>\AppData\Local\Displaymagician\Profiles\DisplayProfiles_2.3.json` if it exists.
- Install this new DisplayMagician version:
[DisplayMagicianSetup-v2.3.0.36.zip](https://github.com/terrymacdonald/DisplayMagician/files/8467396/DisplayMagicianSetup-v2.3.0.36.zip)
- Run DisplayMagician
- Create your Display Profiles again the way you want them
- Update your Game Shortcuts to use the new Display Profiles
- Have fun with your games!

Hopefully it should work this time.  Please log a new issue at https://github.com/terrymacdonald/DisplayMagician/issues/new/choose if you experience any new bugs that you've not seen before, and I'll get right on fixing them.

Thanks
Terry

**Comment by gptech2444** [comment]
Unfortunately this hasn't remedied the issue. 
Now DM won't recognize the triples in surround mode and will only show the 4th monitor when clicking "view current display"
Works fine if triples aren't setup in surround mode.
![image](https://user-images.githubusercontent.com/14959218/162916807-887d6e0b-ef70-4dec-82c7-f88d7d6c5408.png)

**Comment by gptech2444** [comment]
> 

I added it just before you replied
[DisplayMagician-Support-20220412-1834.zip](https://github.com/terrymacdonald/DisplayMagician/files/8471194/DisplayMagician-Support-20220412-1834.zip)
.

**Comment by terrymacdonald** [comment]
@gptech2444,

I've checked the NVIDIALibrary side of things, and it looks as though the display profile can be used. 

```
2022-04-12 18:26:19.1655|TRACE|DisplayMagician.Program|NVIDIALibrary/IsPossibleConfig: Success! The NVIDIA display configuration is possible to be used now
2022-04-12 18:26:19.1655|DEBUG|DisplayMagician.Program|ProfileItem/IsPossibleRefresh: The NVIDIA profile Triples plus 4th is possible!
```

The Display identifiers show that the screens are detected fine by NVIDIA:

```
      "NVIDIA|NVIDIA GeForce RTX 3090|PCI_EXPRESS|6|DP|DEL|16857|1163547468|2147881094",
      "NVIDIA|NVIDIA GeForce RTX 3090|PCI_EXPRESS|6|DP|DEL|16857|1163547980|2147881088",
      "NVIDIA|NVIDIA GeForce RTX 3090|PCI_EXPRESS|6|DP|DEL|16857|1177563468|2147881090",
      "NVIDIA|NVIDIA GeForce RTX 3090|PCI_EXPRESS|6|HDMI|GSM|23410|196405|2147881091"
```

Weird things are occurring though in the WinLibrary component, where I saw this happening:
````
2022-04-12 18:26:19.9937|DEBUG|DisplayMagician.Program|ProfileRepository/GenerateProfileDisplayIdentifiers: DisplayIdentifier: WINAPI|\\?\PCI#VEN_10DE&DEV_2204&SUBSYS_136A196E&REV_A1#4&2283f625&0&0019#{5b45201d-f2f2-4f3b-85bb-30ff1f953599}|DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI|27934|23410|\\?\DISPLAY#GSM5B72#5&2750cc0a&0&UID24832#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}|24GL600F
2022-04-12 18:26:19.9937|DEBUG|DisplayMagician.Program|ProfileRepository/GenerateProfileDisplayIdentifiers: DisplayIdentifier: WINAPI|\\?\PCI#VEN_10DE&DEV_2204&SUBSYS_136A196E&REV_A1#4&2283f625&0&0019#{5b45201d-f2f2-4f3b-85bb-30ff1f953599}|DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DVI|44048|16857|\\?\DISPLAY#DEL41D9#5&2750cc0a&0&UID25600#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}|NV Surround
```

Why does WinLibrary think there an NVSurround screen, when NVIDIA itself doesn't think so? Even weirder, is that your "Triples plus 4th" profile does show the NVSurroud screen at all! The DisplayProfiles_2.3.json WINAPI display identifiers are correct:

```
"DisplayIdentifiers": [
        "WINAPI|\\\\?\\PCI#VEN_10DE&DEV_2204&SUBSYS_136A196E&REV_A1#4&2283f625&0&0019#{5b45201d-f2f2-4f3b-85bb-30ff1f953599}|DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL|44048|16857|\\\\?\\DISPLAY#DEL41D9#5&2750cc0a&0&UID24833#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}|DELL S2721DGF",
        "WINAPI|\\\\?\\PCI#VEN_10DE&DEV_2204&SUBSYS_136A196E&REV_A1#4&2283f625&0&0019#{5b45201d-f2f2-4f3b-85bb-30ff1f953599}|DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL|44048|16857|\\\\?\\DISPLAY#DEL41D9#5&2750cc0a&0&UID24835#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}|DELL S2721DGF",
        "WINAPI|\\\\?\\PCI#VEN_10DE&DEV_2204&SUBSYS_136A196E&REV_A1#4&2283f625&0&0019#{5b45201d-f2f2-4f3b-85bb-30ff1f953599}|DISPLAYCONFIG_OUTPUT_TECHNOLOGY_DISPLAYPORT_EXTERNAL|44048|16857|\\\\?\\DISPLAY#DEL41D9#5&2750cc0a&0&UID24837#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}|DELL S2721DGF",
        "WINAPI|\\\\?\\PCI#VEN_10DE&DEV_2204&SUBSYS_136A196E&REV_A1#4&2283f625&0&0019#{5b45201d-f2f2-4f3b-85bb-30ff1f953599}|DISPLAYCONFIG_OUTPUT_TECHNOLOGY_HDMI|27934|23410|\\\\?\\DISPLAY#GSM5B72#5&2750cc0a&0&UID24832#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}|24GL600F"
      ]
```

So I'm a little stumped! 

Did you use to have a DVI-D screen that you recently swapped? If so, was it used with an NVIDIA Surround screen as part of a previous DisplayMagician profile?

Or did you save this profile right after swapping from an NVIDIA Surround screen (potentially while the screen was still changing?)? If so, you need to wait until NVIDIA has finished making the changes, or the display profile will be stored incorrectly.

And lastly, I have a sneaking suspicion that the error you see is only a broken display layout image. DisplayMagician creates the image from the display profile file. It is highly likely that the image generation is broken, and that's what you're seeing. In fact, if you look at the profile icon, you can see that it is shown laid out correctly, so I expect there is a bug in the main layout image generation code. I'll go have a look at that tonight.

Can you please try to create two different display profiles and then try to swap between them? Then please send me another Support ZIP File and I'll check it all worked ok. I have a feeling the actual swapping will work, just that I need to fix the display layout image generation code. Oh, please also tell me if the display change actually worked :).

Thanks
Terry

**Comment by terrymacdonald** [comment]
@gptech2444 I also swapped out my own DisplayProfile and used your DisplayProfiles_2.3.json, and DisplayMagician worked fine:

![image](https://user-images.githubusercontent.com/5721772/163057243-6871e3f4-c005-4699-978c-4b9d872778c2.png)

So I think the display layout image logic itself is fine. It looks to be something specific to your machine :(. 

Can you try rebooting to see if that make things work?

Thanks
Terry

**Comment by gptech2444** [comment]
It still only shows the 4th 1080p monitor as the only monitor when the triple 1440's are setup in surround on the layout preview in DM.
I can send you the support file later today.

**Comment by terrymacdonald** [comment]
Hi @gptech2444,

That is strange. Why did it work for me and not for you?

Can you please try deleting that display profile and then try saving it
again? Does it still show in the display layout image incorrectly?

Thanks

*Terry*

**Comment by gptech2444** [comment]
[DisplayMagician-Support-20220413-1745.zip](https://github.com/terrymacdonald/DisplayMagician/files/8479195/DisplayMagician-Support-20220413-1745.zip)

DM crashed just before creating that support file.

**Comment by terrymacdonald** [comment]
@gptech2444 Great news! I found some bugs that may explain what you were seeing. The graphics calculation logic was wrong for some NVIDIA configurations, so I've overhauled the calculations to use the new NVIDIA DisplayConfig features that were added in this latest release of DisplayMagician. This greatly simplifies the graphics calculation logic so I know it will work more reliably. I still have a little bit of work to go to properly grab windows taskbar location and map that to the NVIDIA display ids, but I'll do that tomorrow (it's very late here).

Additionally, I found a few errors in the ShortcutForm that occurred when creating a new Game Shortcut. It would result in a 'null:' error and not much other explanation. That took most of tonight to fix :/. Turns out it was a missing list initialisation in the Shortcut object itself, and so I managed to remove a pretty tricky underlying error..... so that's great news too.

I should have another build for you to try in a day or two, and hopefully this one will work \o/

Thanks
Terry

**Comment by terrymacdonald** [comment]
@gptech2444 New build time! I *think* I've fixed the issues you've experienced. 

I've completely changed the way that display profile layout images have are created, and it's a lot simpler, so should avoid some of the issues that you would have experienced. I've also found some bugs with the rebuild of the ShortcutForm and ShortcutItem that I did in v2.3 and fixed those, so that should stop some of the issues that occurred when creating new Game Shortcuts. 

[DisplayMagicianSetup-v2.3.0.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/8488041/DisplayMagicianSetup-v2.3.0.50.zip)

So can you please download and install DisplayMagician v2.3.0.50 from here and give it a test? If you find any issues please create a  Support ZIP File and upload to this issue.

Thanks!
Terry

**Comment by terrymacdonald** [comment]
@gptech2444 I think this version will work for you. Can you please install this version instead of the one I suggested in previous comments and test that the problem is fixed, and then report back here.
[DisplayMagicianSetup-v2.3.1.7.zip](https://github.com/terrymacdonald/DisplayMagician/files/8494408/DisplayMagicianSetup-v2.3.1.7.zip)

If the issue is fixed then please also close this issue so I can keep track of when I can release this new version to the general population.

Thanks
Terry

**Comment by gptech2444** [comment]
That appears to be working. I had to delete the profile I had and save a new one. It did crash once the first time I tried but was ok on the 2nd try.
[DisplayMagician-Support-20220415-1732.zip](https://github.com/terrymacdonald/DisplayMagician/files/8494631/DisplayMagician-Support-20220415-1732.zip)

**Comment by terrymacdonald** [comment]
Hi,

Can you please tell me what hardware you have (model number of screens,
what sort of connection they have to the screens, how many video cards you
have).

Also if you're on windows 11, and what version of NVIDIA drivers you have,
and what version of DisplayMagician you are using.

And then please generate a Support ZIP File (click on Settings button on
the main application screen. Drag and drop it into the GitHub issue using
your web browser, and it will be uploaded so I can get it.

With all that I should be able to see if there is anything wrong, and I
will hopefully have a better idea of a fix.

If you're using DisplayMagician v2.1.5 then there is a known issue when
going from a surround screen display profile to a non-surround screen
display profile that I've fixed in the codebase. It will be released with
the next release.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Ah perfect! I'll take a look tomorrow morning before I start work to see if
there is anything simple to fix.

Thanks
Terry
