### ISSUE TITLE
BSOD when switching monitor profiles

### ISSUE THREAD

**Issue by jamesd408** [terrymacdonald/DisplayMagician#95]
**Describe the bug**
BSODs occurs occasionally when switching monitor profiles. It occurs when switching from my 2 monitor profile to my 3 monitor Surround profile.

**Environment
 (please complete the following information):**
 - Windows Version: Win11
 - DisplayMagician Version: 2.1.55
 - Video Card: Asus RTX2080 Super
 - Number and make/model of monitors: 3x LG LG GN650-B (DP), 1x Dell S3220DGF (HDMI), 1x HP VH240a (HDMI)
 - Date of last video driver update: 512.15
 - Date of last windows update: Up-to-date

**Additional context**
This has been happening for a few months across multiple driver / windows versions.

[BSOD Memory Dumps.zip](https://github.com/terrymacdonald/DisplayMagician/files/8429524/BSOD.Memory.Dumps.zip)
[DisplayMagician-Support-20220406-1431.zip](https://github.com/terrymacdonald/DisplayMagician/files/8429503/DisplayMagician-Support-20220406-1431.zip)

**Comment by terrymacdonald** [comment]
Hi @Janesd408,

Have you tried deleting your old display profiles, and then recreating
them?

DisplayMagician dumps the display configuration raw from windows and the
NVIDIA driver. This is done so that we capture as many settings as possible
from the current display configuration, but it does also mean that
DisplayMagician is susceptible to errors if there are large changes in the
NVIDIA driver or in windows itself. If the NVIDIA driver changes, or
windows changes and you start getting errors, then it is time to recreate
the display profiles, as it is possible that some new display settings are
missing and the display profile needs to be recreated.

NVIDIA fairly recently updated their driver to the to the 512.x version, so
this may have caused your issue. If you have no over from windows 10 to
windows 11, then you'll also need to recreate your display profiles.

To recreate your display profiles you simply delete them from the Display
Profiles window, then recreate then. You then need to edit each Game
Shortcut, and then select the new display profile you want to use with that
game shortcut, and then save the change.

Hopefully everything goes back to working! If not, I'll take a deeper look.

I'm also nearly ready to release DisplayMagician v2.3.0. is the product of
about 8 months work and has quite a few improvements and bug fixes in it.
If the display profile changes don't work then that update may. (Note:
v2.3.0 will also require users to recreate their display profiles as it
does a lot more settings).

Thanks
Terry

**Comment by terrymacdonald** [comment]
Hi @jamesd408,

I've just finished DisplayMagician v2.3.0.35 which is hopefully the next big release of DisplayMagician. It has a lot of improvements and bug fixes to the NVIDIALibrary, and it's possible that it will solve the issues that you've been experiencing. NVIDIALibrary can now handle multiple physical adapters in a logical group, dvi-d and earlier connections, USB connected displays, adaptive sync, image scaling, cloned displays and more. 

[DisplayMagicianSetup-v2.3.0.35.zip](https://github.com/terrymacdonald/DisplayMagician/files/8457813/DisplayMagicianSetup-v2.3.0.35.zip)

Can you please download and install DisplayMagician v2.3.0.35, and then do the following two steps:

- Delete your old Display Profiles 
- Create new Display Profiles 
- Update your Game Shortcuts to use the new Display Profiles

If you have any issues, please create a Support ZIP File (main screen > Settings > Create Support ZIP File) and upload it here through your web browser. I'll then be able to use that for any bug fixing.
 
Thanks
Terry

**Comment by terrymacdonald** [comment]
Sorry! We just found an issue with some botched Display Profile upgrade logic :(.  Now fixed.

Please do the following:

- Delete `C:\Users\<Username>\AppData\Local\Displaymagician\Profiles\DisplayProfiles_2.3.json` if it exists.
- Install this new DisplayMagician version:
[DisplayMagicianSetup-v2.3.0.36.zip](https://github.com/terrymacdonald/DisplayMagician/files/8467396/DisplayMagicianSetup-v2.3.0.36.zip)
- Run DisplayMagician
- Create your Display Profiles again the way you want them
- Update your Game Shortcuts to use the new Display Profiles
- Have fun with your games!

Hopefully it should work this time.  Please log a new issue at https://github.com/terrymacdonald/DisplayMagician/issues/new/choose if you experience any new bugs that you've not seen before, and I'll get right on fixing them.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@jamesd408 New build time!

I've completely changed the way that display profile layout images have are created, and it's a lot simpler, so should avoid some of the issues that you would have experienced. I've also found some bugs with the rebuild of the ShortcutForm and ShortcutItem that I did in v2.3 and fixed those, so that should stop some of the issues that occurred when creating new Game Shortcuts. 

[DisplayMagicianSetup-v2.3.0.50.zip](https://github.com/terrymacdonald/DisplayMagician/files/8488041/DisplayMagicianSetup-v2.3.0.50.zip)

So can you please download and install DisplayMagician v2.3.0.50 from here and give it a test? If you find any issues please create a  Support ZIP File and upload to this issue.

Thanks!
Terry

**Comment by terrymacdonald** [comment]
@jamesd408 I'm going to close this issue as it should be fixed in DisplayMagician v2.3.1.7 which will be released within the couple of days. I'm closing this case so I can keep track of which issues are outstanding. 

If you still have the same problem once DisplayMagician v2.3.1.7 is released, please feel free to reopen this issue. If you have a new issue please open a NEW issue so I can track that prolem separately.

Thanks
Terry
