### ISSUE TITLE
V2.3.1.12 - Superdisplay with Duplicate Mode not Loading Correctly

### ISSUE THREAD

**Issue by cerahmed** [terrymacdonald/DisplayMagician#96]
**Describe the bug**

My setup is as follows: 

Monitors 1,2,3 -> Normal Wired Monitors to RTX3070 (DP/HDMI).
Monitor 4 -> Android phone connected through USB via Spacedesk app.
Monitor 5 -> Android tablet connected through Wi-Fi via Superdisplay app.

I'm using the latest version V2.3.1.12 found in [issue#88](https://github.com/terrymacdonald/DisplayMagician/issues/88#issue-1134162268).

When all monitors are **extended** monitors, the profile saves fine and load correctly. However, one issue here is that the monitor preview in Display Magician does not show the Spacedesk monitor (android phone), nor the Superdisplay wireless monitor (android tablet), but it saves and load them correctly. (First screenshot)

When the SuperDisplay monitor is duplicaing the main monitor (Monitor#1 - HDMI), the profile saves but DOES NOT load correctly. Both the Android phone and tablet become unavailable. (Second screenshot)

**To Reproduce**
Using SuperDisplay wirelessly in Duplicate Mode.

**Expected behaviour**
When using SuperDisplay in Duplicate Mode, profile must load correctly instead of disabling USB/Wireless monitors.

**Screenshots**
First Issue (Preview not showing USB/Wireless monitors):
<img width="959" alt="Issue#1" src="https://user-images.githubusercontent.com/21166481/163736826-7ff073a5-388e-48e0-8cc3-604cb49d740b.png">

Second Issue (SuperDisplay in duplicate mode makes both USB and Wireless monitors unavailable):
<img width="961" alt="Issue#2" src="https://user-images.githubusercontent.com/21166481/163736828-d4b216c2-3de5-4dd6-bee0-3722f2ffda3f.png">

**Reporting Logs**
If DisplayMagician starts:
- Open DisplayMagician and perform whatever actions are needed to make the bug occur.
- Click on the Settings button on the main DisplayMagician window
- Click on 'Create a Support Zip File' button
- Save the Support Zip File on your computer.
- Come back here, and upload the Support Zip File through your web browser and attach it to this issue.

[DisplayMagician-Support-20220418-0253.zip](https://github.com/terrymacdonald/DisplayMagician/files/8502663/DisplayMagician-Support-20220418-0253.zip)

If DisplayMagician does not:
- Open a terminal window and run `C:\Program Files\DisplayMagician\DisplayMagician.exe --trace` to create a TRACE-level DisplayMagician.log file.
- The above command will create a DisplayMagician.log file in `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Logs` which should contain a LOT of detailed TRACE level log entries. 
- Come back here, and upload the DisplayMagician.log file through your web browser and attach it to this issue.
- Also attach the following files to this issue:
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Profiles\DisplayProfiles_2.1.json` 
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Shortcuts\Shortcuts_2.0.json`
  - `C:\Users\<yourusername>\AppData\Local\DisplayMagician\Settings_2.0.json`

**Enviroment (please complete the following information):**
 - Windows Version: Windows 11
 - DisplayMagician Version: V2.3.1.12
 - Video Card: RTX 3070
 - Number and make/model of monitors: 5 Monitors described above.
 - Date of last video driver update: Latest.
 - Date of last windows update: Latest.

**Comment by terrymacdonald** [comment]
Hi,

I've not heard of Spacedesk before. I might try to find out more about how
it works. I expect it will be like Superdisplay, which meant I needed to
add a new video card vendor ID to the supported list. I expect I'll need to
do that to get it to work.

There may also be some issues in how either application interacts with the
NVIDIA Display Config functions. In order to add support for some of the
more advanced NVIDIA features, I moved the additional screens logic from
using windows display CCD config to the NVIDIA Display config. This may not
work with Spacedesk and Superdisplay.

I'll see what I can find in the logs, but it may be a problem I can't fix.

Thanks
Terry

**Comment by cerahmed** [comment]
Hi Terry,

I can confirm that the issue does NOT have to do with Spacedesk per se. I have disconnected disabled Spacedesk, keeping only 3 wired monitor + 1 Superdisplay.

I went ahead and recreated new profiles as above: 1) with Superdisplay as an extended display, and 2) with Superdisplay duplicating the main monitor.

The same behavior still persists: I can apply the extended display profile, but NOT the duplicate monitor profile.

I believe it has something to do with the duplicate mode is what causes the error.

**Comment by cerahmed** [comment]
Update:

Strange thing. I have tried Monitor Profile Switcher app ([Link](https://sourceforge.net/projects/monitorswitcher/)) and I was able to switch to the "duplicate" profile (where my Superdisplay monitor is duplicating the main monitor), but the app fails to load the extended profile (where my Superdisplay is an extended monitor)!

Quite the opposite result I'm getting with DisplayMagician!

Temporarily I'm using Display Magician to switch to the "extended" profile, and Monitor Profile Switcher to switch to the "duplicate" profile.

I'm sharing to say that it is somehow possible to do it, and you might find it helpful in your research for the issue.

**Comment by terrymacdonald** [comment]
Hi,

It is possible to do, it's more a question of whether DisplayMagician can
do it.

This version of DisplayMagician now uses the NVIDIA display config
functions to extract the advanced settings that allow us to track things
like image scaling. This is functionality that a lot of people have been
asking for, and it's taken a bit of work to try and get working properly.

There is a possibility that the new NVIDIA display config functionality is
conflicting with the windows CCD display config settings and is causing the
error you're getting. We used to use the windows CCD display config
settings, but this doesn't let us use any of the NVIDIA advanced settings.

If this is the case, then there is a real possibility that I won't be able
to fix your issue without affecting the new NVIDIA advanced settings
additions that many users want.

I'll do my best to try and fix this issue, but I did want to make sure that
you knew it is something that I may not be able to fix. I'm hoping it's not
a conflict with NVIDIA display config, because then it's something I might
be able to fix.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@cerahmed After doing some digging it looks like it may be something related to the patching of the windows HDR configuration  for SpaceDesk.  This bit specifically:

````
2022-04-18 02:47:55.1002|TRACE|DisplayMagician.Program|WinLibrary/PatchAdapterIDs: Going through the display config paths to update the adapter id
2022-04-18 02:47:55.1002|TRACE|DisplayMagician.Program|WinLibrary/PatchAdapterIDs: Going through the display config modes to update the adapter id
2022-04-18 02:47:55.1002|TRACE|DisplayMagician.Program|WinLibrary/PatchAdapterIDs: Going through the display config HDR info to update the adapter id
2022-04-18 02:47:55.1002|DEBUG|DisplayMagician.Program|ProfileRepository/ApplyProfile: Failed to complete changing the Windows Display layout
2022-04-18 02:47:55.1002|DEBUG|DisplayMagician.Program|ProfileRepository/ApplyProfile: Display change attempt took 0:1.777 and failed.
````

There should be some additional "Going through ..." log entries in there as it patches the various parts of the config upon loading. It's stopping at the HDR processing part, which is odd. I have added some more logging to that area of the code, so that when I get round to packaging the next test release it will give us more insight into what it going wrong.

I'll take a deeper look at your logs over the next few days and see if anything else weird pops out.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@cerahmed Can you also please try this version 2.3.1.27 of DisplayMagician, as it has some more logging in the areas I've mentioned above. 
[DisplayMagicianSetup-v2.3.1.27.zip](https://github.com/terrymacdonald/DisplayMagician/files/8508398/DisplayMagicianSetup-v2.3.1.27.zip)

Please delete and recreate your two display profiles. Please then try swapping between your two display profiles and tell me if they work.

Please also generate a Support ZIP File and upload it to this issue through your web browser. Hopefully this will give me more information to go on.

Thanks
Terry

**Comment by cerahmed** [comment]
Hey Terry, you're a genius! .. it works flawlessly now.

- I have uninstalled the previous version and installed v2.3.1.27.
- Rebooted the PC, then recreated new profiles for both Extended Superdisplay + Duplicated Superdisplay.
- Switched to the Extended profile, then back to the Duplicated profile .. works!
- Saved the logs in the attached zip.

The only MINOR issue remaining is that the monitors preview doesn't show Superdisplay nor Spacedesk in the layout, which does not bother me at all.

I'm happy to do further testing should you require.

[DisplayMagician-Support-20220419-0429.zip](https://github.com/terrymacdonald/DisplayMagician/files/8509101/DisplayMagician-Support-20220419-0429.zip)

**Comment by terrymacdonald** [comment]
Hi,

I *think* I know where the issue may be. I'll use your logs to confirm over
the next few days and see if I can figure out a workaround.

My guess is that moving the display logic to use the NVIDIA config for
NVIDIA devices also stopped the Superdisplay and Spacedesk from being seen
by that code.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@cerahmed Right. I've bashed out some code and I *think* it will work. My guess appears to be right. The issue was that the display layout image generator used the NVIDIA display config driver functions, and unfortunately they only return the displays connected to the NVIDIA driver :/. Not what we wanted.

The new code also checks the displays that Windows knows about, and then it compares the list of the two. Any displays that Windows only knows about are added to the list of displays shown in the images we make. TLDR; Your displays should show up now.

Unfortunately all my displays are connected through an NVIDIA card, so I can't test. Can you please test, and then report back with what you find? Please also create (yet another) Support ZIP File and drop it here from your web browser.

Please install this DisplayMagician version 2.3.1.28: [DisplayMagicianSetup-v2.3.1.28.zip](https://github.com/terrymacdonald/DisplayMagician/files/8509644/DisplayMagicianSetup-v2.3.1.28.zip)

Fingers crossed this works for you 🤞.

Thanks
Terry

**Comment by cerahmed** [comment]
Works perfectly and shows correct monitors previews!!

1) Uninstalled previous version and installed v2.3.1.28.
2) Rebooted the system, deleted the previous profiles, and recreated new ones for Extended + Duplicated (below screenshots).
3) Tried switching back and forth between Extended and Duplicated profile .. flawless!
4) Saved the logd (attached).

<img width="500" alt="Extended" src="https://user-images.githubusercontent.com/21166481/163922025-23d1b83f-217b-40f2-8e66-ecc023c2f6eb.png">


<img width="500" alt="Extended" src="https://user-images.githubusercontent.com/21166481/163922080-449e0058-5920-4999-9623-9c45c1c7b473.png">

All monitor positions and count are correct in the preview, even the "cloned" Superdisplay shows up as +1 Clone. Perfect.

Much much appreciated! Let me know if there are any other testing you'd want me to do.
[DisplayMagician-Support-20220419-0743.zip](https://github.com/terrymacdonald/DisplayMagician/files/8509894/DisplayMagician-Support-20220419-0743.zip)

**Comment by terrymacdonald** [comment]
Issue foxed in mainline code, so closing issue.

**Comment by terrymacdonald** [comment]
Ok, I'm closing this issue. Will be permanently fixed in mainline code.

Thanks
Terry
