### ISSUE TITLE
Unable to Save MS Flight Simulator Game Shortcut

### ISSUE THREAD

**Issue by mastercko** [terrymacdonald/DisplayMagician#98]
DisplayMagician version: 2.3.1.60
OS: Windows 10
OS Version: 10.0.19044 Build 19044
Nvidia GeForce Drivers Version: 512.15

Upon updating to the new version of DisplayMagician, I was able to recreate both of my Display Profiles as expected. 
When I went to my Game Shortcuts to update them, all of them were marked with an exclamation point, which I expected, given the update and the need to redo the profiles. 
The first three that I set up, I was able to easily update them to use my newly re-created Nvidia Surround Profile, but the fourth one (which is MS Flight Simulator), when I go into the edit window and change the display to the new "Surround" profile, the "Save" button is blank, so it won't allow me to save the change. 

I created this Game Shortcut in a previous version of DisplayMagician (the same as the other 3) and the only thing I'm trying now is to change is update the display profile, so no idea why it won't allow me. FYI I am able to make brand new Game Shortcuts from scratch, except I can't get one that points to MSFS to save even if I try rebuilding it from scratch, so my guess is that maybe something changed in what the screen validates as "savable" and therefore when to show the "Save" button? Just a guess.

The way I constructed it is to launch Fast Launcher utility for the game (which strips it of all the logo videos in the game start sequence), then wait for the actual executable of the game itself to end.

**Comment by mastercko** [comment]
Upon looking in the logs, I'm seeing this:

> 2022-04-23 14:09:03.5559|ERROR|DisplayMagician.UIForms.ShortcutForm|ShortcutForm/CanEnableSaveButton: The alternative application executable the user wants to monitor doesn't exist. Please check the file 'C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.22.2.0_x64__8wekyb3d8bbwe\FlightSimulator.exe' is still there, and that the file has the correct permissions.

So just to avoid this I'm trying to delete or switch away from the "wait for alternative executable" setting, but even if I do that, the Save Button is still not displaying.

**Comment by terrymacdonald** [comment]
Hi @mastercko ,

Is the file 'C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.22.2.0_x64__8wekyb3d8bbwe\FlightSimulator.exe' actually there? Can you open windows explorer and go to that location? It might be that flight simulator has been updated,  and no longer exists in that location.

If it does still exist in that location, then how are you adding it to the game shortcut? Are you adding it from the game library section, or adding it as an application in the upper section?

Can you also please create a Support ZIP File from the settings section (press the Settings button on the main form) and then upload it to this issue using your web browser.

That information will then help me figure it what's going won't.

Thanks
Terry

**Comment by mastercko** [comment]
Hi @terrymacdonald,

Thanks for jumping on so quick. 

Regarding your first question: Yes, the file exists there. Attached is the Windows explorer screenshot of it.
![Screenshot 2022-04-23 195216](https://user-images.githubusercontent.com/6900268/164891595-8c12c8fc-d3cc-4691-858e-89913d7b27e3.png)
The way that I initially added it to that edit window is by copy-pasting the text of its address (C:\Program Files\WindowsApps\Microsoft.FlightSimulator_1.24.5.0_x64__8wekyb3d8bbwe\FlightSimulator.exe) directly into the "additional executable" field.

BTW, please note that because that folder (**C:\Program Files\Windows Apps**) is a special system folder where the Windows Store installs apps, it is kind of a tricky mess to get access permissions to even view the contents of it in order to show it to you -- by default, that folder is not viewable by a normal Windows user.

Also, attached is the support zip file.
[DisplayMagician-Support-20220423-1406.zip](https://github.com/terrymacdonald/DisplayMagician/files/8546768/DisplayMagician-Support-20220423-1406.zip)

Hope this helps.

Oh, now that I see that you store the settings as JSONs, I realize that I can probably workaround it for now by manually editing the Shortcuts JSON, but I'm still hoping that you can figure out what's going on.

Thanks!

**Comment by terrymacdonald** [comment]
Yeah this could get tricky... I'd rather not remove the file existence
check, as it's necessary to fix another bug that another user had.

I could put in a specific check for the windows store location in the
folder structure, but I think it might be better if I spent some time
figuring out if I can add windows store support to DisplayMagician. It
would be best if I could just have the windows flight simulator show up in
the games list.

If editing the games shortcut directly in the json file works, then stick
with that for now, and I'll see I if I can add windows store support in
2.4.0.

Thanks
Terry

**Comment by mastercko** [comment]
Understood. Yeah, it would be great to get support for the Windows Store version of MSFS (and other games), for sure!

 Thanks again for your help!

**Comment by terrymacdonald** [comment]
OK, so I've been working on a new code branch that adds the Xbox Game store into the GameLibrary section of DisplayMagician, and also adds the ability to choose applications from a list of installed applications (UWP and other installed apps). I'm *hoping* that your installed copy of MS Flight Simulator will show up in one of those lists. 

Can you please install the MS Xbox Game application from MS Store, and please confirm if MS Flight Simulator will show up in there for you? I'd like to test if the Xbox App will work: https://apps.microsoft.com/store/detail/xbox/9MV0B5HZVK9Z

It will still be a while before I can get this sorted, but I just wanted to know I am working on it.

Thanks
Terry

**Comment by mastercko** [comment]
Yep, it shows up in the Xbox App!

![image](https://user-images.githubusercontent.com/6900268/168331901-eabb3fd1-bf90-4f95-8940-6e512db89042.png)

Nice to hear you are working on it. Thanks so much!

**Comment by terrymacdonald** [comment]
@mastercko Just letting you know I've been fixing some bugs first before working on the addition of the Xbox App and the redesign of the application detection logic. The bug fixing is going way quicker than I thought it might, so I might get to this redesign faster than I thought. 

I'm torn at the moment as to whether I should just release a new v2.3.2 hotfix, or whether I should just work an extra week longer to release a v2.4.0 with this new functionality in it.

My gut feel at this stage is to wait a bit longer and just release one update. But we'll see how that pans out :)

Thanks
Terry

**Comment by mastercko** [comment]
Awesome, great news! Can't wait to try it out.

**Comment by terrymacdonald** [comment]
@mastercko Letting you know I'm almost ready to release the DisplayMagician v2.4.0, as there has been a big amount of errors I've been asked to fix. I've found and fixed the errors, but they are all impacting a wide number of people, and causing other issues to be logged. I need to get that 2.4.0 release out the door so that everyone patches and DM becomes more robust and reliable.

This doesn't fix your problem unfortunately, but rest assured once 2.4.0 is out the door I will start working on the UI updates, Xbox app and Windows UWP app scanning that should make it easier for you to use MS Flight sim in DM. That is quite a bit of work as I need to write a new Xbox Game Library and add in support for UWP scanning, which an be a pain. So it might still take a few weeks to get it sorted.

At this stage I think it is a non-breaking change, and if it stay that way then I will release all that as the next version v2.4.1. If there are breaking changes then I'll release 2.5.0 (breaking changes require a minor version bump, whereas adding new features is a simple maintenance version bump).

While you're here, can you please test out DisplayMagician v2.4.0.10 for me?
[DisplayMagicianSetup-v2.4.0.10.zip](https://github.com/terrymacdonald/DisplayMagician/files/8835910/DisplayMagicianSetup-v2.4.0.10.zip)

It is a test version of DisplayMagician that **hopefully**  is nearly ready to ship. 

PLEASE NOTE: It will rename your old DisplayMagician settings files which will stop older versions of DisplayMagician from working. This is reversible. 

PLEASE ALSO NOTE: You will be required to setup new Display Profiles. This is because we're added new settings (NVIDIA 3D Settings, and Windows DPI Scaling).

Please check the following when you test this version of DisplayMagician that:
- You are informed during first run of DisplayMagician that you will need to create new Display Profiles
- Your Game Shortcuts are still there, and that you can update them with the new Display Profiles you create.
- That you can swap between all the Display Profiles you create without any errors.

Please reply with the results of your testing.

Thanks
Terry

**Comment by mastercko** [comment]
Hi,

Sorry, I have been busy with work for a while, so I wasn't able to get to this until now. Regarding the specifics of the upgrade, this is what happened for all the tests:

* Test: Informed during the first run of need to create new Display Profiles
  * Result: PASS
* Test: Game Shortcuts are still there and I can update them
  * Result: FAIL
  * Note: All Game Shortcuts are missing from Game Shortcut Library menu
* Test: Can swap between all the Display Profiles you create without errors
  * Result: PASS
  * Note: While I was doing the switching back and forth (I did it 2x each way), Chrome crashed for some reason. Not sure if this is something that has to do with the DisplayMagician specifically or not, but just thought I would mention it. Other than that, it worked fine, hence the PASS.

Hope this helps.

**Comment by terrymacdonald** [comment]
@mastercko Great news! DisplayMagician v2.4.1 is now released and much more reliable than v2.3.1.60 was, so that's great. But another great bit of news, is that I've been able to start work on making it easier to add installed applications to DisplayMagician.

I wanted to give you a heads up on what I've been working on. I've managed to get a new interface working for selecting applications/game executables. This is what you will see when you click on the 'Choose' button in the Executable section:

![image](https://user-images.githubusercontent.com/5721772/177290461-1ac754b6-4a37-4c2b-bd32-979a2b412a71.png)

Is this the sort of thing you wanted to have?

I'm also shortly working on getting the Xbox App games into the Game Library. That will take a little bit longer to sort as I need to do some more discovery work on that....

Once I've finished up the code over the next 2 weeks I'll drop a test version of DisplayMagician 2.5.0 in here for you to test.

Thanks
Terry

**Comment by mastercko** [comment]
Congrats on getting the update out. I have already updated and it's working well for me so far. Thanks!

And that looks great! Would be glad to see an easy to select solution like that. 

Looking forward to testing out the update once its ready!

**Comment by terrymacdonald** [comment]
@mastercko Well this is all taking way longer than anticipated. It turned out that the only way to properly handle installed applications was to create another class of running item (alongside executables and games), which has necessitated writing quite a lot of new code.  It's all taking a while to sort out. I've also managed to create a lot of bugs too, some of which have been difficult to flush out.

Additionally, I found out that the Xbox Games also appear in the Applications list, so at this stage I might skip adding the Xbox Game Library, and just keep the Applications as the way to launch Windows Store Games, at least for now. I can then add the Xbox Game Library support in the next version after 2.5.1.

I also took a diversion into improving the Icon/Thumbnail capture in DisplayMagician too, which has been useful. I moved to using some newer Windows 10 APIs to make the capture more reliable, which appear to have worked. And I worked on making the JSON config file loading and saving more reliable too. As well as fixing a major NVIDIALibrary bug when reverting from surround to non-surround profiles, and lastly providing more information about upgrades when DisplayMagician starts, and providing the ability to delay an upgrade for a week.

I'm now getting to the point that I'm down to about 10 bugs left, so I'm hoping I'll be able to troubleshoot the ;last of them over the next 2 weeks, and hopefully then I'll be ready to release.

Wanted to make sure you knew I hadn't forgotten you :).

Thanks
Terry

**Comment by mastercko** [comment]
Cool, thanks for the update!

**Comment by terrymacdonald** [comment]
@mastercko I think I'm ready for you to test 2.5.0.320 that I've linked to below. Please install it over the top of your existing DisplayMagician install, and give it a test:

[DisplayMagicianSetup-v2.5.0.320-test.zip](https://github.com/terrymacdonald/DisplayMagician/files/9440582/DisplayMagicianSetup-v2.5.0.320-test.zip)

This new DisplayMagician has quite a lot of new code to support a new type of thing to run... an Application. An Application is a program that has been installed into Windows using an installer, and includes applications installed via MSI/EXE/APPX installers as well as those installed via the Microsoft Store (e.g. UWP Apps). This should enable you to directly start and run Microsoft Flight Simulator.

To set up a Microsoft Flight Simulator Game Shortcut, please:

- Select the **New** button from the Game Shortcut Library window. 
- Choose the **4. Choose Game to start** tab
- Click on the **Launch a Game or Application executable** radio button
- Click on the **Choose** button
- Select the Microsoft Flight Simulator application from the list of Applications on the left.
- Click on the **Select Application from List** button
- Finish setting up the rest of the Game Shortcut as normal.

Please test that out, and see if it works ok. Either way, please report back what you find, and we'll work through the bugs and errors you find. I'm hopeful that I've squashed most of the bugs already, so hopefully it won't be too long until I manage a new release!

Oh - Also please test the new built-in FOV Calculator to make sure it works ok and is useful. You can access it from the **FOV Calc** button on the main DisplayMagician window. I'd appreciate some feedback on that too.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Just a warning - some of the Application monitoring that worked in testing haven't been working for me with real apps in a new installed DisplayMagician v2.5.0. Would be good if you could test so that I can see what is going wrong. I'll try doing some testing over the next few days but it may be delays thanks to covid.

Thanks
Terry

**Comment by terrymacdonald** [comment]
Oh also - I just re-read your original post, and I just realised that I forgot to add the Windows Store App support to the 'alternative exe' part of the Game Shortcut code :(. This means that the same problem you had at the start is still there 🙄 . Sheesh Terry.

A simple way is for me to work around this for now is to look for the Windows App path (C:\Program Files\Windows Apps) and to ignore the file exists check for those apps. It's not pretty, but it will at least let you continue testing while I figure out a more permanent solution....

Thanks
Terry

**Comment by mastercko** [comment]
Hi, thanks so much! I'll try to get around to testing it this weekend and let you know what I see. Much appreciated!

**Comment by mastercko** [comment]
Hi Terry,

I just tried out the new build and it worked great for me! In order to test it, I didn't use the separate wrapper app (as I originally described in my first message) and instead added MSFS directly from the App List, so that I could test the new functionality. The system went to Surround and the game launched exactly as expected, and after leaving the app, went back to Triple Desktop, also as expected! Yay!

The only (minor) issue that I had is that I couldn't get an added flag to work to the end of the launch string. 

Basically, for MSFS, one should be able to add the flag -FastLaunch to the end of the string in order to skip the company logos that usually come up at the beginning of the launch (see, for example: https://forums.flightsimulator.com/t/fast-launch-not-working/511351), but putting that tag at the end of the generated string that your selection UI adds to the argument section unfortunately doesn't do anything and the game just launches as normal, company logos and all.

Again, this is very minor. I can totally live with this issue if it means that I can properly launch into the game and kick into Surround mode and leave the game and have it go back to Triple Screen, which this does flawlessly from what I can see.

Thanks so much for all your work on this issue so far!

**Comment by terrymacdonald** [comment]
Hey that's great news!


I didn't know that the shellapps shortcut command worked with CMD.exe as
well. That's a much better solution than using explorer.exe. I'll try
swapping over to using CMD.exe instead.

It's interesting that MSFS monitoring for application closing works for
you, as it recently stopped working for me when I was testing the Microsoft
Mail App on Windows 11. I'll have to test windows 10 to see if it works
there or not.

So a bit more testing and modification to be done, but at least we have
some progress!

What do you think of the new application selector UI? It's it simple enough
to use? Any changes you think it needs?

Thanks
Terry

**Comment by terrymacdonald** [comment]
Also, do you think that I still need to add a Xbox library, or will it work
ok using the installed applications as your doing now?

Thanks
Terry

**Comment by mastercko** [comment]
hey again!
To your two questions (sorry in advance for length):

- _What do you think of the new application selector UI? It's it simple enough to use? Any changes you think it needs?_

I thought it was totally fine. Definitely simple enough and easily understood on first usage. Might be nice to be able to switch between icon mode and list mode and give sort options (alphabetical forward and reverse, install date forward and reverse, etc.), but those are very much icing. It works perfectly well as is.

- _Do you think that I still need to add a Xbox library, or will it work ok using the installed applications as your doing now?_

Hmmm, this is a good question. If adding the Xbox library is a huge undertaking, I think that it's probably fine as is. I can see this new dialog window being useful for any of the application selecting screens (for example, when selecting what other apps to launch when launching a game, etc), so in that sense, it's definitely better to keep it general purpose. That being said, when selecting the game to launch, I was still unconsciously expecting to see MSFS in the auto-populated "Steam, Uplay, GOG" list at the bottom of the main wizard window (even though I knew it wasn't there), so if time and resources were infinite, I would say it would be nice to have both methods (the application selector for all the manual "select application" uses, as well as populating Xbox Library games into that auto-filled list of all games in the main wizard). Again, though, the flow here already works well for my use case and the dialog is quite easy to understand, so I think it's totally fine as it is now.

**Comment by terrymacdonald** [comment]
Thanks @mastercko, that helps a lot.

I agree with the Xbox games expectation that they are in the list of games.
That's what I feel too. Unfortunately at the moment I'm not sure how to
extract only the Games from the list of applications. I'm hopeful that the
Xbox App has the ability to do so, so I might spend some time looking at
the Xbox API, registry and file structures to see if I can extract the
installed game information from the Xbox side of things before I release
v2.5.1. I'll do some digging in some of my limited spare time and see what
I can find.

Thanks

*Terry MacDonald *| Principal Security Consultant | Chief Operating Officer



M: +64 211 918 814 <+64+211+918+814>
E: ***@***.***
W: www.cosive.com

**Comment by mastercko** [comment]
Sounds great! Again, thanks so much for all the improvements, it is really appreciated!

**Comment by terrymacdonald** [comment]
@mastercko Darn it! The finished version doesn't work for Windows Store Apps :(. It works perfectly fine during development and when I'm running it from within Visual Studio, but not when I have a finished application that I install through the installer exe.

Further research showed that it is a Windows 10/11 permissions reason behind all this. DisplayMagician 2.x is a Windows Desktop program. It is designed to work with the older Windows 7 APIs. Unfortunately those older apps aren't able to inspect and control Windows UWP Apps. Windows UWP Apps use a completely different permissions model that Windows Desktop APIs can't access (at least as far as I can tell!).

It appears that I will need to change DisplayMagician from a Windows Desktop program to become a UWP App in order for me to get access to the Windows APIs I need to see other UWP Apps. This is a huge undertaking, as I effectively will need to reengineer DisplayMagician and rearchitect it to make it all work.

I will try to see if anyone else on the internet has managed to figure out a way around that restriction, but as far as I can tell there is no way around it. I'll keep you updated with anything I can find, but unfortunately it's not looking good :(.

Thanks
Terry

**Comment by terrymacdonald** [comment]
And literally 10 seconds after I send you a message, I find something that may be easier for me to do :).

It looks like I may be able to migrate to .NET 6 and then I will be able to access some of the Windows Runtime APIs that I need to do the job. I'll do some experimenting and see where I'll end up.

Terry

**Comment by mastercko** [comment]
Heh, glad that you found an easier solution...phew! Hopefully this will pan out. Fingers crossed to see an update come down the pipe! As always, much appreciated!

**Comment by terrymacdonald** [comment]
@mastercko I have a new test version for you to try! This version adds a few robustness features, and adds a warning message to say that DIsplayMagician can run UWP apps from the MS Store, but cannot monitor them. I've spent much of today trying tow work around that problem, but it turns out that its a Windows Permission error, and it won't be soled until I move to DisplayMagician v3.0, when I'll move DisplayMagician to being a UWP app itself!

Could you please download and install this test version of DisplayMagician and see if it works ok? If you have errors please ensure that your DM logging level is set to 'TRACE' from within the Settings page, and then see if you can cause the  issue, then send me another Support ZIP File. 

[DisplayMagicianSetup-v2.5.0.331.zip](https://github.com/terrymacdonald/DisplayMagician/files/10235613/DisplayMagicianSetup-v2.5.0.331.zip)

This version of DisplayMagician adds quite a few new features (e.g. a built in FOV calculator for if you are a simracer) and hopefully works fine. If you could install  and give it a test I'd really appreciate it!

Thanks
Terry

**Comment by mastercko** [comment]
Oh wow, this sounds like an awesome update. I'll give it a try as soon as I can! Thanks!

**Comment by mastercko** [comment]
Understood, no worries. I have worked in games and software, so I am definitely aware of the phenomenon of looking into fixing a bug or adding a new feature that sounds simple at first, but then leads to a complete refactor being needed. :) The plan for the 3.0.0 rewrite sounds pretty extensive, so I am excited to see it when you are ready to unveil it. I am still happy to check the recent update to see how it works on my PC when I get the chance (I also play Assetto Corsa and Beam.NG, so the FOV calculator should be super useful!). 

And just wanted to say again, I really appreciate you taking this on and looking into it! Thanks so much!

**Comment by terrymacdonald** [comment]
This has been fixed in the latest version of DisplayMagician released here: [DisplayMagician v2.5.0](https://github.com/terrymacdonald/DisplayMagician/releases/latest)

I will close this issue for now as the issue should have been fixed, but please feel free to reopen this if that specific issue is not fixed. If you find a different issue please create a new separate issue so that I can work on them separately.

Please note that the new application selection functionality won't work with UWP applications due to Windows permission restrictions. This shouldn't affect your particular MSFS issue as I don't believe that MSFS is a UWP app. I am tracking the UWP application issue internally in my dev task list and will be working on workarounds as part of the DisplayMagician v3.0.0 work. That work won't be shown/tracked in this issue though, which is why I'm closing this issue now.

Thanks
Terry

**Comment by terrymacdonald** [comment]
@mastercko I've been testing opening UWP apps and monitoring them from DisplayMagician, and I think the most recent code changes may have managed to get this working.

[DisplayMagicianSetup-v2.6.0.521-uwp.zip](https://github.com/terrymacdonald/DisplayMagician/files/14227964/DisplayMagicianSetup-v2.6.0.521-uwp.zip)

Can you please install this test version and see that you can open Windows Store apps and DisplayMagician will wait for them to close?

Thanks
Terry

**Comment by mastercko** [comment]
Hi @terrymacdonald 

I just updated to this version and launched MS Flight Simulator Windows Store version with it, then closed it and received a notification from DisplayMagician that the app and all processes closed, so it looks like it is working properly.
